### ISSUE TITLE
VS Code Azure Functions extension defaults a storage account to West US

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1333] opened 2019-06-07 23:28 UTC
VS Code Functions Extension 0.17.1 (Windows)
This is to reduce manual steps but having some visible option for storage location is useful

**Comment by EricJizbaMSFT** [comment] 2019-06-10 16:52
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1317

**Closed by EricJizbaMSFT** 2019-06-10 16:52 UTC
