### ISSUE TITLE
VS Code Functions plugin fails 4 out of 5 times to connect when debugging

### ISSUE THREAD

**Issue by toddysm** [microsoft/vscode-azurefunctions#1378] opened 2019-07-16 04:18 UTC
Repro steps:

1.
2.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to detect running Functions host within "60" seconds. You may want to adjust the "azureFunctions.pickProcessTimeout" setting.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:390:87999
o extension.bundle.js:390:86913
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-07-17 15:44
@toddysm this is somewhat of a known issue, but it's difficult for us to reproduce. If you could share detailed repro steps or anything unique about your project/machine that would be very helpful

Related to https://github.com/microsoft/vscode-azurefunctions/issues/1353

**Comment by toddysm** [comment] 2019-08-05 17:21
@EricJizbaMSFT I am also not able to repro consistently but it is happening quite often. There is nothing special in the steps - just pressing F5 and once works, few times doesn't. I noticed that restarting VS Code fixes it but if VS Code wasn't restarted for a while it happens more often if not every time (could it be memory issue or lack of handles?). If I can get something concrete, I will update the issue. For now, what you can try is having VS Code running for several hours and maybe putting the laptop to sleep few times.

**Comment by EricJizbaMSFT** [comment] 2019-08-05 17:25
@toddysm I actually recently merged a PR to improve this experience. If you've got the time, you can try out a preview build with these instructions and let us know how it goes: https://aka.ms/azCodeInsiders

Closing as duplicate of #1353

**Closed by EricJizbaMSFT** 2019-08-05 17:25 UTC
Labels: needs more info
