### ISSUE TITLE
Unable to see function in tree ... shows "(Invalid)", Error: <!DOCTYPE html>

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurefunctions#929] opened 2019-01-23 21:43 UTC
Create a new python function
deploy it to azure
expand the function in the explorer

result: the Function itself is shown with a warning and marked as "(Invalid)" and if you expand the function you get an `Error: <!DOCTYPE html>` node in the tree:

![image](https://user-images.githubusercontent.com/1487073/51639025-c4054f00-1f14-11e9-8f57-e7963dca6748.png)

**Comment by EricJizbaMSFT** [comment] 2019-01-23 21:53
I assume these are non-anonymous triggers? If so, closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/654

**Closed by EricJizbaMSFT** 2019-01-23 21:53 UTC

**Comment by chrisdias** [comment] 2019-01-23 21:58
yes they are non-anon.  could we (in the meantime) special case this and just not show the sub node, etc.  showing the html in the node is weird.

**Comment by EricJizbaMSFT** [comment] 2019-01-23 22:05
Is "in the meantime" for a demo? If so - can't you just not expand that node? Or are you wanting us to get rid of the "Invalid" stuff, too?

We already have [a fix](https://github.com/Microsoft/vscode-azuretools/pull/360) in master to better parse errors that show up as html (which honestly it's a bug in the functions runtime if it shows up as html but whatever), but I can't verify this specific case because I'm getting ServiceUnavailable.

**Comment by chrisdias** [comment] 2019-01-23 22:12
Yes, the demo is driving my usage of this, but I'm suggesting that we make it look a little nicer anyway.  When is the fix supposed to be released?

**Comment by EricJizbaMSFT** [comment] 2019-01-23 23:41
Early February
