### ISSUE TITLE
Azure subscription not found when trying to create an Azure Function App

### ISSUE THREAD

**Issue by macinson** [microsoft/vscode-azurefunctions#3274] opened 2022-08-04 13:06 UTC
Hi,
I tried creating an Azure Function App based on this walkthrough: https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python. I am able to create a function locally but when I try to create one in resources (remote) it says that my subscription can't be found. The subscription itself is displayed in the resources section.

Action: azureFunctions.createFunctionApp
Error type: SubscriptionNotFound
Error Message: Subscription redacted:id was not found.

Version: 1.7.4
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.69.2
Language: eng

```
handleErrorResponse extension.bundle.js:2:1823131
deserializeResponseBody extension.bundle.js:2:1823862
```

**Comment by nturinski** [comment] 2022-08-04 22:14
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3269

**Closed by nturinski** 2022-08-04 22:14 UTC
Labels: bug
