### ISSUE TITLE
The PowerShell version in status bar is changed from 7.0 to 6.2 when debugging a PowerShell project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2190] opened 2020-06-28 09:59 UTC
**OS:** Windows 10
**Build Version:** 20200625.7
**PowerShell Version:** 7.0

**Repro Steps:**
1. Create a PowerShell project in VS Code.
2. Debug it.
3. Check the PowerShell version from status bar.

**Expect:**
The PowerShell version keeps 7.0 during debugging.
![image](https://user-images.githubusercontent.com/45614674/85944381-ddf85c00-b968-11ea-80d4-c6749f3fdf38.png)

**Actual:**
The PowerShell version is changed from 7.0 to 6.2 during debugging.
![image](https://user-images.githubusercontent.com/45614674/85944359-b608f880-b968-11ea-8e7a-8cb3b1087441.png)

**Comment by EricJizbaMSFT** [comment] 2020-07-06 21:19
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1866. PowerShell 7 isn't supported yet.

**Closed by EricJizbaMSFT** 2020-07-06 21:19 UTC
Labels: AT-CTI
