### ISSUE TITLE
Getting 'sourceArray.map is not a function' after publishing

### ISSUE THREAD

**Issue by davidebbo** [Microsoft/vscode-azurefunctions#628] opened 2018-09-20 23:56 UTC
Publishing generally worked, but this popped up:

![image](https://user-images.githubusercontent.com/556238/45852741-2abff500-bcf6-11e8-96c0-59e69999d15b.png)

**Comment by EricJizbaMSFT** [comment] 2018-09-21 00:00
Yes that is a known issue. I've never been able to list functions for a linux consumption app and need someone on the functions team to help figure out why. Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/625

**Closed by EricJizbaMSFT** 2018-09-21 00:00 UTC
