### ISSUE TITLE
There's an error ''Failed to run 'mvn' command'' when creating a JAVA function

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/vscode-azurefunctions#263] opened 2018-03-08 09:45 UTC
## Steps to reproduce
1.install .NET Core 2.0, Azure Function Core Tools, VS Code Debugger for Java, JDK 1.8+ and Maven 3.0+
2.Set Environment Variable
  a) Check environment variable value:==> echo %JAVA_HOME% C:\Program Files\Java\jdk-9.0.4
  b) Add JAVA_HOME to user variable with C:\Program Files\Java\jdk-9.0.4
  c) Add the bin directory of apache-maven-3.5.2 to path environment variable(C:\Program   Files\Java\apache-maven-3.5.2\bin)
3.Restart testing machine.
4.Create New Java Project.
  a) Click 'Create New project' and new one folder> Select Java
  b) Click 'Yes' in the popped prompt to initialize the project
5.Click 'Create function app'>select the folder that created in Step1. Press Enter with all default settings.
6. Verify whether the function creates successfully.

## Expected  behavior
The function creates successfully.

## Actual behavior
There's an error 'Failed to run "mvn" command'.

![error](https://user-images.githubusercontent.com/12556995/37143998-b0f99392-22b4-11e8-8004-c5708019d203.PNG)

More Info:
This issue also reproduces on Mac and Linux.

**Comment by jdneo** [comment] 2018-03-20 08:10
This is caused by the maven plugin not support jdk 9.0 now. Could you please check if the problem still occur if the jdk is set to ~1.8?

**Comment by EricJizbaMSFT** [comment] 2018-03-21 16:52
@jdneo if that's the case, please update the prerequisites section in the README with the supported jdk versions

https://github.com/Microsoft/vscode-azurefunctions#java

**Comment by jdneo** [comment] 2018-03-22 02:55
PR: https://github.com/Microsoft/vscode-azurefunctions/pull/290

**Comment by v-flyuan** [comment] 2018-03-22 09:08
Hello,

I have tried using JSDK1.8 today. We can create function successfully. Then F5 successfully for the first time. But there're 2 new issues. Please get details from below.

**Issue1:**
After F5 successfully for the first time, then F5 again.
Expect: F5 successfully;
Actual: No response.

**Issue2:**
After F5 successfully for the first time, deploy. 
Expect: Deploy successfully;
Actual: Failed to deploy. You can see the screenshot below.
![deploy](https://user-images.githubusercontent.com/12556995/37760994-5424806a-2df3-11e8-8199-429e918c9764.png)

**Comment by jdneo** [comment] 2018-03-22 09:28
From the output, the failure happened when we are doing the clean lifecycle:
- The function plugin will do nothing related with the clean lifecycle, so this is not a issue related with the function plugin.
- The output says it is caused by some files cannot be deleted. In most cases, this is because the files are still be occupied by some process and not been released.

In the extension, when user hit `F5`, we're triggering the function cli command to start the function host. So please check:
- Before doing a new '`F5`', Is the previous function host stopped? (You can stop it by entering `ctrl` + `C` in the terminal panel)
- If the host is stopped but the target folder still cannot be deleted (that is what clean lifecycle doing), I think that mightbe a problem related with the function-cli

**Comment by EricJizbaMSFT** [comment] 2018-03-26 17:07
Closing this as the original issue has been fixed by an update to the README

@v-flyuan please create separate issues for what you just reported and we can discuss potential improvements in each issue individually.

**Closed by EricJizbaMSFT** 2018-03-26 17:07 UTC
