### ISSUE TITLE
[Suggestion]Add 'App Service Plan' item when creating 'Function App' from VS Code 

### ISSUE THREAD

**Issue by v-ruizh** [Microsoft/vscode-azurefunctions#1152] opened 2019-04-03 08:44 UTC
OS: Windows
Node.js: V10.15.0
Build Version: [20190402.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4643)
Azure Functions Core Tools: V2.4.498

Repro Steps:

1. Enable slots from user setting.
2. Create a 'Function App' from VS Code.
3. Create a slot to this Function App.
4. Create the second slot to this Function.

Actual:
An error occurs when creating the second slot.
![image](https://user-images.githubusercontent.com/45614674/55464826-83b9ff80-562e-11e9-9956-73383de1286f.png)

More Info:
This issue don't reproduce in the Function App which created from portal and set the App Service Plan. It will avoid this issue if add the 'App Service Plan' item when creating 'Function App' in VS Code.

**Comment by EricJizbaMSFT** [comment] 2019-04-03 15:30
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/854

**Closed by EricJizbaMSFT** 2019-04-03 15:30 UTC
Labels: AT-CTI
