### ISSUE TITLE
Allow zip package deployments with WEBSITE_RUN_FROM_PACKAGE=1

### ISSUE THREAD

**Issue by miguelisidoro** [microsoft/vscode-azurefunctions#2184] opened 2020-06-26 12:10 UTC
Hello,

I saw that there is a request at https://github.com/microsoft/vscode-azurefunctions/issues/783 to allow functions to be deployed as packages (Zip) according to best practices at https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#integration-with-zip-deployment

When will this be available?
The main goal here is to allow:

1. Set WEBSITE_RUN_FROM_PACKAGE to 1 and have this configuration be deployed in Azure (either in function app or deployment slots)
2. Have the deployment be made as zip package as explained at https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#integration-with-zip-deployment and https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push.
3. Update an existing function app (and deployment slots) - delete old files if not published as zip and republish as zip package

Thanks,
Miguel

**Comment by miguelisidoro** [comment] 2020-06-26 13:05
I was able to deploy it sucessfully by adding the setting in Azure Portal. I was adding it on the local settings. If possible, make an update to the extension so that deployment is made even if the setting is only on local settings and ensure that files in wwwroot are removed and the zip file is /home/data/SitePackages.

**Comment by EricJizbaMSFT** [comment] 2020-06-29 23:38
As you figured out, it's already possible to use `WEBSITE_RUN_FROM_PACKAGE`. In fact you don't have to go to the portal to change settings - you can do that directly in VS Code:
<img width="439" alt="Screen Shot 2020-06-29 at 4 24 18 PM" src="https://user-images.githubusercontent.com/11282622/86066273-946e4680-ba26-11ea-8e6d-4c1a63f4672a.png">

We also prompt to upload settings after you deploy, if desired:
<img width="474" alt="Screen Shot 2020-06-29 at 4 24 28 PM" src="https://user-images.githubusercontent.com/11282622/86066294-a18b3580-ba26-11ea-9419-b48a27e7e72c.png">

Unfortunately, it's not possible to make the local settings directly affect how it's run in Azure. I'm going to close this as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1465

**Closed by EricJizbaMSFT** 2020-06-29 23:38 UTC
