### ISSUE TITLE
Cannot read properties of undefined (reading 'isLinux')

### ISSUE THREAD

**Issue by mumurug-MSFT** [microsoft/vscode-azurefunctions#3369] opened 2022-10-10 14:00 UTC
**Details:**
VS code version: 1.72.0
Azure Functions extension version: v.1.8.1
Python extension version: v.2022.16.0
OS: Windows

**Repro Steps:**
Following https://learn.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=python#republish-project-files to deploy Azure Functions app to Azure caused the below error:

![image](https://user-images.githubusercontent.com/95652148/194883340-72cbfe82-ebe6-4b16-a7e0-48777aa9ab44.png)

Unable to deploy the app via VS code.

**Comment by karlwirenrocket** [comment] 2022-10-12 14:58
Having the same issue on Version: 1.71.0

**Comment by AlexFilipovici** [comment] 2022-10-13 08:53
Having the same issue - Cannot read properties of undefined (reading 'createClient')

Following https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-typescript#deploy-the-project-to-azure

VS code version: 1.72.1
Azure Functions extension version: v.1.8.1

**Comment by nturinski** [comment] 2022-10-13 20:50
Hi all, I've found a workaround to this issue. The tutorial will have you press the "Deploy" cloud icon on the local workspace, which is where the issue is.

The two methods you can use are:
- Open Resources > Function App > <your_function_app>
- Right-click the function app
- Click "Deploy to Function App..."
![image](https://user-images.githubusercontent.com/5290572/195707520-6b83fcef-ffe8-480c-9c4e-cf78c7cdf6b0.png)

The other method is:
- Press F1 to open the Command Palette
- Type `>Azure Functions: Deploy to Function App...`
- Select `Azure Functions: Deploy to Function App...`
- Follow the prompts to select your Function App
![image](https://user-images.githubusercontent.com/5290572/195707789-a7749651-e40a-4430-8a55-5d525d03cf3d.png)

Sorry about the issue! Hopefully these unblock you as we work on resolving this.

**Comment by AlexFilipovici** [comment] 2022-10-14 12:29
Thanks, @nturinski!

**Closed as completed** 2022-10-14 18:17 UTC
Labels: bug, investigate

**Comment by nturinski** [comment] 2022-10-18 23:08
Hi all, just wanted to let you know v1.8.2 has been released and should resolve this issue.
