### ISSUE TITLE
After deploy a function, Got error message

### ISSUE THREAD

**Issue by aaron1688** [Microsoft/vscode-azurefunctions#662] opened 2018-09-25 19:45 UTC
Repro steps:
Just follow the steps in the following link:
https://code.visualstudio.com/tutorials/functions-extension/deploy-app
The error happened in the last step to deploy the function.

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-09-25 20:08
Thanks for filing - there may have been an outage in Azure Functions. In any case, closing as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/645 for further investigation

**Closed by EricJizbaMSFT** 2018-09-25 20:08 UTC
