### ISSUE TITLE
Handling binary wheel dependencies without wheel 

### ISSUE THREAD

**Issue by suntracks** [Microsoft/vscode-azurefunctions#939] opened 2019-01-29 09:03 UTC
Unable to build azure functions with SQL Alchemy .
Is there a better way to build this and deploy to functions.
Docker/containers are such an unease to develop/deploy and debug.

Repro steps:
Using VS code to create function apps.
Well functioning python script with dependencies in venv env

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: 
There was an error restoring dependencies.ERROR: cannot install SQLAlchemy-1.2.16 dependency: binary dependencies without wheels are not supported. 

Version: 0.13.1
OS: darwin

Azure functions version:
2.4.290

pip freeze details:
asn1crypto==0.24.0
astroid==2.1.0
azure-common==1.1.17
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
azure-nspkg==3.0.2
azure-storage==0.36.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.4.2
grpcio==1.14.2
grpcio-tools==1.14.2
idna==2.8
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
npTDMS==0.13.0
numpy==1.16.0
pandas==0.23.4
protobuf==3.6.1
ptvsd==4.2.0
pycparser==2.19
pylint==2.2.2
PyMySQL==0.9.3
python-dateutil==2.7.5
pytz==2018.9
requests==2.21.0
six==1.12.0
SQLAlchemy==1.2.16
typed-ast==1.2.0
urllib3==1.24.1
wrapt==1.11.1

**Comment by EricJizbaMSFT** [comment] 2019-02-07 19:55
Are you aware of the `--build-native-deps` flag?

- If no, try adding that in your `.vscode/tasks.json` file after `func pack`. In this case, I would close as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/826
- If yes, and you just don't want to use Docker, I recommend filing an issue here: https://github.com/Azure/azure-functions-core-tools That scenario is handled by the func cli team, not the VS Code extension. In this case, I would close as external

**Closed by EricJizbaMSFT** 2019-02-07 19:55 UTC
