### ISSUE TITLE
FUNCTIONS_WORKER_RUNTIME not being set for queue and python

### ISSUE THREAD

**Issue by jeffhollan** [Microsoft/vscode-azurefunctions#1238] opened 2019-04-29 21:49 UTC
Issue Type: <b>Bug</b>

1. Create new function app project
1. Select Python
1. Select Azure Queue Storage
1. Click to create new local.settings.json
1. Select storage account in azure
1. Finish create experience

The local.settings.json doesn't include `FUNCTIONS_WORKER_RUNTIME` which is breaking the local debug experience.  Not sure why.  Http function seems to work fine when it sets that message.  Didn't repro on all machines (Asavari tried it out)

func version 2.6.1048

Extension version: 0.16.0
VS Code version: Code - Insiders 1.34.0-insider (0200bdd71e409954ae12149fe493f38065306555, 2019-04-29T05:15:17.465Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|-psn_0_1134869|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EricJizbaMSFT** [comment] 2019-04-29 21:52
Duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/1137. Already fixed on master - you can try latest build with these instructions: https://aka.ms/azCodeInsiders

**Closed by EricJizbaMSFT** 2019-04-29 21:52 UTC
