### ISSUE TITLE
Display "Cannot find module '@azure/functions' " for a TS project in 'Problems' window

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1325] opened 2019-06-04 06:56 UTC
**OS:** Win10\Mac
**Build Version**: [20190603.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6473)

**Repro Step:**
Create a TS project --> Check the 'Problems' window.

**Expect:**
No error displays.

**Actual:**
Display "Cannot find module '@azure/functions' ".
![image](https://user-images.githubusercontent.com/34729092/58857918-eab06f00-86d8-11e9-85cc-d3f5c2ea3f2c.png)

**More Info:**
1. Func version: V2.7.1158
2. Node version: V10.15.3
3. Npm version: V6.4.1

**Comment by EricJizbaMSFT** [comment] 2019-06-04 15:56
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1026

**Closed by EricJizbaMSFT** 2019-06-04 15:56 UTC
Labels: AT-CTI
