### ISSUE TITLE
Unable to deploy Azure function from VS code

### ISSUE THREAD

**Issue by sandeep0473** [Microsoft/vscode-azurefunctions#944] opened 2019-01-31 08:03 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/sandeep/Documents/azure/azure.zip

Version: 0.13.1
OS: linux

**Comment by EricJizbaMSFT** [comment] 2019-02-07 19:49
@sandeep0473 I believe this may be a duplicate of another bug we've been seeing. You can try the workarounds listed here: https://github.com/Microsoft/vscode-azurefunctions/issues/892#issuecomment-459054366

We've fixed on master already and plan to release soon, but you're welcome to try earlier:
How to install: https://aka.ms/azCodeInsiders
Build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2905

NOTE: This relies on VS Code v1.31.0 just released yesterday

If you're still having problems, please copy the full output of the "func pack" task here

**Closed** 2019-02-28 20:24 UTC
Labels: needs more info
