### ISSUE TITLE
Not allowed to open

### ISSUE THREAD

**Issue by eternalguardian** [Microsoft/vscode-azurefunctions#727] opened 2018-10-16 12:21 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: EPERM
Error Message: EPERM: operation not permitted, open 'c:\Program Files (x86)\Pidgin\pixmaps\pidgin\host.json'

Version: 0.11.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-10-17 17:39
Closing as by design. Feel free to re-open if it's not a permission issue

**Closed by EricJizbaMSFT** 2018-10-17 17:39 UTC
