### ISSUE TITLE
Unable to do build-native-deps through VS Code

### ISSUE THREAD

**Issue by priyaananthasankar** [Microsoft/vscode-azurefunctions#682] opened 2018-10-02 17:37 UTC
I have dependencies that do not have prebuilt wheel files on PyPI. Through func core tools I am able to do -build-native-deps that builds these dependencies using Docker and publishes them. 

I am unable to do this through VS Code.

**Comment by EricJizbaMSFT** [comment] 2018-10-02 17:44
We're running the task defined in `.vscode/tasks.json` before deploying. You can customize that however you would like. In this case, it sounds like you just need to replace `func pack` with `func pack --build-native-deps`.

This doesn't seem like something we want by default (since it depends on docker, etc.) - but let me know if you disagree

**Comment by priyaananthasankar** [comment] 2018-10-02 17:52
Thanks @EricJizbaMSFT  Azure Python SDK's are the ones that are forcing me to do a build-native-deps. Would be nice to have it - but also good enough if this can be mentioned somewhere - I guess in this case the functions documentation would be the right place.

**Comment by EricJizbaMSFT** [comment] 2018-10-03 17:47
Where did you originally find out about the `build-native-deps` flag? I'm just trying to figure out where we would document this

**Comment by priyaananthasankar** [comment] 2018-10-03 17:50
@EricJizbaMSFT : I am guessing here, but also adding @asavaritayal for inputs
https://github.com/Azure/azure-functions-python-worker/wiki/Develop-using-VS-Code

**Comment by priyaananthasankar** [comment] 2018-10-03 22:06
The exact location where I found --build-native-deps is here: https://github.com/Azure/azure-functions-python-worker/wiki/Developer-Guide

**Comment by EricJizbaMSFT** [comment] 2019-01-29 19:01
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/826

**Closed by EricJizbaMSFT** 2019-01-29 19:01 UTC
Labels: P3, documentation
