### ISSUE TITLE
Unable to deploy through VS Code - node.js

### ISSUE THREAD

**Issue by pink-cupcakes** [Microsoft/vscode-azurefunctions#859] opened 2018-12-12 19:34 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy. Pre-deploy task "installExtensions" failed with exit code "2".

Version: 0.13.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-12-12 21:42
@pink-cupcakes closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/852. Please feel free to answer my questions in this comment https://github.com/Microsoft/vscode-azurefunctions/issues/852#issuecomment-446697967 so we can get more info on this situation

**Closed by EricJizbaMSFT** 2018-12-12 21:42 UTC
