### ISSUE TITLE
Debugging Azure function Failed to attach (System.Private.CoreLib: The given key 'LogType' was not present in the dictionary)

### ISSUE THREAD

**Issue by zorzigio** [microsoft/vscode-azurefunctions#1725] opened 2019-11-29 22:41 UTC
I am implementing a simple Azure function in VS Code using BlobTrigger and using Python 3.7.3.

The function is just the default created by VS Code.

I am not able to run it since VS Code gives

```
An unhandled exception has occurred. Host is shutting down.
System.Private.CoreLib: The given key 'LogType' was not present in the dictionary.
```

VS Code also opens a popup `Failed to attach (connect ECONNREFUSED 127.0.0.1:9091)`

Here is the output from terminal

```
> Executing task: .venv\Scripts\python -m pip install -r requirements.txt <

Requirement already satisfied: azure-functions in d:\epiq\code\functions\blob_trigger_add\.venv\lib\site-packages (from -r requirements.txt (line 1)) (1.0.5)

Terminal will be reused by tasks, press any key to close it.

> Executing task: .venv\Scripts\activate ; func host start <

Found Python version 3.7.3 (python).

                  %%%%%%     
                 %%%%%%      
            @   %%%%%%    @  
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@ 
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@  
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0
[29/11/2019 22:31:27] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '8c02ca7a-5153-434e-bbb8-21e89b582f6c'
[29/11/2019 22:31:27] Reading host configuration file 'D:\Epiq\Code\functions\blob_trigger_add\host.json'
[29/11/2019 22:31:27] Host configuration file read:
[29/11/2019 22:31:27] {
[29/11/2019 22:31:27]   "version": "2.0",
[29/11/2019 22:31:27]   "extensionBundle": {
[29/11/2019 22:31:27]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[29/11/2019 22:31:27]     "version": "[1.*, 2.0.0)"
[29/11/2019 22:31:27]   }
[29/11/2019 22:31:27] }
[29/11/2019 22:31:27] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\zorzi\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[29/11/2019 22:31:27] Found a matching extension bundle at C:\Users\zorzi\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[29/11/2019 22:31:27] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[29/11/2019 22:31:27] Skipping bundle download since it already exists at path C:\Users\zorzi\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[29/11/2019 22:31:27] Loading Extention bundle from C:\Users\zorzi\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[29/11/2019 22:31:27] Reading functions metadata
[29/11/2019 22:31:27] 1 functions found
[29/11/2019 22:31:27] Loading startup extension 'AzureStorage'
[29/11/2019 22:31:27] Loaded extension 'AzureStorage' (3.0.10.0)
[29/11/2019 22:31:28] Initializing Warmup Extension.
[29/11/2019 22:31:28] Initializing Host. OperationId: '8c02ca7a-5153-434e-bbb8-21e89b582f6c'.
[29/11/2019 22:31:28] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=8c02ca7a-5153-434e-bbb8-21e89b582f6c
[29/11/2019 22:31:28] LoggerFilterOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "MinLevel": "None",
[29/11/2019 22:31:28]   "Rules": [
[29/11/2019 22:31:28]     {
[29/11/2019 22:31:28]       "ProviderName": null,
[29/11/2019 22:31:28]       "CategoryName": null,
[29/11/2019 22:31:28]       "LogLevel": null,
[29/11/2019 22:31:28]       "Filter": "<AddFilter>b__0"
[29/11/2019 22:31:28]     },
[29/11/2019 22:31:28]     {
[29/11/2019 22:31:28]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[29/11/2019 22:31:28]       "CategoryName": null,
[29/11/2019 22:31:28]       "LogLevel": "None",
[29/11/2019 22:31:28]       "Filter": null
[29/11/2019 22:31:28]     },
[29/11/2019 22:31:28]     {
[29/11/2019 22:31:28]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[29/11/2019 22:31:28]       "CategoryName": null,
[29/11/2019 22:31:28]       "LogLevel": null,
[29/11/2019 22:31:28]       "Filter": "<AddFilter>b__0"
[29/11/2019 22:31:28]     }
[29/11/2019 22:31:28]   ]
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] FunctionResultAggregatorOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "BatchSize": 1000,
[29/11/2019 22:31:28]   "FlushTimeout": "00:00:30",
[29/11/2019 22:31:28]   "IsEnabled": true
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] SingletonOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "LockPeriod": "00:00:15",
[29/11/2019 22:31:28]   "ListenerLockPeriod": "00:00:15",
[29/11/2019 22:31:28]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[29/11/2019 22:31:28]   "LockAcquisitionPollingInterval": "00:00:05",
[29/11/2019 22:31:28]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] QueuesOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "BatchSize": 16,
[29/11/2019 22:31:28]   "NewBatchThreshold": 8,
[29/11/2019 22:31:28]   "MaxPollingInterval": "00:00:02",
[29/11/2019 22:31:28]   "MaxDequeueCount": 5,
[29/11/2019 22:31:28]   "VisibilityTimeout": "00:00:00"
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] BlobsOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "CentralizedPoisonQueue": false
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] HttpOptions
[29/11/2019 22:31:28] {
[29/11/2019 22:31:28]   "DynamicThrottlesEnabled": false,
[29/11/2019 22:31:28]   "MaxConcurrentRequests": -1,
[29/11/2019 22:31:28]   "MaxOutstandingRequests": -1,
[29/11/2019 22:31:28]   "RoutePrefix": "api"
[29/11/2019 22:31:28] }
[29/11/2019 22:31:28] Starting JobHost
[29/11/2019 22:31:28] Starting Host (HostId=gz-1173307470, InstanceId=852e14a5-2d40-4282-9eed-2ce865b65d40, Version=2.0.12888.0, ProcessId=6632, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[29/11/2019 22:31:28] Loading functions metadata
[29/11/2019 22:31:28] 1 functions loaded
[29/11/2019 22:31:28] Loading proxies metadata
[29/11/2019 22:31:28] Initializing Azure Function proxies
[29/11/2019 22:31:28] 0 proxies loaded
[29/11/2019 22:31:28] Starting worker process:python  c:/Users/zorzi/.vscode/extensions/ms-python.python-2019.11.50794/pythonFiles/ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 --wait "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\3.7/WINDOWS/X64/worker.py" --host 127.0.0.1 --port 54169 --workerId 3f86bcde-7b97-4963-bcc8-314eb272eac0 --requestId 1b7983b6-0853-406d-8d18-739105be4185 --grpcMaxMessageLength 134217728
[29/11/2019 22:31:28] python process with Id=14380 started
[29/11/2019 22:31:28] Generating 1 job function(s)
[29/11/2019 22:31:28] Found the following functions:
[29/11/2019 22:31:28] Host.Functions.BlobTrigger
[29/11/2019 22:31:28]
[29/11/2019 22:31:29] Initializing function HTTP routes
[29/11/2019 22:31:29] No HTTP routes mapped
[29/11/2019 22:31:29]
[29/11/2019 22:31:29] Host initialized (1471ms)
[29/11/2019 22:31:29] Host started (1574ms)
[29/11/2019 22:31:29] Job host started
Hosting environment: Production
Content root path: D:\Epiq\Code\functions\blob_trigger_add
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txt3.txt', Id=1edf4271-8d73-446e-b8c1-a4bc26abcc33)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txt5.txt', Id=42b63fca-d5bc-4501-9a54-1c33d8f8aa5e)
[29/11/2019 22:31:31] An unhandled exception has occurred. Host is shutting down.
[29/11/2019 22:31:31] System.Private.CoreLib: The given key 'LogType' was not present in the dictionary.
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/lv1/lv2', Id=aaac3e94-70ef-4d79-a29e-4f5c98519b66)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/corrupted', Id=0ee6405d-0810-490f-94f9-f44e9e33d74d)
[29/11/2019 22:31:31] Stopping host...
[29/11/2019 22:31:31] Stopping JobHost
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/lv1', Id=fe567f48-a365-4ee2-8867-62e2cb6fadab)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/corrupted/Corrupted.pdf', Id=b354108f-3d22-4330-875e-ce833898f839)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txt2.txt', Id=f8203703-fecf-4939-8e05-c252639cde00)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txt.txt', Id=7cf5eac0-124e-46c9-99f7-cc44fba2af42)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txta.txt', Id=ce10af86-bc8f-4998-a6f8-35a55550ce39)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/new_blob', Id=1fb4a086-2e67-40ab-942c-5470bc3d8efa)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/txt1.txt', Id=afef3fb8-6861-4aa5-b115-1718b32db6ad)
[29/11/2019 22:31:31] Executing 'Functions.BlobTrigger' (Reason='New blob detected: container/lv1/lv2/ocrscan.pdf', Id=ec578ab3-4159-4ad0-becd-f9011b4d7308)
[29/11/2019 22:31:36] Host did not shutdown within its allotted time.
Application is shutting down...

Terminal will be reused by tasks, press any key to close it.

```

**Comment by EricJizbaMSFT** [comment] 2019-12-04 23:39
I tried to reproduce and ran into this issue: https://github.com/Microsoft/vscode-python/issues/8685

I don't see the exact same error in your logs, but perhaps it's related? You can wait for them to release the fix or try downgrading to an older version of the Python extension with the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)
![Screen Shot 2019-12-04 at 3 36 25 PM](https://user-images.githubusercontent.com/11282622/70190874-01e21080-16ac-11ea-97f0-2229d312d5d9.png)

This is the version I'm on where it works:
![Screen Shot 2019-12-04 at 3 36 38 PM](https://user-images.githubusercontent.com/11282622/70190938-28a04700-16ac-11ea-9ce4-93deba06e676.png)

**Comment by zorzigio** [comment] 2019-12-05 12:51
Thanks @EricJizbaMSFT for the help.
Unfortunately downgrading the Python extension to 2019.10.44104 did not help. VS Code is still giving the same error as before

**Comment by EricJizbaMSFT** [comment] 2019-12-05 17:39
Have you modified the blob trigger? If so, can you paste the contents here?

Maybe try creating a fresh new project and using an empty storage account to see if that still reproduces

**Comment by zorzigio** [comment] 2019-12-06 21:41
Thanks @EricJizbaMSFT for the suggestions.

I tried creating a new project using a newly created storage account (StorageV2 with Hierarchical Namespace enabled). Started debugging and everything was working for a couple of minutes. I uploaded some blobs and the function would be triggered.  After that, the same error as before.

```
An unhandled exception has occurred. Host is shutting down.
System.Private.CoreLib: The given key 'LogType' was not present in the dictionary.
```

I tried repeating the same process again but leaving disabled the Hierarchical namespace option and now the function has been running for about 20 min with no errors thrown (I also uploaded some blobs and the function got triggered correctly).

So I guess this has somehow something to do with the error?

The function that I am using is the default one that gets created by the VS Code extension for Azure functions when using blob triggers (no modifications from the original).

**Comment by EricJizbaMSFT** [comment] 2019-12-09 17:59
And this only causes problems when debugging, correct? Not when you deploy it to Azure?

I'm not that familiar with the func cli, which is actually running the Azure Functions host on your local machine. It's possible they have a bug with Hierarchical Namespace. You would probably have better luck filing an issue here: https://github.com/Azure/azure-functions-core-tools

**Comment by timardis12** [comment] 2019-12-17 16:32
@zorzigio we had just started seeing this error message over the past couple weeks, and it was crashing our Functions as well. We were also using Storage v2 w/ HNS enabled. Switching back to Storage v1 fixed it for us (I imagine v2 w/o HNS should work as well, but we didn't try that).

Thanks for posting here, otherwise we probably wouldn't have figured out what was causing it.

**Comment by grendo** [comment] 2019-12-24 00:03
seeing the same thing in visual studio using Storage v2 w/ HNS enabled on any blob trigger, both local and on azure.  Tried various versions 2 and 3 of the function framework.  No solution yet.

**Comment by venkatx5** [comment] 2020-01-09 09:52
Any update on this issue?

**Comment by brettsam** [comment] 2020-01-21 23:13
Is everyone seeing this using Storage V2? I have a fix -- https://github.com/microsoft/vscode-azurefunctions/issues/1725, but that just fixes this specific error message.

I'm not sure why we just started seeing it after this code has been here for 5+ years, but if it has something to do with Storage v2, that would explain it.

**Comment by brettsam** [comment] 2020-01-22 13:45
The blob trigger issue is fixed with https://github.com/Azure/azure-webjobs-sdk/pull/2414. It turns out there are [subtleties when using the Storage APIs against Data Lake storage](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues#issues-and-limitations-with-using-blob-apis) and we were bumping into one of them.

I don't seem to have rights to close or transfer issues in this repo. @EricJizbaMSFT could you close this for us?

**Closed** 2020-01-22 17:16 UTC
Labels: upstream
