### ISSUE TITLE
Deploy to Function App: Reported URL is wrong

### ISSUE THREAD

**Issue by alexjamesbrown** [Microsoft/vscode-azurefunctions#484] opened 2018-07-26 08:34 UTC
**Azure Function VS Code Extension version: 0.10.0**

Using the Visual Studio Code option:
> Azure Functions: Deploy to Function App

After my function is successfully deployed, I see the following output in the console:
...
> 09:18:07 myfunction: Deployment successful.
> Deployment to "myfunction" completed.

> HTTP Trigger Urls:
>  HttpTriggerFunction: https://myfunction.azurewebsites.net/api/HttpTriggerFunction

In my particular case, I have a custom route set in `function.json`

	{
	  "bindings": [
	    {
	      "type": "httpTrigger",
	      "methods": [
	        "get"
	      ],
	      "authLevel": "anonymous",
	      "name": "req",
	      "route": "my-route"
	    }
	  ],
	  "scriptFile": "../MyFunction.dll",
	  "entryPoint": "MyFunction.HttpTriggerFunction.Run"
	}

I also have the `routePrefix` set in `host.json`

	{
	    "http": {
	        "routePrefix": ""
	    }
	}

This means, the reported URL of `https://myfunction.azurewebsites.net/api/HttpTriggerFunction` is wrong
(it returns a 404)

It should be 

https://myfunction.azurewebsites.net/my-route

(which works)

**Comment by ubikusss** [comment] 2018-07-27 14:53
The extension does a POST to a Kudu endpoint:
Kudu URL:
"https://funcappdini.scm.azurewebsites.net/api/functions/URLTesting/listsecrets"

It does not return the correct URL if you use a custom route. 
We're (with @snobu) looking into this in Kudu to see why.

**Comment by ubikusss** [comment] 2018-08-01 08:40
There is a PR for the Kudu project.

**Comment by ubikusss** [comment] 2018-08-03 10:16
For the record, the PR is this:
https://github.com/projectkudu/kudu/pull/2821

**Comment by EricJizbaMSFT** [comment] 2019-02-27 22:24
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/205

**Closed by EricJizbaMSFT** 2019-02-27 22:24 UTC
Labels: bug, external
