### ISSUE TITLE
Can't deploy to app on premium plan. 

### ISSUE THREAD

**Issue by anindya5** [microsoft/vscode-azurefunctions#1609] opened 2019-10-22 20:56 UTC
Every-time trying to deploy an app on premium plan(preview) getting this error. Can deploy to another app on consumption plan, the same code. I am using VSCode for deployment

Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 503
Error Message: Service Unavailable

Version: 0.19.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:393194
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:637004
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by Guts** [comment] 2019-10-23 17:00
Almost the same here, but I'm trying to deploy a Python Function to Consumption Plan in West Europe.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.19.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: fr

<details>
<summary>Call Stack</summary>

```
a.pipeline extension.bundle.js:218:2797976
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:668851
extension.bundle.js:164:24705extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:637004
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-10-30 21:55
@anindya5 were you deploying a Linux or Windows plan? Also what language is your project?

@Guts you said you got a workaround for this issue? What exactly was the workaround? It's possible your old app got a weird configuration at some point

**Comment by Guts** [comment] 2019-10-31 08:51
> @Guts you said you got a workaround for this issue? What exactly was the workaround? It's possible your old app got a weird configuration at some point

I followed the other issues as I mentioned:

> tried advanced deployment with OS as linux, language python. it worked.

_Originally posted by @pranman11 in https://github.com/microsoft/vscode-azurefunctions/issues/1567#issuecomment-540192761_

**Comment by EricJizbaMSFT** [comment] 2019-11-05 17:59
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1583

**Closed by EricJizbaMSFT** 2019-11-05 17:59 UTC
Labels: needs more info
