### ISSUE TITLE
[Unstable] An error occurs when deploying a project to a Function App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3219] opened 2022-06-10 08:47 UTC
**OS:** Win10
**Build Version:** 20220609.3

**Repro Steps:**
1. Create a Python project.
2. Create a Python Function App.
3. Right click the Function App and select "Deploy to Function App...".
4. Check whether the confirmation dialog pops up or not.

**Expect:**
The confirmation dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/173027500-34785870-1aa7-48a9-861e-9491a6ccb75d.png)

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/173027525-ab602e7d-b08a-4677-9560-30967f0dbe95.png)

**More Info:**
1. Deploy again, this issue does not reproduce.
2. This is an unstable issue, I encounter this issue 2 times when testing.

**Comment by nturinski** [comment] 2022-08-02 23:49
I've tried a few times, but I can't get this to reproduce.

I looked for any references to `refresh` in the deployment code, but I didn't see anywhere this error could happen. I think that something else must be triggering it, maybe something to do with the resolving done by Resources after the create completes?

**Comment by v-ruizh** [comment] 2022-08-08 08:07
I can reproduce this issue when testing function extension every time. Before I deploy the Python project, I have done for deploying some other projects, such as C#/JavaScript/TypeScript projects. This issue is unstable. It probably can be reproduced the first-time deployment for Python. It does not reproduce if deploy again. I'm not sure if this caused by other projects deployment.

**Comment by nturinski** [comment] 2022-08-08 16:38
Okay, thanks for following up on that. Does it happen with the first deploy on a Python project? 

I think it's unlikely that a user would be deploying multiple project languages in one VS Code session so if it is okay on the first deploy, then I think that this is an edge case that most customers won't encounter.

**Comment by v-ruizh** [comment] 2022-08-09 09:47
I tried this scenario for the first deploy on a Python project, deploy successfully.

**Comment by nturinski** [comment] 2022-08-11 21:53
I'm going to go ahead and close this one as a `wont-fix`. The reason being that it seems difficult to reproduce and only reproduces when a user deploys multiple project languages in one session.

**Closed by nturinski** 2022-08-11 21:53 UTC
Labels: bug, AT-CTI
