### ISSUE TITLE
Unable to deploy azure function from VS code

### ISSUE THREAD

**Issue by AmudhaPalani** [Microsoft/vscode-azurefunctions#716] opened 2018-10-12 20:02 UTC
Repro steps:
1) Select Deploy Azure function from command palette.

Action: azureFunctions.deploy
Error type: Error
Error Message: Could not zip a non-exist file path.

Version: 0.11.0
OS: darwin

**Comment by EricJizbaMSFT** [comment] 2018-10-17 17:54
Could you give a little more info about this scenario? For example what language are you using?

**Comment by zunhu** [comment] 2018-10-23 02:05
I got similar issue. using .net461, but when I did 'Azure deploy' got some warning during build:

C:\Users\v-zuhu\.nuget\packages\microsoft.net.sdk.functions\1.0.23\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Publish.targets(145,5): warning : Method IoTWorkbench.IoTHubTrigger1.Run is missing a trigger attribute. Both a trigger attribute and FunctionName attribute are required for an Azure function definition. [C:\Users\v-zuhu\Documents\IoTWorkbenchProjects\examples\10221251\Functions\Functions.csproj]
C:\Users\v-zuhu\.nuget\packages\microsoft.net.sdk.functions\1.0.23\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Publish.targets(145,5): warning :  [C:\Users\v-zuhu\Documents\IoTWorkbenchProjects\examples\10221251\Functions\Functions.csproj]

**Comment by EricJizbaMSFT** [comment] 2018-10-23 16:57
@zunhu that original error is expected if your build failed. You will have to fix your build errors for a deploy to work

**Comment by EricJizbaMSFT** [comment] 2018-11-08 18:19
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/772

**Closed by EricJizbaMSFT** 2018-11-08 18:19 UTC
Labels: P2, enhancement
