### ISSUE TITLE
Unable to deploy Azure Function from VSCode

### ISSUE THREAD

**Issue by anandbonde** [microsoft/vscode-azurefunctions#2183] opened 2020-06-25 22:22 UTC
Does this occur consistently?

YES

Repro steps:

1. Create a new Azure Function from VSCode
2. Test it locally (it works)
3. Try to deploy it to Azure

I can see the app on the portal. But not sure if it was deployed correctly or not.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.22.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:587813
fulfilled extension.bundle.js:1:586061
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-06-29 23:43
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1958. If you have any details to add, please add them to that issue (for example, what type of function app, python/javascript, linux/windows, etc.)

**Closed by EricJizbaMSFT** 2020-06-29 23:43 UTC
