### ISSUE TITLE
appsettings.json vs local.settings.json

### ISSUE THREAD

**Issue by brugos** [Microsoft/vscode-azurefunctions#327] opened 2018-04-17 19:00 UTC
I'm using azure functions with javascript and was using func+vscode for everything. I've added some env keys to add my conneciton strings and I can see them crypted locally on the appsettings.json file.

I didn't found a way in your docs on how to publish these keys so I've created manually on the integrated Azure Functions section on VSCode. However, when I try to download the keys I found the issue below. I can guess that is because there is no local.settings.json, but my doubt is what is the relation between appsettings.json and local.settings.json ??

Thanks.

Repro steps:
<Enter steps to reproduce issue>

Action: azureFunctions.appSettings.download
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\Users\jbrugos\Documents\codes\McLaren\eloquaFunction\local.settings.json'

Version: 0.8.1
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-04-17 20:28
"appsettings.json" is an old file name and is deprecated. See [here](https://github.com/Azure/azure-functions-core-tools/issues/122) for more info. Please use "local.settings.json" file going forward. I think they're pretty much the same format/usage, but see [here](https://docs.microsoft.com/azure/azure-functions/functions-run-local#local-settings-file) for more info on local.settings.json.

We have an [existing bug](https://github.com/Microsoft/vscode-azurefunctions/issues/324) where 'download' doesn't work if you don't have a local.settings.json file, but the easy workaround is to create the file before you download.

**Comment by EricJizbaMSFT** [comment] 2018-04-18 18:08
Let us know if you have any other questions. Closing this as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/324

**Closed by EricJizbaMSFT** 2018-04-18 18:08 UTC

**Comment by alexgman** [comment] 2018-08-14 22:25
If we promote a function app to QA/PROD, do we need to create another` local.settings.json` file like `prod.settings.json`?

How would we make the _switch_ within our code between these two files to account for different environments?

For example, developing locally:

`log.Info(GetEnvironmentVariable("AzureWebJobsStorage"));`

When we promote our code, how does it know which environment we are in, since there is no differentiation above?

**Comment by EricJizbaMSFT** [comment] 2018-08-16 16:11
@alexgman `local.settings.json` is only used when developing on your local machine (see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file) for more info). It is ignored in Azure and there is no equivalent `prod.settings.json`.

For the application settings in Azure, you can edit them in the portal as described here: 

We also provide ways for you to edit these directly in VS Code if you so desire:
![screen shot 2018-08-16 at 9 09 11 am](https://user-images.githubusercontent.com/11282622/44220735-5159a180-a134-11e8-9fe0-e93d797b59e9.png)
