### ISSUE TITLE
MS case TrackingID#2303150030002186

### ISSUE THREAD

**Issue by Amaresh-LNU** [microsoft/vscode-azurefunctions#3640] opened 2023-04-05 05:10 UTC
Hi Team,

we have critical cloud-based police reporting production application developed to run in Azure function with python code base in VS Code, we are facing issue while trying to debug the python code in visual studio code in local/dev system.

Regards,
Amaresh

**Comment by alexweininger** [comment] 2023-04-05 16:11
Please add detailed repro steps.

**Comment by Amaresh-LNU** [comment] 2023-04-06 11:52
It is troughing an error when we click on the debug option 'connect ECONNREFUSED 127.0.0.1:9091'

**Comment by alexweininger** [comment] 2023-04-06 22:05
Closing as a duplicate of #3332. Please follow that issue for further updates.

See this possible fix: https://github.com/microsoft/vscode-azurefunctions/issues/3332#issuecomment-1496587360

**Closed by alexweininger** 2023-04-06 22:05 UTC
Labels: info-needed
