### ISSUE TITLE
Debugger crashes on save of file (Javascript)

### ISSUE THREAD

**Issue by osbornm** [microsoft/vscode-azurefunctions#2070] opened 2020-05-02 20:52 UTC
### Problem
When the debugger is running and a file is saved the debugger crashes with the following error. This is a simple httptrigger func created using the this extension. This makes any reasonable dev workflow impossible.

<img width="1391" alt="Screen Shot 2020-05-02 at 3 46 56 PM" src="https://user-images.githubusercontent.com/674284/80891880-856c5180-8c8c-11ea-9318-6855f96e2757.png">

### Environment

**VS CODE**: Version: 1.45.0-insider
**CLI**: azure-functions-core-tools@3.0.2245
**Functions extension**: v0.22.0

**Comment by osbornm** [comment] 2020-05-02 20:58
I found this issue which seems similar but no actual resolution. https://github.com/Azure/azure-functions-host/issues/3415

**Comment by osbornm** [comment] 2020-05-04 13:13
seem related to: https://github.com/Azure/azure-functions-host/issues/3543 but this hasn't had a meaningful update in > 10 months.

**Comment by EricJizbaMSFT** [comment] 2020-05-04 19:55
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/781, which unfortunately is really just a tracking issue for the one you mentioned.

**Closed by EricJizbaMSFT** 2020-05-04 19:55 UTC
