### ISSUE TITLE
Error from learn.microsoft.com -  Enable automatic updates in a web application using Azure Functions and SignalR Service

### ISSUE THREAD

**Issue by vglu** [microsoft/vscode-azurefunctions#1859] opened 2020-02-03 14:45 UTC
Repro steps:

1. https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account
2. Error 404

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:502569extension.bundle.js:218:502569
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:634979
$.t._callback.t.callback.t.callback [as callback] extension.bundle.js:194:5590
$.emit events.js:200:13
$.EventEmitter.emit domain.js:471:20
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
$.EventEmitter.emit domain.js:471:20
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-02-03 17:30
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1859 and https://github.com/microsoft/vscode-azurefunctions/issues/1583

**Comment by EricJizbaMSFT** [comment] 2020-02-03 17:31
As a workaround, please try the "Advanced" option when creating a function app in azure, which should give you more options

**Closed by EricJizbaMSFT** 2020-02-03 17:30 UTC
