### ISSUE TITLE
No dialog about 'Select storage account' pops up when creating a C# project with "Timer Trigger" template

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurefunctions#3616] opened 2023-03-07 09:06 UTC
**OS:** Win10
**Build Version:** 20230304.7
**Regression:** Not a Regression

**Repro Steps:**

1. Create a C# project with "Timer Trigger" template.
2. Check whether there is a dialog pops up.

**Expect:**
The below dialog pops up.
![image](https://user-images.githubusercontent.com/107091828/223367208-c58264c4-3745-46df-9cfb-40815c715a1a.png)

**Actual:**
No dialog about 'Select storage account' pops up.

**More Info:**

1. This issue also reproduces for Java project.
2. This issue also reproduces on the previous released Azure Functions extension v1.10.0.

**Comment by MicroFish91** [comment] 2023-03-09 23:44
The `function.json` files don't exist until after a build for languages that need to be compiled.  Closing as by design

**Closed by MicroFish91** 2023-03-09 23:44 UTC
Labels: AT-CTI
