### ISSUE TITLE
Cannot deploy new Python function in VSCode

### ISSUE THREAD

**Issue by aatifsyed** [microsoft/vscode-azurefunctions#2571] opened 2020-12-07 00:29 UTC
Does this occur consistently? Yes
Repro steps:
1. Follow tutorial up to https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python#publish-the-project-to-azure

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://`app-name`.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 1.0.1
OS: linux
OS Release: 4.19.128-microsoft-standard+
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by aatifsyed** [comment] 2020-12-07 00:58
Could deploy from the CLI, following https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-python?tabs=azure-cli%2Cbash%2Cbrowser#deploy-the-function-project-to-azure

**Comment by ejizba** [comment] 2020-12-07 22:47
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2390

**Closed by ejizba** 2020-12-07 22:47 UTC
