### ISSUE TITLE
error while deploying function in azure

### ISSUE THREAD

**Issue by akarana** [Microsoft/vscode-azurefunctions#644] opened 2018-09-23 17:13 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-09-24 15:06
Thanks for filing - there may have been an outage in Azure Functions. In any case, closing as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/645 for further investigation

**Closed by EricJizbaMSFT** 2018-09-24 15:06 UTC
Labels: duplicate
