### ISSUE TITLE
Azure Policy Definitions (location based) stops deploying a new function

### ISSUE THREAD

**Issue by gfk76** [microsoft/vscode-azurefunctions#1244] opened 2019-04-30 20:05 UTC
Repro steps:1.2.Action: azureFunctions.deployError type: RequestDisallowedByPolicyError Message: Resource 'azuretutjs20' was disallowed by policy. Policy identifiers: '[{"policyAssignment":{"name":"Allowed locations","id":"/subscriptions/1ab102b6-e215-4951-97f4-f9240e755372/providers/Microsoft.Authorization/policyAssignments/c0e6f7c631ce4f0a8a883e61"},"policyDefinition":{"name":"Allowed locations","id":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c"}}]'.Version: 0.16.0OS: darwinVS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.l.pipeline (dist/extension.bundle.js:277:755010)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment] 2019-04-30 20:36
@gfk76 you can change the `azureFunctions.advancedCreation` setting to `true` and you will be manually prompted for things like location

We improved that here: https://github.com/Microsoft/vscode-azurefunctions/pull/1198, but it hasn't been released yet

**Comment by EricJizbaMSFT** [comment] 2019-07-19 21:00
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1317

**Closed by EricJizbaMSFT** 2019-07-19 21:00 UTC
