### ISSUE TITLE
How can I create a new Azure Function app in monorepo

### ISSUE THREAD

**Issue by dfberry** [microsoft/vscode-azurefunctions#3894] opened 2023-11-13 21:04 UTC
When I select the folder for the new app, it creates a new node_modules folder and a new package-lock.json even though the folder is within an [npm workspace monorepo](https://docs.npmjs.com/cli/v10/using-npm/workspaces). 

How should I correctly use the Azure Functions extension to create a new app within a monorepo? 

```text
// root file and folder view
./.git
./.devcontainer
./package.json --> workspace property is set to  "packages/*"
./package-lock.json
./packages/api --> new Azure Functions
 
@ggailey777 
@glaucia86

**Comment by nturinski** [comment] 2023-11-14 01:53
Hi @dfberry,

Creating a monorepo Azure Function app isn't possible today, but is currently part of our backlog. https://github.com/microsoft/vscode-azurefunctions/issues/2521

**Comment by MicroFish91** [comment] 2023-11-22 19:21
Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/2521

**Closed by MicroFish91** 2023-11-22 19:21 UTC
