### ISSUE TITLE
Socket hang up when deploying Azure Functions

### ISSUE THREAD

**Issue by christiangartner** [microsoft/vscode-azurefunctions#3100] opened 2022-04-07 08:54 UTC
Deployment using Azure Functions Extension (Deploy to Function App...) fails with VSCode version 1.66. When changed to previous version 1.65.2 of VSCode, everything works fine.

Azure Functions output logs:
9:45:47 AM xx-functions: Starting deployment...
9:45:51 AM xx-functions: Creating zip package...
9:46:06 AM xx-functions: Zip package size: 20.2 MB
10:01:42 AM: Error: request to https://xx-functions.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

This is a copy of a closed issue created from [lainean](https://github.com/lainean) in vscode-project: https://github.com/microsoft/vscode/issues/146885

**Comment by YipingRuan** [comment] 2022-04-07 11:51
Same here and as discussed rollback vscode fixed the issue.

More at https://docs.microsoft.com/en-us/answers/questions/795409/azure-function-vscode-stuck-on-deploying-to-34xxxx.html

**Comment by WillyMoselhy** [comment] 2022-04-07 13:48
Same here
BROKEN: VS Code 1.66.0  - Azure Function Extension 1.6.1
WORKING: VS Code 1.65.2 -  Azure Function Extension 1.6.1

**Comment by alexweininger** [comment] 2022-04-07 17:18
Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade your Azure Functions extension version to `1.2.1` (Feb 08, 2021), we used a different zip deploy method which seems to be working still. Note: it might not work in environments like WSL or Codespaces, which is why we changed our deploy in `1.3.0` (Mar 15, 2021).
4. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working as discussed and confirmed above.
---

Here's some information on the bug we suspect is causing the issue with zip deploy.

We suspect that it was a regression in the [libuv library](https://github.com/libuv/libuv) caused by [libuv/libuv@ce15b84](https://github.com/libuv/libuv/commit/ce15b8405e9d01e221f8390475deab4a40d26e38), which was included in Node.JS `16.13.0`.

See [this issue](https://github.com/microsoft/vscode/issues/146470), and specifically [this comment](https://github.com/microsoft/vscode/issues/146470#issuecomment-1087175293) for more information.

---

Follow along with #2844 for more updates and discussion, we're directing all of these zip deploy issues over there.

**Comment by alexweininger** [comment] 2022-04-07 17:18
Closing as a duplicate of #2844

**Closed by alexweininger** 2022-04-07 17:18 UTC

**Comment by alexweininger** [comment] 2022-04-13 19:19
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension.
