### ISSUE TITLE
Error "resources.map is not a function" when creating ServiceBusQueueTriggerCSharp function

### ISSUE THREAD

**Issue by gazzzmo** [Microsoft/vscode-azurefunctions#765] opened 2018-10-26 12:03 UTC
Repro steps:
Create new Function
Select ServiceBusQueueTriggerCSharp
Select namespace
After scanning for service bus queues - if none exist get error

Action: azureFunctions.createFunction
Error type: object
Error Message: resources.map is not a function

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-10-26 18:44
Thanks for filing! Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/755

This only happens if you don't have a service bus namespaces in your subscription. As a workaround, you can create a namespace in your subscription. Or if you don't want to mess with Azure, you can select an existing App Setting when prompted and manually change to a different app setting afterwards.

**Closed by EricJizbaMSFT** 2018-10-26 18:44 UTC
