### ISSUE TITLE
Could not Create a New Local Azure Function

### ISSUE THREAD

**Issue by Tuppu** [microsoft/vscode-azurefunctions#3284] opened 2022-08-11 09:02 UTC
Does this occur consistently?  Yes 

Repro steps:
1. Installed Azure Functions Extension
2. Select Azure Tab from the left bar
3. There isn't '+' symbol on the Local WORKSPACE

![image](https://user-images.githubusercontent.com/6342115/184100030-bfd01ac6-fa7e-4899-b70a-7e071ff6122a.png)

Why Isn't seen on the layout?
 
Version: 1.7.4
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.70.1
Language: en

**Comment by alexweininger** [comment] 2022-08-11 15:58
A few workarounds:
1. Use the command palette (accessed via pressing `F1`) to run commands. All Azure Functions commands can be run this way.
1. Downgrade VS Code to 1.69.  
1. Uninstall the App Service extension 😭

There's a recent [bug in VS Code](https://github.com/microsoft/vscode/issues/155030) that's causing some of our buttons to disappear. We're working on getting this fixed because we realize it's super annoying. Sorry for the trouble!

This bug also only happens when you have both the Azure Functions and Azure App Service extensions installed at the same time. So if you uninstall one of those (if you don't need App Service in this case) then the button should re-appear.

**Comment by alexweininger** [comment] 2022-08-11 15:59
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3280.

**Closed by alexweininger** 2022-08-11 15:59 UTC
