### ISSUE TITLE
Cannot deploy an Azure Function App to Azure from VS Code

### ISSUE THREAD

**Issue by jwill20** [microsoft/vscode-azurefunctions#1802] opened 2020-01-15 15:32 UTC
Repro steps:

1. Following instructions in https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code
2. Everything works except the deploy to Azure.
3. I can create an Azure function directly in the portal.

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.20.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:502525
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:673009
extension.bundle.js:164:24705
$._callback extension.bundle.js:1:632208
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-01-22 18:53
As a workaround please try the "Advanced" option when creating a function app. Your subscription likely doesn't have permissions for one of our defaults. Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1583

**Closed by EricJizbaMSFT** 2020-01-22 18:53 UTC
