### ISSUE TITLE
New Windows Function App disconnects for log streams and doesn't terminate output channel

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2775] opened 2021-04-20 09:59 UTC
**OS:** Windows
**Build Version:** 20210419.2

**Repro Steps:**
1. Create a new Windows Function App.
2. Right click this Function App and execute "Start Streaming Logs" action.
3. Check the output log within 10 mins.

**Expect:**
Succeed to connect to log stream and start streaming logs.

**Actual:**
Keep connecting to log stream more than 10 mins.
![image](https://user-images.githubusercontent.com/45614674/115376379-3b63df00-a201-11eb-806e-379e9b121e20.png)

4. Execute "Stop Streaming Logs" action for this Function App.
5. The output log doesn't match the notification message.
![image](https://user-images.githubusercontent.com/45614674/115375168-1c188200-a200-11eb-8fd6-5c7344a1646c.png)

**More Info:**
1. This issue does not reproduce for a deployed Function App.
2. If execute "Start Streaming Logs" action again, it will open a new output window.
![image](https://user-images.githubusercontent.com/45614674/115376863-a6adb100-a201-11eb-97ae-756a922f9eb8.png)

**Comment by ejizba** [comment] 2021-07-12 23:40
This no longer repros for me and is likely a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/2717. Can you double check if it still repros?

**Closed** 2022-03-11 05:19 UTC
Labels: bug, P3, AT-CTI
