### ISSUE TITLE
Used WSL2 Develop Azure Function in Python

### ISSUE THREAD

**Issue by skyline9002** [microsoft/vscode-azurefunctions#2458] opened 2020-10-10 15:03 UTC
Does this occur consistently? 
Repro steps:

1. Used WSL2 to develop python functions 
2. Try to deploy the function from VScode to Azure
3. The function could not be deployed automatically 

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://xxxxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.24.1
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-10-12 20:25
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2390

**Closed by EricJizbaMSFT** 2020-10-12 20:25 UTC
