### ISSUE TITLE
Did not find preDeploy task "func: extensions install"

### ISSUE THREAD

**Issue by connor4312** [Microsoft/vscode-azurefunctions#1015] opened 2019-02-21 18:26 UTC
Hi,

I tried to deploy a new function via the extension in VSCode. I'm using the latest version, 0.14.0, on OSX. When I attempt to deploy, I get this error:

```
Error: Did not find preDeploy task "func: extensions install". Change the "azureFunctions.preDeployTask" setting, manually edit your task.json, or re-initialize your VS Code config with the following steps:
1. Open Command Palette (View -> Command Palette...)
2. Search for "Azure Functions" and run command "Initialize Project for Use with VS Code"
3. Select "Yes" to overwrite your tasks.json file when prompted
```

Following the steps doesn't resolve the issue. The generated `task.json` looks like this:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "func",
      "command": "host start",
      "problemMatcher": "$func-watch",
      "isBackground": true,
      "dependsOn": "func: extensions install"
    }
  ]
}
```

I do have the `azure-functions-core-tools` installed and in my path, and am able to manually run `func extensions install` from the command line.

**Comment by EricJizbaMSFT** [comment] 2019-02-21 22:29
Are you only using Http or Timer triggers?

- If yes, you can remove the setting "azureFunctions.preDeployTask" in your `.vscode/settings.json` file.
- If no, we need to figure out why it can't find "func: extension install". What is your project langauge? And can you send a screenshot of your workspace? I'm wondering about your project structure and if you have the function app at the root or in a subdirectory

**Comment by connor4312** [comment] 2019-02-21 23:03
In this case I was only using a storage queue trigger. The language was Node.js--sorry, I forgot to mention that.

Assuming you've got an @microsoft.com you should be able to access our VSTS instance and see the actual code [here](https://watchmixer.visualstudio.com/Mixer/_git/community?path=%2Fpackages%2Fcommunity-functions%2Fsrc%2FworkOnDeletion&version=GBmaster). Here's my workspace:

![](https://memes.peet.io/img/19-02-je5nhx6gs4kq3hnu60ahjeqnida6bs.png)

**Comment by EricJizbaMSFT** [comment] 2019-02-21 23:39
Yeah we don't work well if the project is a subdirectory (aka in your "src" folder). That's tracked here and we hope to get a fix soon: https://github.com/Microsoft/vscode-azurefunctions/issues/686

**Comment by EricJizbaMSFT** [comment] 2019-02-22 02:43
Okay I've added some workarounds here: https://github.com/Microsoft/vscode-azurefunctions/issues/686#issuecomment-466252387

Closing this as a duplicate of #686

**Closed by EricJizbaMSFT** 2019-02-22 02:43 UTC
