### ISSUE TITLE
Deplyoment of Azure Function - Failed with code "403"

### ISSUE THREAD

**Issue by klaswolfgang** [microsoft/vscode-azurefunctions#1837] opened 2020-01-24 10:04 UTC
On Windows 10, Visual Studio Code (most recent versions),
the deployment of a locally created Azure function to Azure does not work as it always fails with error code 403.

The function could be tested and debugged locally, that works fine.
(The problem is exactly the same for languages Python and JavaScript.)

The problem could be the execution rights for some scripts, but those rights have been set to "unrestricted" according to the instructions here:
https://docs.microsoft.com/de-de/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7
Hence, those rights look like this:
S> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine       Unrestricted

But starting deployment via the VS code built-in procedure still results in the error message 
Failed with code "403".

 

Repro steps:

1. Just following the steps explained in the official tutorial here:
 https://docs.microsoft.com/de-de/azure/javascript/tutorial-vscode-serverless-node-04

Action: azureFunctions.deploy
Error type: 403
Error Message: Failed with code "403".

Version: 0.20.2
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:502569extension.bundle.js:218:502569
s extension.bundle.js:218:111756
s extension.bundle.js:164:25792
extension.bundle.js:164:27036extension.bundle.js:164:27036
o extension.bundle.js:164:674848
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:635041
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-01-29 23:28
As a workaround please try the "Advanced" option when creating a function app. Your subscription likely doesn't have permissions for something. Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1583

**Closed by EricJizbaMSFT** 2020-01-29 23:28 UTC
