### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Duffmann** [Microsoft/vscode-azurefunctions#867] opened 2018-12-15 19:36 UTC
[ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-azurefunctions/files/2683014/ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `0.13.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/dirk/ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Duffmann** [comment] 2018-12-15 19:40
[ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-azurefunctions/files/2683011/ms-azuretools.vscode-azurefunctions-unresponsive.cpuprofile.txt)

**Comment by EricJizbaMSFT** [comment] 2018-12-18 19:09
Thanks for filing @Duffmann. It looks like most of the time is spent in module load, which we already have plans to fix by using webpack. @StephenWeatherford already did this for our docker extension (https://github.com/Microsoft/vscode-docker/pull/645) and we've seen good results so far.

Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/708

**Closed by EricJizbaMSFT** 2018-12-18 19:09 UTC
