### ISSUE TITLE
Fail to list the function URL after deploying a Python project to Linux Dedicated Plan

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1296] opened 2019-05-22 10:20 UTC
**OS:** Mac\Win10
**Build Version**:[ 20190521.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6164)

**Repro Steps**:
1. Create a Python project.
2. Deploy to a Linux function app.
3. Check the result.

**Expect:**
Succeed to deploy and there is no error when getting the function URL.

**Actual:**
Display that succeed to deploy but fail to list the function URL.
![image](https://user-images.githubusercontent.com/34729092/58167267-6a056380-7c40-11e9-9562-5bebfc3384a5.png)

**More Info:**
1. This issue also reproduces after deploying a C#/JS project to a Linux function app.
2. This issue DOEN NOT reproduce after deploying a C#/JS project to a Windows function app.

**Comment by EricJizbaMSFT** [comment] 2019-05-23 20:45
What region was this in? The Azure team fixed a bug related to this a little bit ago, but I thought it was already deployed to all regions: https://github.com/Azure/azure-functions-host/issues/4372

**Comment by v-dantch** [comment] 2019-05-24 10:09
Hi Eric,

We tried to deploy a JS project to Linux function apps with below locations. And this issue also reproduces.
![image](https://user-images.githubusercontent.com/34729092/58320789-14eb6c80-7e4f-11e9-9b00-e0a4cca0bc06.png)


Location | State
-- | --
East   Asia | Repro
East   US | Repro
West   Europe | Repro
West   US | Repro

**Comment by EricJizbaMSFT** [comment] 2019-05-29 17:50
@v-dantch can you give me permissions to a function app that this repros on?

You should be able to do this in the portal. Go to "Platform Features -> All Settings"
![Screen Shot 2019-05-29 at 10 48 07 AM](https://user-images.githubusercontent.com/11282622/58579201-630dc080-81ff-11e9-812a-71f60f80f527.png)

Then go to "Access Control -> Add role assignment" and add me by email addresss
![Screen Shot 2019-05-29 at 10 48 23 AM](https://user-images.githubusercontent.com/11282622/58579212-66a14780-81ff-11e9-8e64-74b36de072f8.png)

**Comment by v-dantch** [comment] 2019-05-31 06:15
Hi Eric, sorry for the late notice 🙇. 
Done for the permission of function app "[test0530-l-python](https://ms.portal.azure.com/#blade/WebsitesExtension/FunctionsIFrameBlade/id/%2Fsubscriptions%2F92be7e56-8a60-427c-a3e3-0ebd54a827a1%2FresourceGroups%2Ftest0530lpython%2Fproviders%2FMicrosoft.Web%2Fsites%2Ftest0530-l-python)".

**Comment by EricJizbaMSFT** [comment] 2019-05-31 18:51
Ah didn't realize this was a Linux dedicated plan instead of consumption. I can repro on dedicated

**Comment by EricJizbaMSFT** [comment] 2019-07-19 21:38
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1374

**Closed by EricJizbaMSFT** 2019-07-19 21:38 UTC
Labels: AT-CTI, P1, bug
