### ISSUE TITLE
[Suggestion] Add a command "Select Function" when executing "Start Streaming Logs/Stop Streaming Logs/View Properties" commands

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2477] opened 2020-10-19 12:22 UTC
**OS:** All
**Build Version:** 20201015.3

**Repro Steps:**

1. F1 -> Type and select "Azure Functions: Execute Function Now..." -> Select a subscription -> Select a Function App -> Check the result.
2. F1 -> Type and select "Start Streaming Logs" -> Select a Function App -> Check the result.
3. Right click one function and check its context menu.

**Actual:**
There is no command "Select Function" when executing "Start Streaming Logs" command.

**Suggestion:**
Add a command "Select Function" when executing "Start Streaming Logs/Stop Streaming Logs/View Properties" commands.
![image](https://user-images.githubusercontent.com/62053665/96449172-0e7d4200-1247-11eb-8657-7e9c7aea8c28.png)

**More Info:**
There is a command "Select Function" when executing commands as below:
![image](https://user-images.githubusercontent.com/62053665/96449646-be52af80-1247-11eb-9bcd-04cdca80172e.png)

**Comment by EricJizbaMSFT** [comment] 2020-10-19 22:12
The problem is that the commands you mentioned work for functions and function apps. We could add support, but it could clutter up the command palette and/or confuse users. We will close this as "wont-fix" unless we get more user feedback asking for this

**Closed by EricJizbaMSFT** 2020-10-19 22:12 UTC
Labels: AT-CTI
