### ISSUE TITLE
Failed to get deployment stsatus

### ISSUE THREAD

**Issue by AmitFidler** [microsoft/vscode-azurefunctions#2433] opened 2020-10-04 08:26 UTC
Does this occur consistently? 
Repro steps:

Yes

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.23.0
OS: win32
OS Release: 10.0.14393
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:722464
rejected extension.bundle.js:164:721889
o extension.bundle.js:1:255722
extension.bundle.js:1:256219extension.bundle.js:1:256219
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-10-05 21:13
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1958

**Closed by EricJizbaMSFT** 2020-10-05 21:13 UTC
