### ISSUE TITLE
unable to deploy azure function

### ISSUE THREAD

**Issue by erix-m** [microsoft/vscode-azurefunctions#1189] opened 2019-04-15 21:06 UTC
Repro steps:1.2.Action: azureFunctions.createFunctionAppError type: 403Error Message: Failed with code "403".Version: 0.16.0OS: linuxVS Code Version: 1.33.1<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment] 2019-04-15 21:47
@erix-m can you describe repros steps? And what type of project you were trying to deploy?

**Comment by erix-m** [comment] 2019-04-15 23:43
This is an Azure Function using the template for Event Hub Trigger in VS Code. I just have a simple one file project, which I am able to run / debug locally on Ubuntu 18.04. I get this error when I try to deploy it using VS Code. I click the 'Deploy to Function App' button, choose 'Create new Function App in Azure', enter the unique name, and hit enter. This is when I see the error.

**Comment by EricJizbaMSFT** [comment] 2019-04-15 23:49
Can you copy the logs here?
<img width="621" alt="Screen Shot 2019-04-15 at 4 45 37 PM" src="https://user-images.githubusercontent.com/11282622/56172354-ea7bd900-5f9d-11e9-95f4-eac12db786cf.png">

What language is this project? Python/JavaScript/C#, etc.

You can try changing the setting `azureFunctions.advancedCreation` to `true`. That should prompt you for more values. For example picking a different region sometimes helps if there's an outage in one region.

**Comment by EricJizbaMSFT** [comment] 2019-04-17 20:38
Could be a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/1194. Do you have restricted permissions for your subscription?

**Closed** 2019-05-08 22:12 UTC
Labels: needs more info
