### ISSUE TITLE
Unable to connect git hub to functions from vscode

### ISSUE THREAD

**Issue by monishcm** [microsoft/vscode-azurefunctions#2428] opened 2020-10-01 09:38 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.connectToGitHub
Error type: Error
Error Message: Internal error: Action not supported.

Version: 0.24.1
OS: win32
OS Release: 10.0.20190
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1000:119069extension.bundle.js:1000:119069
fulfilled extension.bundle.js:1000:118457
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-10-05 21:20
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2369

**Closed by EricJizbaMSFT** 2020-10-05 21:20 UTC
