### ISSUE TITLE
Log streaming for Python

### ISSUE THREAD

**Issue by asavaritayal** [microsoft/vscode-azurefunctions#1292] opened 2019-05-22 00:11 UTC
Enable log streaming for Python. Instead of using the Kudu endpoint, launch the **Live Metrics Stream** view in the browser.

**Comment by EricJizbaMSFT** [comment] 2019-05-22 18:11
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/589

**Closed by EricJizbaMSFT** 2019-05-22 18:11 UTC
Labels: python
