### ISSUE TITLE
No + on workspace to add function project

### ISSUE THREAD

**Issue by stan-exostar** [microsoft/vscode-azurefunctions#3282] opened 2022-08-09 21:37 UTC
Does this occur consistently? Yes
Repro steps:

1. Installed Azure Extensions and Azure Functions extension into VSCode
2. Logged into Azure account (subscription is there).
3. Opened RESOURCES and clicked on Function App to see what was there.
4. Went to WORKSPACE and had only an icon for Deploy and for Refresh, not for Add project.
![VSCodeFunctionsCannotAdd](https://user-images.githubusercontent.com/109746516/183765706-6dcdb807-7462-4990-9b48-0305f14c1f2c.png)

I expected a + sign to add a function project. As it stands, I can't create a function project so can't work with functions at all. Is there some trick? Happening on two machines.

Version: 1.7.4
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

**Comment by stan-exostar** [comment] 2022-08-09 21:41
Nuts, just saw this was already reported.

**Comment by alexweininger** [comment] 2022-08-09 21:46
A few workarounds:
1. Downgrade VS Code to 1.69. 
2. Use the command palette (accessed via pressing `F1`) to run commands. All Azure Functions commands can be run this way.

There's a recent bug in VS Code that's causing some of our buttons to disappear. We're working on getting this fixed because we realize it's super annoying. Sorry for the trouble!

This bug also only happens when you have both the Azure Functions and Azure App Service extensions installed at the same time. So if you uninstall one of those (if you don't need App Service in this case) then the button should re-appear.

**Comment by alexweininger** [comment] 2022-08-11 15:59
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3280

**Closed by alexweininger** 2022-08-11 15:59 UTC
