### ISSUE TITLE
Creating Azure Python functions behind private proxy -- pip proxy

### ISSUE THREAD

**Issue by IDoCodingStuffs** [Microsoft/vscode-azurefunctions#870] opened 2018-12-17 18:55 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Failed to run ".env\Scripts\activate && func init ./ --worker-runtime python" command. Check output window for more details.

Output: 

Error running 'pip install wheel'. Collecting wheel
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001402649DBE0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/wheel/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001402649DB70>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/wheel/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001402649D908>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/wheel/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001402649DBA8>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/wheel/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001402649DA20>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/wheel/
  Could not find a version that satisfies the requirement wheel (from versions: )
No matching distribution found for wheel

Version: 0.13.0
OS: win32

**Comment by asavaritayal** [comment] 2018-12-17 22:49
@IDoCodingStuffs can you please provide the exact repro steps for this issue?

**Comment by Bandit253** [comment] 2018-12-18 09:59
This the same as mine
**Proxy problem when creating python function** #868

**Comment by EricJizbaMSFT** [comment] 2018-12-18 18:54
Closing as duplicate of #868

**Closed by EricJizbaMSFT** 2018-12-18 18:54 UTC
