### ISSUE TITLE
Pop up an error when running 'Start Streaming Logs' for one deployed Linux function app with Python

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#734] opened 2018-10-18 09:30 UTC
Version: 1.29.0-insider (user setup)
Node.js: 8.9.3
Architecture: x64
Extension version: ![image](https://user-images.githubusercontent.com/34729022/47144273-b0d15a80-d2f9-11e8-9b4f-6f319610c40c.png)
Repro Steps:
1. Create a project with Python.
2. Create a Function adding an HttpTrigger.
3. Deploy to one Linux function app.
4. Right click the function app -> Select 'Start Streaming Logs' -> Check the result.

Expect:
Succeed to connect to the Streaming logs with no error.

Actual:
Pop up an error "this operation is not support"
![notsupport](https://user-images.githubusercontent.com/34729022/47144688-93e95700-d2fa-11e8-8697-d93b5da96869.png)

**Comment by EricJizbaMSFT** [comment] 2018-10-18 16:56
Thanks for filing. This is a known issue with Linux Consumption apps. Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/589

**Closed by EricJizbaMSFT** 2018-10-18 16:56 UTC
Labels: CTI
