### ISSUE TITLE
issue deploy app fuction in visual studio code

### ISSUE THREAD

**Issue by DongyueWang** [microsoft/vscode-azurefunctions#1669] opened 2019-11-08 00:45 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2860478extension.bundle.js:218:2860478
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-11-08 18:08
@DongyueWang please try picking a different type of plan or region and/or add more detailed repro steps

**Comment by pcseanmckay** [comment] 2019-11-13 03:36
@EricJizbaMSFT This error is occurring while trying to deploy an azure function app using Visual Studio Code in the following learning path module: Enable automatic updates in a web application using Azure Functions and SignalR Service.  So he should only need to choose the appropriate plan that was created in the sandbox for the learning path.

**Comment by EricJizbaMSFT** [comment] 2019-11-13 19:42
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1676 since that is the same error with more info

**Closed by EricJizbaMSFT** 2019-11-13 19:42 UTC
Labels: needs more info
