### ISSUE TITLE
Error following Azure Functions quickstart

### ISSUE THREAD

**Issue by haugan** [microsoft/vscode-azurefunctions#1917] opened 2020-02-24 09:20 UTC
Following the quickstart Create an Azure Functions project using Visual Studio Code, I install latest verison of nodejs, updated VS Code, made sure to install Azure Functions and C# extension. After creating a new Azure Functions project, following instructions from the quickstart docs (at https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-csharp) I press F5 and then this error shows up in my Terminal log. The project won't start.

Build started 24.02.2020 10:16:55.
     1>Project "c:\Dev\Sandbox\AzureFunctions\AzureFunctions.csproj" on node 1 (Clean target(s)).
     1>CoreClean:
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\host.json".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\local.settings.json".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\AzureFunctions.deps.json".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\AzureFunctions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\System.Net.Http.Formatting.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Authentication.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Authentication.Core.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Authorization.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Authorization.Policy.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Hosting.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Http.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Http.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Http.Extensions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Http.Features.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.JsonPatch.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Mvc.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Mvc.Core.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll".        
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Routing.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.Routing.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.AspNetCore.WebUtilities.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Azure.WebJobs.Host.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Azure.WebJobs.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Azure.WebJobs.Extensions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Azure.WebJobs.Extensions.Http.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Azure.WebJobs.Host.Storage.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Build.Framework.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Build.Utilities.Core.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.DotNet.PlatformAbstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.Binder.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.EnvironmentVariables.dll".  
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.FileExtensions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Configuration.Json.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.DependencyInjection.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.DependencyInjection.Abstractions.dll".    
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.DependencyModel.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.FileProviders.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.FileProviders.Physical.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.FileSystemGlobbing.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Hosting.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Hosting.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Logging.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Logging.Abstractions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Logging.Configuration.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.ObjectPool.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Options.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Options.ConfigurationExtensions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Extensions.Primitives.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.Net.Http.Headers.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\NCrontab.Signed.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Newtonsoft.Json.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Newtonsoft.Json.Bson.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\Microsoft.WindowsAzure.Storage.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.csprojAssemblyReference.cache".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.AssemblyInfoInputs.cache".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.AssemblyInfo.cs".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.csproj.CopyComplete".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.dll".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\obj\Debug\netcoreapp3.0\AzureFunctions.pdb".
       _CleanFunctions:
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\AzureFunctions.pdb".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\extensions.json".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\function.deps.json".
         Deleting file "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\HttpExample\function.json".
         Removing directory "c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\".
     1>Done Building Project "c:\Dev\Sandbox\AzureFunctions\AzureFunctions.csproj" (Clean target(s)).

Terminal will be reused by tasks, press any key to close it.

> Executing task: C:\Program Files\dotnet\dotnet.exe build /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary <

Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34,62 ms for c:\Dev\Sandbox\AzureFunctions\AzureFunctions.csproj.
  AzureFunctions -> c:\Dev\Sandbox\AzureFunctions\bin\Debug\netcoreapp3.0\bin\AzureFunctions.dll

Terminal will be reused by tasks, press any key to close it.

> Executing task: func host start <

func : File C:\Users\hauga\AppData\Roaming\npm\func.ps1 cannot be loaded. The file C:\Users\hauga\AppData\Roaming\npm\func.ps1 is not digitally 
signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Exe 
cution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ func host start
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
The terminal process terminated with exit code: 1

**Comment by haugan** [comment] 2020-02-24 09:27
Fixed by running this command in PowerShell

`Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser`

Still, maybe the Quickstart should contain some information regarding this. If that's already the case, I apologize for overlooking it.

**Comment by EricJizbaMSFT** [comment] 2020-02-24 21:43
Looks like a dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1678

**Closed by EricJizbaMSFT** 2020-02-24 21:43 UTC
