### ISSUE TITLE
Error while following https://docs.microsoft.com/nb-no/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/5-exercise-enable-automatic-updates-in-a-web-app-using-signalr

### ISSUE THREAD

**Issue by longcui** [microsoft/vscode-azurefunctions#1711] opened 2019-11-22 16:15 UTC
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: 403
Error Message: Failed with code "403".

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:502525extension.bundle.js:218:502525
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-12-02 19:23
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1676

**Closed by EricJizbaMSFT** 2019-12-02 19:23 UTC

**Comment by EricJizbaMSFT** [comment] 2019-12-02 19:25
@longcui as a workaround you can try the "Advanced" option when creating a function app in Azure. If you still have issues, feel free to comment on 1676
