### ISSUE TITLE
Deploy to Function App sometimes fail with the error (Failed to get status of Deployment)

### ISSUE THREAD

**Issue by ahmed-magdy-maersk** [microsoft/vscode-azurefunctions#2493] opened 2020-10-27 10:59 UTC
Does this occur consistently?
No
Repro steps:
1. From the Azure / Functions section, click on the (Deploy to Function App..) button
2. Choose the web app to deploy to
3. Sometimes it fails with the error below, and running it again works (without any changes on my side)

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 1.0.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:54:14844
fulfilled extension.bundle.js:54:13091
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-10-27 17:31
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1958

**Closed by EricJizbaMSFT** 2020-10-27 17:31 UTC
