### ISSUE TITLE
Azure Function extension fails to create trigger function (Cannot read properties of undefined (reading 'getSubscriptionPromptStep'))

### ISSUE THREAD

**Issue by ivctr** [microsoft/vscode-azurefunctions#3195] opened 2022-05-26 09:57 UTC
When creating a new local app settings, "locals.settings.json" it returns Cannot read properties of undefined (reading 'getSubscriptionPromptStep') as error message

**Comment by dwoldo** [comment] 2022-05-26 16:40
I am experiencing this issue as well.

Azure Function Extension v1.7.0
Python Extension v2022.6.2
Python v3.10.4
VS Code v1.67.2 (user setup)

**Comment by alexweininger** [comment] 2022-05-26 17:17
Thanks for reporting the issue. Until we release a fix for this issue, a workaround is to install the previous version of the extension.

To do this, go to the Azure Functions page in the Extensions explorer and using the dropdown on the "Uninstall" button, select "Install another version..."

<img width="610" alt="Screen Shot 2022-05-26 at 10 16 02 AM" src="https://user-images.githubusercontent.com/12476526/170540461-4e93b4b4-aad4-4500-9922-48b497ebf7fa.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/12476526/170540268-80e90d33-82e9-4aeb-a23b-b2a1847d85de.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/12476526/170540512-29e3bfb2-82f0-4e89-8f1f-87e35b777382.png">

**Comment by alexweininger** [comment] 2022-05-26 17:18
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3191

**Closed by alexweininger** 2022-05-26 17:18 UTC

**Comment by alexweininger** [comment] 2022-05-27 18:55
Fix has been released https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.7.2
