### ISSUE TITLE
Navigate to home page after loading “Live Metrics Stream” for a few seconds in Azure Portal for Linux function apps

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurefunctions#1471] opened 2019-08-29 07:06 UTC
**Build Version**: [20190828.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9222)
**OS**: Windows

**Repro Steps:**
1. F1 --> Type and select "Create Function App in Azure ... (Advanced)".
2. Enter a valid function name --> Select "Linux" OS --> Select "Consumption Plan" --> Select a runtime --> Create a new resource group with a new storage account --> Create a new Application Insights resource --> Select a location.
3. Right click this new Linux function app  after it has been created successfully -->Select "Start Streaming Logs".

**Expect:**
Open the Live Metrics Stream.
![image](https://user-images.githubusercontent.com/34729092/63918076-8fd7ab00-ca6e-11e9-964a-5ed30467394d.png)

**Actual:**
Loading "Live Metrics Stream" **for a few seconds**, then **navigate to the home page** in Azure Portal.

**More Info:**
1. This issue reproduces with all 3 runtimes : .NET , Python and JavaScript.
2. This issue reproduces with all locations like below:

Location | Result
-- | --
East   Asia | Repro
Australia East | Repro
East   US | Repro
East US 2 | Repro
North   Europe | Repro
South   Central US | Repro
Southeast   Asia | Repro
UK   South | Repro
West   Europe | Repro
West   US | Repro
West   US 2 | Repro

**Comment by EricJizbaMSFT** [comment] 2019-08-29 18:41
What browser are you using?

Does this reproduce on a Mac?

**Comment by v-dantch** [comment] 2019-08-30 09:04
This issue reproduces on Mac and Linux(We only tried on Mac and Linux). And we use Edge on Windows and Safari on Mac.

**Comment by EricJizbaMSFT** [comment] 2019-09-19 22:50
I can't repro, but @nturinski can so I can investigate with his help :)

**Comment by EricJizbaMSFT** [comment] 2020-02-14 17:59
Still can't repro this. Since no users have reported it and it's likely a bug in the portal anyways (aka out of our control) - I'm going to close this as won't-fix

**Closed by EricJizbaMSFT** 2020-02-14 17:59 UTC
Labels: AT-CTI, bug, investigate
