### ISSUE TITLE
Cannot read properties of undefined (reading 'client')

### ISSUE THREAD

**Issue by ali-homayouni** [microsoft/vscode-azurefunctions#3377] opened 2022-10-18 15:02 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'client')

Version: 1.0.1
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.72.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:706:91122extension.bundle.js:706:91122
fulfilled extension.bundle.js:706:90188
```

</details>

**Comment by nturinski** [comment] 2022-10-18 17:51
Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3378

**Closed by nturinski** 2022-10-18 17:51 UTC
