### ISSUE TITLE
Can't create site exception following tutorial  Enable automatic updates (...) using Azure Functions & SignalR 

### ISSUE THREAD

**Issue by tassilostefan** [microsoft/vscode-azurefunctions#1724] opened 2019-11-29 14:48 UTC
Repro steps:

1. Follow the steps [here](https://docs.microsoft.com/en-us/learn/modules/automatic-update-of-a-webapp-using-azure-functions-and-signalr/7-exercise-host-a-static-website-using-a-storage-account)
2. Before arriving at the exception, the first issue is that I cannot select JavaScript language
3. The settings provided under "Deploy the function app" then lead to the exception below

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2860478extension.bundle.js:218:2860478
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by anthonychu** [comment] 2019-12-02 17:43
Can you confirm that you used the "Advanced" option?

![image](https://user-images.githubusercontent.com/3982077/69981712-ba128c00-14e7-11ea-8cc3-a0642aade177.png)

@craigshoemaker Do you know if there's been changes to the concierge subscriptions that would have placed restrictions on deployments?

**Comment by anthonychu** [comment] 2019-12-02 17:45
May be related to #1711

**Comment by EricJizbaMSFT** [comment] 2019-12-02 19:22
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1676

**Closed by EricJizbaMSFT** 2019-12-02 19:22 UTC
