### ISSUE TITLE
Improve error message when user F5's without func cli installed

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurefunctions#328] opened 2018-04-18 10:01 UTC
Repro steps:
1. Creat a function project.
2. Set a breakpoint in index.js file and debug it.
3. Verify whether the debugging can succeed or not.

Expect:
No error dialog pops up after debugging.

Actual:
Pop up an error dialog after debugging.
![actual](https://user-images.githubusercontent.com/37653604/38924442-7e4d22bc-42ec-11e8-960a-a103a0f97212.png)

**Comment by EricJizbaMSFT** [comment] 2018-04-19 21:33
This works fine for me. Do you have node and the functions runtime installed? What versions? What OS are you on?

See the prereqs for more info: https://github.com/Microsoft/vscode-azurefunctions#prerequisites

**Comment by EricJizbaMSFT** [comment] 2018-12-18 18:44
Moving this out of "future" milestone due to #873. We have a warning message after the user creates a new project, but it doesn't show if the extension host restarts (aka if the folder isn't open and they have to open it in VS Code)
<img width="465" alt="screen shot 2018-12-18 at 10 42 18 am" src="https://user-images.githubusercontent.com/11282622/50175505-ce974d80-02b1-11e9-9321-72c275acdb2f.png">

NOTE: If we fix https://github.com/Microsoft/vscode-azurefunctions/issues/358, I don't think this bug is necessary

**Comment by EricJizbaMSFT** [comment] 2019-01-16 19:53
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/358

**Closed by EricJizbaMSFT** 2019-01-16 19:53 UTC
Labels: CTI, P2, enhancement
