### ISSUE TITLE
There is an error when debugging a PowerShell project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#2211] opened 2020-07-03 10:30 UTC
**OS:** Linux/Mac
**Build Version:** 20200703.6
**PowerShell Version:** 7.0

**Repro Steps:**

1. Crete a PowerShell project.
2. Debug it.

**Expect:**
Debug successfully without any error.

**Actual:**
There is an error.
![image](https://user-images.githubusercontent.com/62053665/86459604-9eab8000-bd59-11ea-8b79-b50e469eb1dc.png)

**More info:**
This issue does not reproduce on Win10.

**Comment by EricJizbaMSFT** [comment] 2020-07-06 18:02
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1723

**Closed by EricJizbaMSFT** 2020-07-06 18:02 UTC
Labels: AT-CTI
