### ISSUE TITLE
Include tooltips or other visual queues during ‘Create Project’ so customers can understand configuration options. 

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2342] opened 2020-08-26 06:50 UTC
What problem would the feature you're requesting solve? Please describe.
Many of the options during the create function create project flow in VSC are not intuitive. AA key example of this are the 3 auth levels (Admin, Functions, Anon). However, things like triggers can easily be explained and save the customer some time googling these options.

To help aide customers, it might be helpful to include a visual que that prompts the user with more information for a specific option. A tooltip next to each option feels like it could make sense, but I'll leave that up to your team and the designers to sort out :)

Describe the solution you'd like
For example, instead of having just
![image](https://user-images.githubusercontent.com/6217333/91270603-c0a7fa00-e72d-11ea-8277-ab6b2aba1c62.png)

Maybe having text right underneath each selection describing what they are might be better.

This is a suggestion for all of options.

**Comment by EricJizbaMSFT** [comment] 2020-08-31 21:52
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1788

**Closed by EricJizbaMSFT** 2020-08-31 21:52 UTC
