### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by rajen03333** [microsoft/vscode-azurefunctions#2362] opened 2020-09-05 14:20 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:39:14848
fulfilled extension.bundle.js:39:13096
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by rtreit** [comment] 2020-09-08 17:18
I am seeing this as well - when I try to deploy an update to my functions from within VS Code it is consistently failing the first time and if I do it again then it seems to succeed. Although a couple times it failed more than once in a row.

**Comment by EricJizbaMSFT** [comment] 2020-09-12 00:11
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1958

**Closed by EricJizbaMSFT** 2020-09-12 00:11 UTC
