### ISSUE TITLE
problem while creating function using visual code extension

### ISSUE THREAD

**Issue by nimishmehta8779** [microsoft/vscode-azurefunctions#2415] opened 2020-09-26 06:28 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunctionApp
Error type: BadRequest
Error Message: Requested features are not supported in region. Please try another region.

Version: 0.24.1
OS: linux
OS Release: 5.4.0-48-generic
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
extension.bundle.js:48:1291123
Promise.propagateAslWrapper async-listener/index.js:504:23
Promise.__asl_wrapper async-listener/glue.js:188:31
proxyWrapper async-listener/index.js:529:23
async-listener/index.js:541:70
async-listener/glue.js:188:31
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-09-28 21:15
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2258

**Closed by EricJizbaMSFT** 2020-09-28 21:15 UTC
