### ISSUE TITLE
Warning to show end of life for selected stack when eol is within 6 months or passed already

### ISSUE THREAD

**Issue by kulkarnisonia16** [microsoft/vscode-azurefunctions#3348] opened 2022-09-21 05:01 UTC
![image](https://user-images.githubusercontent.com/10569526/191418047-357a3ab9-b60a-41c9-87ce-fbca5d54c24e.png)

**Comment by nturinski** [comment] 2022-09-22 23:04
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3353

**Closed by nturinski** 2022-09-22 23:04 UTC
