### ISSUE TITLE
error!!!

### ISSUE THREAD

**Issue by mlianghua** [microsoft/vscode-azurefunctions#2511] opened 2020-11-03 03:33 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to get latest templates: Failed to detect Azure Functions maven plugin version.

Version: 1.0.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
CentralTemplateProvider.<anonymous> extension.bundle.js:451:428378
fulfilled extension.bundle.js:451:424812
```

</details>

**Comment by nturinski** [comment] 2020-11-03 19:16
Please check your pom.xml and make sure it doesn't have any errors. Also check for the property `azure.functions.maven.plugin.version` to make sure it exists. If you're still having problems, add more detailed repro steps

**Comment by EricJizbaMSFT** [comment] 2020-11-03 22:13
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2508

**Closed by EricJizbaMSFT** 2020-11-03 22:13 UTC
Labels: needs more info
