### ISSUE TITLE
npm tool failing to install

### ISSUE THREAD

**Issue by KoshurBhat** [microsoft/vscode-azurefunctions#1819] opened 2020-01-21 06:04 UTC
Issue Type: <b>Performance Issue</b>

Hi Team,
I have been trying to install-start npm tool for Azure functions but even after installation its failing to get started. Its not showing up even on powershell. Please help!!

Extension version: 0.20.1
VS Code version: Code - Insiders 1.42.0-insider (d72b2d372f5024a9193b37a3830bbbc459c0ef1b, 2020-01-20T05:33:26.563Z)
OS version: Windows_NT x64 6.3.9600

**Comment by EricJizbaMSFT** [comment] 2020-01-21 17:57
@KoshurBhat please add a little more detail to this issue. I'm a little confused about what you mean by "install-start npm tool". Any logs or errors that you see would be very helpful.

**Comment by KoshurBhat** [comment] 2020-01-22 16:29
@EricJizbaMSFT I had install the Azure Functions extensions as is required for Visual Studio Code. Even though the installation seems successful but when I try to run the required code to access my resources on Azure, it fails. Not sure how to capture any logs for the same. Please suggest

**Comment by EricJizbaMSFT** [comment] 2020-01-22 18:29
What do you mean by "it fails"? Can you tell me the error message? Even a screenshot would be helpful

**Comment by KoshurBhat** [comment] 2020-01-22 19:52
![issue_SS](https://user-images.githubusercontent.com/39535100/72928826-a9132800-3d7e-11ea-8d47-d312f41dae98.png)

**Comment by EricJizbaMSFT** [comment] 2020-04-08 22:51
Likely a problem with the PATH environment variable. Will close as a dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2019

**Closed by EricJizbaMSFT** 2020-04-08 22:51 UTC
Labels: needs more info
