### ISSUE TITLE
Failure to deploy from VSC to Azure Function to overwrite current read-only function 

### ISSUE THREAD

**Issue by amran15** [microsoft/vscode-azurefunctions#1716] opened 2019-11-25 17:59 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: Run-From-Zip is set to a remote URL using WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.

Version: 0.20.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:393195
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:636440
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment] 2019-11-26 18:00
@amran15 

Thanks for reporting.  Please provide repro steps.

**Comment by EricJizbaMSFT** [comment] 2019-12-02 17:53
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1073

**Closed by EricJizbaMSFT** 2019-12-02 17:53 UTC
Labels: needs more info
