### ISSUE TITLE
Local debugging doesn't work with enterprise proxy

### ISSUE THREAD

**Issue by pmadusud** [Microsoft/vscode-azurefunctions#808] opened 2018-11-14 23:21 UTC
I am using the latest version of Visual Studio code and developing Azure functions using .NET Core tools. The azure functions tries to connect with the public API for certain processing. 

My development environment is behind the enterprise proxy. When I try to do local debugging I get the below error which I believe is due to the proxy authentication.
`A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

The local debugging doesn't seem to take the Standard IE proxy settings and also the http.proxy in the Visual Studio User setting. Even with those settings i get the same error mentioned above.

Any pointers to resolve the issue will be great.

**Comment by EricJizbaMSFT** [comment] 2018-11-27 17:01
Extension support for proxies has been recently added in VS Code insiders. You're welcome to try it out. See here for more info: https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-441998815

We already have an issue tracking in this repo, so closing as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/493

**Closed by EricJizbaMSFT** 2018-11-27 17:01 UTC
