### ISSUE TITLE
not able to create azure function

### ISSUE THREAD

**Issue by ravikumar144** [microsoft/vscode-azurefunctions#1828] opened 2020-01-23 10:35 UTC
Repro steps:

1.
2.

Action: azureFunctions.createNewProject
Error type: TypeError
Error Message: Invalid Version: 3.7.0a4

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
new W extension.bundle.js:1:172662
oe.test extension.bundle.js:1:183826
Function.ce [as satisfies] extension.bundle.js:1:178804
extension.bundle.js:1:801512extension.bundle.js:1:801512
Object.t.isSupportedPythonVersion extension.bundle.js:1:801502
extension.bundle.js:164:360847extension.bundle.js:164:360847
o extension.bundle.js:164:359890
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-01-23 18:06
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1754. Fix is already merged in master - should be released soon

**Closed by EricJizbaMSFT** 2020-01-23 18:06 UTC
