### ISSUE TITLE
Unable to execute Azure function from VS Core

### ISSUE THREAD

**Issue by vasanthmurugan-office** [microsoft/vscode-azurefunctions#1753] opened 2019-12-13 17:05 UTC
Repro steps:

1.
2.

Action: azureFunctions.executeFunction
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:7071

Version: 0.20.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:218:1076707
$.callback extension.bundle.js:218:1075381
$.e.callback.t.callback [as _callback] extension.bundle.js:218:1074827
t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.onRequestError extension.bundle.js:194:14671
ClientRequest.emit events.js:200:13
Socket.socketErrorListener _http_client.js:402:9
Socket.emit events.js:200:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-04-08 22:48
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1617

**Closed by EricJizbaMSFT** 2020-04-08 22:48 UTC
