### ISSUE TITLE
Unable to create python function in existing workspace

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/vscode-azurefunctions#2504] opened 2020-10-30 21:40 UTC
Issue Type: <b>Bug</b>

Had a folder open that had a python flask app.  Added a new blank folder to the workspace. Tried to create a function in it.  During creation it says Message: Unable to write to Folder Settings because no resource is provided.  Seems to be related to #414.  Resolved by opening folder in it's own window (not in workspace) and could create fine

Extension version: 1.0.0
VS Code version: Code - Insiders 1.51.0-insider (2d8bbc6976748c4b0c5e84be541674b89b9d91e4, 2020-10-30T06:57:39.786Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (39.76GB free)|
|Process Argv|--crash-reporter-id 6d902a21-4e78-43ea-9df3-2855bc1c55bd|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by EricJizbaMSFT** [comment] 2020-11-02 22:44
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2506

**Closed by EricJizbaMSFT** 2020-11-02 22:44 UTC
