### ISSUE TITLE
Fail to debug a PowerShell project with an error on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3061] opened 2022-03-02 07:30 UTC
**OS:** M1 Pro 
**Build Version:** 20220228.3
**Regression:** Not a regression

**Repro Steps:**

1. Open a new folder in the VS Code -> Click "Create New Project..." button -> Select the opened folder -> PowerShell -> HTTP trigger -> Type a function name -> Type a namespace -> Function.
2. Debug with "Attach to PowerShell Functions“.
3. Check whether succeeds to debug without any error.

**Expect:**
Succeed to debug without any error.

**Actual:**
Fail to debug with an error.
<img width="261" alt="Screen Shot 2022-03-02 at 2 12 25 PM" src="https://user-images.githubusercontent.com/62053665/156306097-7eec35c0-2850-42cd-a733-21d02d866f1c.png">

**More Info:**
Debug again or restart VS Code can not fix this issue.

**Comment by nturinski** [comment] 2022-07-07 22:28
Closing as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3223

**Closed by nturinski** 2022-07-07 22:28 UTC
Labels: AT-CTI
