### ISSUE TITLE
Enable log streaming for Python/Linux functions

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#833] opened 2018-11-28 22:54 UTC

**Comment by EricJizbaMSFT** [comment] 2018-11-28 23:50
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/589

We currently have that in 'tracking' milestone since we use kudu to stream logs and I don't know how we'd do it without kudu.

**Closed by EricJizbaMSFT** 2018-11-28 23:50 UTC
