### ISSUE TITLE
Error attempting to publish function app

### ISSUE THREAD

**Issue by mcollier** [microsoft/vscode-azurefunctions#3336] opened 2022-09-15 14:21 UTC
When attempting to publish a function app, I receive an "Error: Cannot read properties of undefined (reading 'createClient')" error message.  No additional information is provided in VS Code.

Azure Functions extension version v1.7.4.

**Comment by nturinski** [comment] 2022-09-15 18:32
Hi @mcollier 

Sorry you're running into this issue.  This is a known [issue](https://github.com/microsoft/vscode-azureappservice/issues/2291). The current workaround is to run the command again or to open the Azure tree view prior to deploying.

**Comment by alexweininger** [comment] 2022-10-13 22:27
Duplicate of #3369, track the progress on releasing a fix on that issue.

**Closed by alexweininger** 2022-10-13 22:27 UTC
Labels: bug
