### ISSUE TITLE
A warning "No job functions found..." occurs in Terminal logs when debugging a C# project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#2217] opened 2020-07-07 09:55 UTC
**OS:** Mac
**Build Version:** 20200706.1
**.NET Core SDK Version:** 3.1.301

**Repro Steps:**
1. Create a C# project with HttpTrigger function.
2. Debug this project and check the Terminal logs.

**Expect:**
Debug successfully without any warning.

**Actual:**
A warning "No job functions found..." occurs in Terminal logs.
![Screen Shot 2020-07-07 at 2 26 47 PM](https://user-images.githubusercontent.com/45614674/86764339-8cdc1c80-c07a-11ea-8280-708cd678ebef.png)

Detailed log:

> Executing task: func host start <

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (3.0.2630 Commit hash: beec61496e1c5de8aa4ba38d1884f7b48233a7ab)
Function Runtime Version: 3.0.13901.0
[7/7/2020 6:23:25 AM] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'a16013c4-63d6-4805-bd4d-4a0bafa75acd'
[7/7/2020 6:23:26 AM] Reading host configuration file '/Users/azuretest/Desktop/serene/project/cs/bin/Debug/netcoreapp3.1/host.json'
[7/7/2020 6:23:26 AM] Host configuration file read:
[7/7/2020 6:23:26 AM] {
[7/7/2020 6:23:26 AM]   "version": "2.0",
[7/7/2020 6:23:26 AM]   "extensionBundle": {
[7/7/2020 6:23:26 AM]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[7/7/2020 6:23:26 AM]     "version": "[1.*, 2.0.0)"
[7/7/2020 6:23:26 AM]   }
[7/7/2020 6:23:26 AM] }
[7/7/2020 6:23:30 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:python
[7/7/2020 6:23:30 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:java
[7/7/2020 6:23:30 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:powershell
[7/7/2020 6:23:30 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:node
[7/7/2020 6:23:30 AM] Loading functions metadata
[7/7/2020 6:23:30 AM] Reading functions metadata
[7/7/2020 6:23:30 AM] 0 functions found
[7/7/2020 6:23:30 AM] 0 functions loaded
[7/7/2020 6:23:30 AM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /var/folders/c4/7rjnq7qn5xn41z95g9rv7wv80000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[7/7/2020 6:23:30 AM] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[7/7/2020 6:23:31 AM] Downloading extension bundle from https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.3.0/Microsoft.Azure.Functions.ExtensionBundle.1.3.0.zip to /var/folders/c4/7rjnq7qn5xn41z95g9rv7wv80000gn/T/122ac66f-d139-492a-a65e-e373077dccac/Microsoft.Azure.Functions.ExtensionBundle.1.3.0.zip
[7/7/2020 6:23:42 AM] Completed downloading extension bundle from https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.3.0/Microsoft.Azure.Functions.ExtensionBundle.1.3.0.zip to /var/folders/c4/7rjnq7qn5xn41z95g9rv7wv80000gn/T/122ac66f-d139-492a-a65e-e373077dccac/Microsoft.Azure.Functions.ExtensionBundle.1.3.0.zip
[7/7/2020 6:23:42 AM] Extracting extension bundle at /var/folders/c4/7rjnq7qn5xn41z95g9rv7wv80000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.3.0
[7/7/2020 6:23:42 AM] Zip extraction complete
[7/7/2020 6:23:42 AM] Loading extension bundle from /var/folders/c4/7rjnq7qn5xn41z95g9rv7wv80000gn/T/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.3.0
[7/7/2020 6:23:43 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:python
[7/7/2020 6:23:43 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:java
[7/7/2020 6:23:43 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:powershell
[7/7/2020 6:23:43 AM] FUNCTIONS_WORKER_RUNTIME set to dotnet. Skipping WorkerConfig for language:node
[7/7/2020 6:23:43 AM] Initializing Warmup Extension.
[7/7/2020 6:23:44 AM] Initializing Host. OperationId: 'a16013c4-63d6-4805-bd4d-4a0bafa75acd'.
[7/7/2020 6:23:44 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=a16013c4-63d6-4805-bd4d-4a0bafa75acd
[7/7/2020 6:23:44 AM] LoggerFilterOptions
[7/7/2020 6:23:44 AM] {
[7/7/2020 6:23:44 AM]   "MinLevel": "None",
[7/7/2020 6:23:44 AM]   "Rules": [
[7/7/2020 6:23:44 AM]     {
[7/7/2020 6:23:44 AM]       "ProviderName": null,
[7/7/2020 6:23:44 AM]       "CategoryName": null,
[7/7/2020 6:23:44 AM]       "LogLevel": null,
[7/7/2020 6:23:44 AM]       "Filter": "<AddFilter>b__0"
[7/7/2020 6:23:44 AM]     },
[7/7/2020 6:23:44 AM]     {
[7/7/2020 6:23:44 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[7/7/2020 6:23:44 AM]       "CategoryName": null,
[7/7/2020 6:23:44 AM]       "LogLevel": "None",
[7/7/2020 6:23:44 AM]       "Filter": null
[7/7/2020 6:23:44 AM]     },
[7/7/2020 6:23:44 AM]     {
[7/7/2020 6:23:44 AM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[7/7/2020 6:23:44 AM]       "CategoryName": null,
[7/7/2020 6:23:44 AM]       "LogLevel": null,
[7/7/2020 6:23:44 AM]       "Filter": "<AddFilter>b__0"
[7/7/2020 6:23:44 AM]     }
[7/7/2020 6:23:44 AM]   ]
[7/7/2020 6:23:44 AM] }
[7/7/2020 6:23:44 AM] FunctionResultAggregatorOptions
[7/7/2020 6:23:44 AM] {
[7/7/2020 6:23:44 AM]   "BatchSize": 1000,
[7/7/2020 6:23:44 AM]   "FlushTimeout": "00:00:30",
[7/7/2020 6:23:44 AM]   "IsEnabled": true
[7/7/2020 6:23:44 AM] }
[7/7/2020 6:23:44 AM] SingletonOptions
[7/7/2020 6:23:44 AM] {
[7/7/2020 6:23:44 AM]   "LockPeriod": "00:00:15",
[7/7/2020 6:23:44 AM]   "ListenerLockPeriod": "00:00:15",
[7/7/2020 6:23:44 AM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[7/7/2020 6:23:44 AM]   "LockAcquisitionPollingInterval": "00:00:05",
[7/7/2020 6:23:44 AM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[7/7/2020 6:23:44 AM] }
[7/7/2020 6:23:44 AM] HttpOptions
[7/7/2020 6:23:44 AM] {
[7/7/2020 6:23:44 AM]   "DynamicThrottlesEnabled": false,
[7/7/2020 6:23:44 AM]   "MaxConcurrentRequests": -1,
[7/7/2020 6:23:44 AM]   "MaxOutstandingRequests": -1,
[7/7/2020 6:23:44 AM]   "RoutePrefix": "api"
[7/7/2020 6:23:44 AM] }
[7/7/2020 6:23:44 AM] Starting JobHost
[7/7/2020 6:23:44 AM] Starting Host (HostId=minintm5vmq69-626848009, InstanceId=0c320548-2786-44e7-ab2b-ae619295388e, Version=3.0.13901.0, ProcessId=3080, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[7/7/2020 6:23:44 AM] Loading functions metadata
[7/7/2020 6:23:44 AM] Reading functions metadata
[7/7/2020 6:23:44 AM] 0 functions found
[7/7/2020 6:23:44 AM] 0 functions loaded
[7/7/2020 6:23:44 AM] Generating 0 job function(s)
[7/7/2020 6:23:44 AM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[7/7/2020 6:23:44 AM] Initializing function HTTP routes
[7/7/2020 6:23:44 AM] No HTTP routes mapped
[7/7/2020 6:23:44 AM] 
[7/7/2020 6:23:44 AM] Host initialized (260ms)
[7/7/2020 6:23:44 AM] Host started (291ms)
[7/7/2020 6:23:44 AM] Job host started
Hosting environment: Production
Content root path: /Users/azuretest/Desktop/serene/project/cs/bin/Debug/netcoreapp3.1
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[7/7/2020 6:23:49 AM] Host lock lease acquired by instance ID '000000000000000000000000731AF69C'.

**More Info:**
This issue does not reproduce for JavaScript/TypeScript/Python/PowerShell project.

**Comment by EricJizbaMSFT** [comment] 2020-07-13 17:33
Likely dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2196, which is fixed in the latest versions of VS Code

**Closed by EricJizbaMSFT** 2020-07-13 17:33 UTC
Labels: AT-CTI
