### ISSUE TITLE
"Could not load template" after updating extension

### ISSUE THREAD

**Issue by phanthoa** [Microsoft/vscode-azurefunctions#659] opened 2018-09-25 07:22 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\thoapv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.2\resources\dotnetJsonCli\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\thoapv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.2\resources\dotnetTemplates\itemTemplates-beta.nupkg" --require "c:\Users\thoapv\.vscode\extensions\ms-azuretools.vscode-azurefunctions-0.10.2\resources\dotnetTemplates\projectTemplates-beta.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.2.x --arg:name "TSDVTestFuncion" --arg:AzureFunctionsVersion v2" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null
}

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-10-17 18:13
Sorry for the delayed response. Can you give us a little more info? For example:
1. Does this always happen for you?
1. Do the file paths listed in the "--require" above actually exist?

**Comment by firebellys** [comment] 2018-11-26 23:02
This started happening for me as well. It happens every time (repeatable) and I have all those required files. I've made dozens of functions on this machine recently too, so this is not expected.

&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.createFunction
Error type: Error
Error Message: Command "dotnet '/Users/eumenhofer/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.12.1/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/eumenhofer/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.12.1/resources/dotnetTemplates/itemTemplates-~2.nupkg' --require '/Users/eumenhofer/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.12.1/resources/dotnetTemplates/projectTemplates-~2.nupkg' --operation create --identity Azure.Function.CSharp.QueueTrigger.2.x --arg:name 'TestOp' --arg:namespace 'Company.Function' --arg:Connection 'AzureWebJobsStorage' --arg:QueueName 'myqueue-items'" failed with exit code "6":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "QueueTrigger",
  "ResultInfo": null,
  "OutputBaseDirectory": null
}


Version: 0.12.1
OS: darwin

**Comment by firebellys** [comment] 2018-11-29 18:51
I have tried uninstalling and reinstalling the extension as well and still can't make any new functions. The runtime works, and I can debug without issue, but creating new functions is no longer working at all.

**Comment by EricJizbaMSFT** [comment] 2018-11-29 18:54
@firebellys how did you uninstall? Sometimes it doesn't *actually* uninstall everything. Can you try the following:
1. Go to `/Users/eumenhofer/.vscode/extensions/` and delete all `ms-azuretools.vscode-azurefunctions-*` folders
1. Re-install

**Comment by firebellys** [comment] 2018-11-30 19:01
That fixed it! If it happens again, I'll compress the folder and send it over you can investigate. Thanks!

**Comment by EricJizbaMSFT** [comment] 2018-11-30 22:50
@firebellys glad that worked for you. Also thanks for adding to the issue. It seems this issue may be related to when you update the extension - which could help me find the root cause

**Comment by EricJizbaMSFT** [comment] 2019-02-21 23:13
Closing this as won't fix. Seems like you had a workaround and the cause may not be on our side. We can re-investigate if more people keep having this problem

**Closed by EricJizbaMSFT** 2019-02-21 23:13 UTC
Labels: P1, bug
