### ISSUE TITLE
An error "Failed to attach to process: Unknown Error: 0x80131c3c" occurs when debugging a .NET 6.0 LTS project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#3251] opened 2022-07-19 02:31 UTC
**OS:** M1(Pro)
**Build Version:** 20220715.7

**Repro Steps:**
1. Create a C# project with the **.NET 6.0 LTS** runtime.  
2. Open the C# project in VS Code -> Debug it.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/179647474-bbe2e243-c0d2-40a0-bfec-fb62c843b0c9.png)

**More Info:**
This issue doesn't reproduce for C# projects created with other runtimes.

**Comment by nturinski** [comment] 2022-07-21 22:24
Could you try this again? Maybe the staging templates were messing something up. It seems to be working okay on my machine.

![image](https://user-images.githubusercontent.com/5290572/180325109-67c1c8b1-fb3a-476b-9c1b-88625ec43d47.png)

![image](https://user-images.githubusercontent.com/5290572/180325183-caf10ece-56e5-4df1-8938-04d52b897867.png)

**Comment by v-xinda** [comment] 2022-07-22 01:50
@nturinski  This issue still reproduces on **Mac(Pro)**. This issue doesn't reproduce on Windows.
I set the "Azure Functions: Template Source" setting with "**Default**" and the dotnet version is **6.0.302**. 
![image](https://user-images.githubusercontent.com/57662131/180344068-f30ddee2-d05c-45c7-8672-62d8c4c729ac.png)
![image](https://user-images.githubusercontent.com/57662131/180344177-76c497be-b2ed-4ee7-86d8-0089e2020645.png)

**Comment by MicroFish91** [comment] 2022-08-25 22:41
Hi, we have tried reproducing this on Mac and have been unsuccessful.  We will be closing this out as unable to repro.  If you can provide additional information showing how you are producing this error we can reopen

**Closed by MicroFish91** 2022-08-25 22:41 UTC
Labels: AT-CTI, debugging
