### ISSUE TITLE
Problem when deploying function app

### ISSUE THREAD

**Issue by LaiHoangLe** [microsoft/vscode-azurefunctions#1446] opened 2019-08-15 10:46 UTC
Repro steps:

I tried to deploy an Azure Function App but can not do it. Please help me.
Thank in advance

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: Encountered an error (Forbidden) from extensions API.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-08-19 23:02
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1282

**Closed by EricJizbaMSFT** 2019-08-19 23:02 UTC
