### ISSUE TITLE
Storage binding does not create a new app setting

### ISSUE THREAD

**Issue by asavaritayal** [Microsoft/vscode-azurefunctions#1226] opened 2019-04-25 23:45 UTC
[Functions_localdev.mp4.zip](https://github.com/Microsoft/vscode-azurefunctions/files/3119208/Functions_localdev.mp4.zip)

Please see attached file for the exact repro steps. On a high level, when a user creates a new function using the Blob trigger template and they decide to create a new storage account for it, the account gets created but no new application setting is registered in the local settings and function.json configuration. User is required to manually configure this.

**Comment by EricJizbaMSFT** [comment] 2019-04-25 23:49
@asavaritayal this has already been fixed

Duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/1137

**Closed by EricJizbaMSFT** 2019-04-25 23:49 UTC
