### ISSUE TITLE
DISCUSSION: Exposing stubbing for input bindings for functions while debugging on VS Code

### ISSUE THREAD

**Issue by ijoosong** [microsoft/vscode-azurefunctions#2346] opened 2020-08-27 18:49 UTC
Currently, there is a way to quickly stub input bindings as well as trigger functions when debugging locally but that visibility is very low.  Not a lot of people are aware this is a new feature.  What are some ways we can expose this feature to customers?

**Comment by EricJizbaMSFT** [comment] 2020-09-14 22:12
We're open to any suggestions you have. Users can right click in the "functions.json" file, on a function in the "Local Project" tree view, or use the command palette. Those are our most common entry points for a feature like this, and I don't think it's worth something as in-your-face as a button in the ribbon

**Comment by ejizba** [comment] 2021-01-26 20:44
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2641

**Closed by ejizba** 2021-01-26 20:44 UTC
Labels: needs design
