### ISSUE TITLE
[Feature Request] Reattach Debugger After File Changes

### ISSUE THREAD

**Issue by Hazhzeng** [microsoft/vscode-azurefunctions#2637] opened 2021-01-26 02:12 UTC
### Rationale

**This feature request is for the interpreted language only (python, nodejs, powershell)**

As the function host already support soft restart to reload customer's code, we can leverage this feature and enable a seamless experience for customer's to debug function code locally, without the need of exiting the host.

### Current Behavior
1. Python, Node or PowerShell developers hit F5 in vscode.
2. The function host should start and the debugger attaches.
3. Now, the customer modify the .py, .js, .ps1 files and save.
4. The host reload the new code, the debugger detaches, host exits gracefully.

### Expected Behavior
1. Python, Node or PowerShell developers hit F5 in vscode.
2. The function host should start and the debugger attaches.
3. Now, the customer modify the .py, .js, .ps1 files and save.
4. **The debugger detached, waiting for function host to soft restart, with the new customer's code in it.**
5. **Once the host completely restarts, reattach the debugger.**

Let me know if there's any blockers or technical difficulties.

/cc: @mhoeger @stefanushinardi @AnatoliB @fabiocav

**Comment by ejizba** [comment] 2021-01-26 19:25
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/781

**Closed by ejizba** 2021-01-26 19:25 UTC
