### ISSUE TITLE
Worst service of Azure function deployment

### ISSUE THREAD

**Issue by rahulmodu** [microsoft/vscode-azurefunctions#2321] opened 2020-08-20 09:08 UTC
I am sick of the service of Azure function deployment. Every time I am facing too much problem  to deploy the function

**Comment by EricJizbaMSFT** [comment] 2020-08-24 16:43
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2318

**Closed by EricJizbaMSFT** 2020-08-24 16:43 UTC
