### ISSUE TITLE
Error trying to deploy my function

### ISSUE THREAD

**Issue by MarluanEspiritusanto** [microsoft/vscode-azurefunctions#2037] opened 2020-04-15 15:55 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Error
Error Message: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

Version: 0.22.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:281:30759
fulfilled extension.bundle.js:281:29077
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment] 2020-04-15 17:57
Closing as a dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1983

As Eric mentioned in that thread...

> If you want a different workaround, I've added a setting to disable this validation:
>  "azureFunctions.suppressMd5Validation": true
> It won't be released for a bit, but you can install [this insiders build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17165&view=results) with [these instructions](https://aka.ms/azcodeinsiders) to get it early.

**Closed by nturinski** 2020-04-15 17:57 UTC
