### ISSUE TITLE
Azure function deploy from vscode fails with error

### ISSUE THREAD

**Issue by z424brave** [Microsoft/vscode-azurefunctions#642] opened 2018-09-23 11:07 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
Create a function in vscode and attempt to deploy to Azure

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-09-24 15:05
Thanks for filing - there may have been an outage in Azure Functions. In any case, closing as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/645 for further investigation

**Closed by EricJizbaMSFT** 2018-09-24 15:05 UTC
