### ISSUE TITLE
ECONNRESET error when try to upload a function via Azure Functions

### ISSUE THREAD

**Issue by hypeitnow** [microsoft/vscode-azurefunctions#2393] opened 2020-09-17 13:37 UTC
Does this occur consistently? 
Repro steps:

1. Create an azure function in VS Code
2. Make the required changed in init.py
3. Deploy to Function App from VS Code.

Action: azureFunctions.deploy
Error type: ECONNRESET
Error Message: request to https://mkitestapp2.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.24.0
OS: linux
OS Release: 5.4.0-1025-azure
Product: Visual Studio Code
Product Version: 1.48.2
Language: en-US

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:205:15
TLSSocket.socketErrorListener _http_client.js:402:9
TLSSocket.emit events.js:200:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-09-21 20:45
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2390

**Closed by EricJizbaMSFT** 2020-09-21 20:45 UTC
