### ISSUE TITLE
Function app deployment not working with latest extension version 

### ISSUE THREAD

**Issue by BalakumaranGunasekaran** [microsoft/vscode-azurefunctions#3096] opened 2022-04-04 15:43 UTC
We tried to deploy azure linux function app with vscode which failed with below error.After downgrading the azure extension version in vscode to 1.2.1 resolved the issue.

11:47:13 : Starting deployment...
11:47:14 : Creating zip package...
11:47:33 : Zip package size: 172 MB
11:52:18: Error: request to https://****.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET;

**Comment by klodha** [comment] 2022-04-05 05:52
Duplicate of #3094 and #2844. Quick solution: Downgrade to Feb 2022 release of VSCode (https://code.visualstudio.com/updates/v1_65) and it will work fine. You can disable auto-update to "none" in preferences to ensure that VSCode doesn't get upgraded automatically.

**Comment by alexweininger** [comment] 2022-04-05 20:09
Closing as duplicate of #2844 

Until a fix is released in VS Code stable (hopefully the next major release), here are some options:
1. Wait for the fix to come in [VS Code Insiders](https://code.visualstudio.com/insiders/)
2. [Deploy via Azure CLI](https://github.com/microsoft/vscode-azurefunctions/issues/2844#issuecomment-1086259916)
3. Downgrade to the [VS Code February 2022 release](https://code.visualstudio.com/updates/v1_65), where zip deploy is working

**Closed by alexweininger** 2022-04-05 20:09 UTC

**Comment by alexweininger** [comment] 2022-04-13 19:19
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension.
