### ISSUE TITLE
ServiceUnavailable from host runtime - error

### ISSUE THREAD

**Issue by kavithamadhavaraj** [Microsoft/vscode-azurefunctions#971] opened 2019-02-07 14:01 UTC
Could not deploy the project to Azure Functions

Repro steps:
Try to deploy a default HTTPTrigger template from VSCode, Linux Consumption Plan, West Europe

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (ServiceUnavailable) from host runtime.

Version: 0.13.1
OS: linux

**Comment by EricJizbaMSFT** [comment] 2019-02-07 19:41
@kavithamadhavaraj we've done some work recently to mitigate this so I'll close as a duplicate of that. For example: https://github.com/Microsoft/vscode-azuretools/pull/372

We plan to release soon, but you're welcome to try earlier if you want:
How to install: https://aka.ms/azCodeInsiders
Build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2905

NOTE: This relies on VS Code v1.31.0 just released yesterday

**Closed by EricJizbaMSFT** 2019-02-07 19:41 UTC
