### ISSUE TITLE
Unable to deploy my Python function

### ISSUE THREAD

**Issue by RonnyA** [microsoft/vscode-azurefunctions#1282] opened 2019-05-16 14:39 UTC
Repro steps:

1. Create a new Python app like this https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python
2.  Deploy using "Up arrow " (deploy to function app)
3.  Fail during upload to storage

Deploying using "func" works great
> func azure functionapp publish <APP_NAME>

Action: azureFunctions.deploy
Error type: Forbidden
Error Message: Forbidden

Version: 0.17.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

Creating new function app "hgfuifgheiui"...
Created new function app "hgfuifgheiui": https://hgfuifgheiui.azurewebsites.net

15:17:35 hgfuifgheiui: Starting deployment...
15:17:37 hgfuifgheiui: Uploading zip package to storage container...
Error: Forbidden
16:30:06 hgfuifgheiui: Starting deployment...
16:30:11 hgfuifgheiui: Uploading zip package to storage container...
Error: Forbidden

```
Function.module.exports.j._normalizeError extension.bundle.js:332:65127
Object.module.exports.j._processResponse extension.bundle.js:332:60937
$.h [as _callback] extension.bundle.js:332:54789
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-05-20 23:02
@RonnyA can't repro this myself, but got a few questions for ya:
- When you say "Deploying using "func" works great" - how did you create the function app? Was that the same function app that you created from VS Code? Or did you create it from the portal?
- Can you try creating a function app through the portal - and then deploying through VS Code? (Just trying to determine if we created the function app incorrectly or if we're deploying incorrectly)
- Do you have any special restrictions on your subscription?
- Have you tried to deploy to your function app since you ran into this message? I wonder if the storage account or function app wasn't fully "initialized" right after creation

**Comment by toddpenland** [comment] 2019-06-04 23:07
Hi @EricJizbaMSFT,

I followed the same exact steps as @RonnyA and encountered pretty much the same issues. Here's a bit more detail:

Following the tutorial, I attempted to deploy from VS Code using the "Up Arrow" as Ronny mentioned. It created the Azure resources and got to the step of zipping up the function, and that's when I got a popup saying simply "Forbidden" and under it Source: Azure Functions (Extension).  

Unlike Ronny, I got no call stack or other useful information.  I did confirm that the zip file was created so the failure was subsequent to that step.

I tried several more times, wating a few minutes between each and received the same error each time.

From within VS Code, I then simply opened the terminal to get a command prompt and used the CLI  "func" command Ronny listed above to deploy the tutorial app to the same function app service that was previously created. It loaded with no problem and I confirmed the function worked properly.

I then tried to deploy again using the funciton tooling (up arrow) and still got Forbidden.

I tried this in 2 different subscriptions, both of which I have role of Account Admin.

Let me know if there are any logs or other info that would help.

**Comment by EricJizbaMSFT** [comment] 2019-06-06 22:20
@toddpenland thanks for the info - we'll look into it

**Comment by gregoryfinn65** [comment] 2019-08-15 15:34
![image](https://user-images.githubusercontent.com/53275726/63106170-448eaa00-bf50-11e9-806a-18885e1dbae1.png)

@EricJizbaMSFT  Is this the same issue? 


> Repro steps:
> 
> 1. Create a new Python app like this https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python
> 2. Deploy using "Up arrow " (deploy to function app)
> 3. Fail during upload to storage
> 
> Deploying using "func" works great
> 
> > func azure functionapp publish <APP_NAME>
> 
> Action: azureFunctions.deploy
> Error type: Forbidden
> Error Message: Forbidden
> 
> Version: 0.17.0
> OS: win32
> Product: Visual Studio Code
> Product Version: 1.33.1
> Language: en
> 
> Call Stack

**Comment by EricJizbaMSFT** [comment] 2019-08-19 23:05
Can you guys try deploying again with v0.18.0 of the extension (released today) and let me know if you see any difference? We included a few changes related to the [recent GA announcement](https://twitter.com/AzureFunctions/status/1163511532417765376) of Python and Linux consumption which might have helped

**Comment by rcarmo** [comment] 2019-08-20 20:26
Hmmm. I was just trying out the new extension and ended up filing #1457, but now that I recall I also got a “Forbidden” when trying non-git deployment.

**Comment by EricJizbaMSFT** [comment] 2019-10-03 00:49
Closing this since remote build will be the default soon (#1541). You can try it out with these instructions: https://github.com/microsoft/vscode-azurefunctions/wiki/Server-Side-Build

**Closed by EricJizbaMSFT** 2019-10-03 00:49 UTC
Labels: P2, bug
