### ISSUE TITLE
VS Code deploy error when deploying to Linux 

### ISSUE THREAD

**Issue by StephaneBischoff** [Microsoft/vscode-azurefunctions#977] opened 2019-02-08 14:44 UTC
Repro steps:
Trying to deploy from VS Code into already existing Azure Function App which is running on a App Service Plan with a Linux machine. Yet, receiving this error message from the deploy in VS Code.

Action: azureFunctions.deploy
Error type: Error
Error Message: Python projects are not supported on Windows Function apps.  Deploy to a Linux Consumption app.

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment] 2019-02-08 20:29
Looks like a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/906 or https://github.com/Microsoft/vscode-azurefunctions/issues/893

We've fixed on master and plan to release soon, but you're welcome to try earlier:
How to install: https://aka.ms/azCodeInsiders
Build: https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2905

**Closed by EricJizbaMSFT** 2019-02-08 20:29 UTC

**Comment by ikendall** [comment] 2019-02-08 20:56
Hi Eric,

That works, thanks. Look forward to the full release.

Ian
