### ISSUE TITLE
Negociate

### ISSUE THREAD

**Issue by AlexSouzaSantos** [microsoft/vscode-azurefunctions#2363] opened 2020-09-06 12:18 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.createFunction
Error type: Error
Error Message: Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again.

Version: 0.24.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
D.reject workbench.desktop.main.js:5545:245
file:/workbench.desktop.main.js:5549:267
async D.doWriteConfiguration workbench.desktop.main.js:5542:403
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-09-12 00:29
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2364

**Closed by EricJizbaMSFT** 2020-09-12 00:29 UTC
