### ISSUE TITLE
Unexpected token } when creating new C# Project

### ISSUE THREAD

**Issue by adamjohnstonarm** [microsoft/vscode-azurefunctions#2999] opened 2021-11-09 09:21 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-azurefunctions`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.62.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 489,
		"activateCallTime": 21,
		"activateResolvedTime": 70,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-azuretools.vscode-azurefunctions",
				"_lower": "ms-azuretools.vscode-azurefunctions"
			},
			"activationEvent": "onView:azFuncTree"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Repro Steps:**
- Select `Create New Project`
- Select any empty folder
- Select `C#`

**Expected:**
- Developer should be presented with list of C# runtimes

**Actual:**
- Error: Error "SyntaxError: Unexpected token } in JSON at position 205943" occurred while parsing the response body

JSON content below. Note the spurious `,` at position 205938

[cli-feed-v4.json](https://github.com/microsoft/vscode-azurefunctions/files/7506093/cli-feed-v4.txt)

edit: Hi! thanks for your issue report. I edited your comment to change the pasted JSON to a file. The pasted JSON was long and making the page unresponsive for me. Hope you don't mind :)

**Comment by tommck** [comment] 2021-11-09 14:04
I just created a bug in the wrong repo for this exact thing. Especially sucks for me because I'm preparing to demo a bunch of this stuff at a conference in 10 days :)

**Comment by adamjohnstonarm** [comment] 2021-11-09 14:09
To be fair @tommck, I'm not clear whether this is an extension bug or a bug in the Azure APIs. Out of curiosity, where did you create the bug?

**Comment by adamjohnstonarm** [comment] 2021-11-09 14:12
To be fair @tommck, I'm not clear whether this is a bug in the extension, or a bug in the Azure API. I can't tell where the response is coming from.

**Comment by tommck** [comment] 2021-11-09 14:31
Yes, it's highly possible that it's in the API

**Comment by tommck** [comment] 2021-11-09 14:42
@adamjohnstonarm It's linked here.. has a video as well.. I did it in the "function host" by mistake

**Comment by tommck** [comment] 2021-11-09 15:00
@adamjohnstonarm yep... if you hit this URL, the JSON is invalid... https://functionscdn.azureedge.net/public/cli-feed-v4.json (that's the URL the code uses)

**Comment by alexweininger** [comment] 2021-11-09 15:47
File in question, linked to the errant comma: https://github.com/Azure/azure-functions-tooling-feed/blob/main/cli-feed-v4.json#L4878

I've created an issue on the appropriate repo: https://github.com/Azure/azure-functions-tooling-feed/issues/315

**Comment by alexweininger** [comment] 2021-11-09 15:53
@tommck @adamjohnstonarm this issue has been fixed and the API now returns a valid JSON response. It looks like the issue is fixed on my end, could you verify it's fixed for you? Thanks!

**Comment by tommck** [comment] 2021-11-09 15:59
@alexweininger yes, it is!  thank you!

**Comment by alexweininger** [comment] 2021-11-09 16:01
> @alexweininger yes, it is! thank you!

Awesome, thanks for the detailed issue report from both of you.

**Closed by alexweininger** 2021-11-09 16:01 UTC

**Comment by adamjohnstonarm** [comment] 2021-11-09 16:05
Thanks for the quick turnaround! Unfortunately I can't verify yet as the feed still seems to serving the old file (to me at least)

**Comment by alexweininger** [comment] 2021-11-09 16:08
> Thanks for the quick turnaround! Unfortunately I can't verify yet as the feed still seems to serving the old file (to me at least)

Ok, that could be due to some CDN caching. It might be another hour until it gets updated on all CDNs. If it's still not working after an hour or so, comment and I will reopen the issue.

**Comment by alexweininger** [comment] 2021-11-09 16:30
We could use something like https://json5.org/ to avoid issues like this in the future. JSON5 has support for parsing JSON with extra commas.
