### ISSUE TITLE
Azure functions .NET 7 support for VS Code extension 

### ISSUE THREAD

**Issue by cloudmelon** [microsoft/vscode-azurefunctions#3243] opened 2022-07-13 20:52 UTC
I CAN create an Azure function .NET 7 in an isolated process through VS Code extension. 

Related work item : 
[.NET 7.0 support isolated for AF v4](https://github.com/Azure/azure-functions-dotnet-worker/issues/823)

cc @nturinski

**Comment by nturinski** [comment] 2022-08-02 21:39
Closing as the templates were released and .NET 7 seems to be working.

**Comment by jorgelevy** [comment] 2022-08-02 22:34
I'm still seeing Net6

![image](https://user-images.githubusercontent.com/875747/182483064-c58c0d3c-2cc7-4209-9fd2-b47cec7966be.png)

VS Code Insiders: 1.70.0-insider
Azure Function Core Tools: 4.0.4670
.NET DSK: 7.0.100-preview.6.22352.1
Node.js: 16.13.2
OS: Win11 insiders 10.0.25169

**Comment by nturinski** [comment] 2022-08-02 23:53
You don't see `.NET 7.0 (isolated)` as a choice when you creating a new project?

![image](https://user-images.githubusercontent.com/5290572/182495951-3212eb7d-2131-45f3-abcd-b0c7edb5c993.png)

Or even when you select .NET 7.0, it's still creating a .NET 6 project?

**Comment by jorgelevy** [comment] 2022-08-02 23:56
I see the option for '.NET 7.0 Isolated', but the generated code come as .NET 6.

**Comment by nturinski** [comment] 2022-08-03 00:12
Weird, I'll look into this. I'm able to reproduce this, but I have an old test project with the proper TargetFramework.

![image](https://user-images.githubusercontent.com/5290572/182497578-184b3897-f656-4b44-8e38-0482783bd6a6.png)

Maybe the templates were updated?

**Comment by nturinski** [comment] 2022-08-04 18:40
Fixed by https://github.com/microsoft/vscode-azurefunctions/pull/3273

Until this gets released in the wild, I think if you just manually change the TargetFramework to `net7.0` and build it should work.  The templates being served were correct, but we weren't passing a parameter to generate the proper `csproj` file.

**Closed by nturinski** 2022-08-04 18:40 UTC

**Comment by cloudmelon** [comment] 2022-08-15 17:33
> Fixed by #3273
> 
> Until this gets released in the wild, I think if you just manually change the TargetFramework to `net7.0` and build it should work. The templates being served were correct, but we weren't passing a parameter to generate the proper `csproj` file.

Hi @nturinski there was another item related to this and the team had fixed that in sprint 126, I will follow up on the stack API :).
