### ISSUE TITLE
Improve basic create experience when user doesn't have access to create resource group

### ISSUE THREAD

**Issue by IonutCristianBistriceanu** [microsoft/vscode-azurefunctions#1194] opened 2019-04-17 08:35 UTC
Repro steps:1.2.Action: azureFunctions.createFunctionAppError type: 403Error Message: Failed with code 403.Version: 0.16.0OS: win32VS Code Version: 1.32.3<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment] 2019-04-17 15:29
@IonutCristianBistriceanu please post repro steps for your issue

**Comment by IonutCristianBistriceanu** [comment] 2019-04-17 18:04
@EricJizbaMSFT 
Repro steps:


1.2.Action: azureFunctions.deployError type: 403Error Message: Failed with code 403.Version: 0.16.0OS: win32VS Code Version: 1.32.3<details><summary>Call Stack</summary>```module.exports.o.pipeline (dist/extension.bundle.js:277:500927)s (dist/extension.bundle.js:277:110820)s (dist/extension.bundle.js:165:25754)dist/extension.bundle.js:165:26994o (dist/extension.bundle.js:223:7055)dist/extension.bundle.js:165:24675$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:579051)$.module.exports.$.init.t._callback.t.callback.t.callback [as callback] (dist/extension.bundle.js:253:5461)$.emit (events.js:182:13)$.<anonymous> (dist/extension.bundle.js:253:18274)$.emit (events.js:187:15)IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)Object.onceWrapper (events.js:273:13)IncomingMessage.emit (events.js:187:15)endReadableNT (_stream_readable.js:1090:12)process._tickCallback (internal/process/next_tick.js:63:19)```</details>

**Comment by EricJizbaMSFT** [comment] 2019-04-17 18:22
Thanks for the info - can you try setting `azureFunctions.advancedCreation` to `true` in your VS Code settings and trying again? That will prompt you for more values and it might help me figure out exactly which step is failing

**Comment by IonutCristianBistriceanu** [comment] 2019-04-17 18:29
I have changed the azureFunctions.advancedCreation setting to true and tried again. I got asked for the additional info like OS, storage and resource group I think. I also managed to deploy the application and checked it in portal.azure.com.It is working fine now. Let me know if you need me to do anything more.

@EricJizbaMSFT

**Comment by EricJizbaMSFT** [comment] 2019-04-17 18:34
Can you let me know what OS, runtime and region you selected when creating the function app? And what language your local project is? Could be our defaults aren't working in your case.

**Comment by IonutCristianBistriceanu** [comment] 2019-04-17 18:47
OS: Windows
Runtime: .NET
Region: West Europe

**Comment by EricJizbaMSFT** [comment] 2019-04-17 18:51
Interesting... can you do me a favor and try deploying to the West US region? That's our default and I'm wondering if you don't have access to that region for some reason (or if that region has an outage or something).

**Comment by IonutCristianBistriceanu** [comment] 2019-04-17 19:20
Unfortunately I can't create a new resource group since I don't have permission.(Company owned account).

**Comment by EricJizbaMSFT** [comment] 2019-04-17 20:32
Ah that would explain it - so you must've selected an existing resource group when you used advanced creation?

**Comment by IonutCristianBistriceanu** [comment] 2019-04-17 21:15
Yes, I selected an existing resource group.

**Comment by EricJizbaMSFT** [comment] 2019-07-19 21:01
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1317

**Closed by EricJizbaMSFT** 2019-07-19 21:01 UTC
Labels: P2, bug
