### ISSUE TITLE
report

### ISSUE THREAD

**Issue by VivekaR18** [microsoft/vscode-azurefunctions#1531] opened 2019-10-01 05:37 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: 409
Error Message: Run-From-Zip is set to a remote URL using WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.

Version: 0.18.1
OS: linux
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline extension.bundle.js:331:748337
s extension.bundle.js:218:110861
s extension.bundle.js:164:25754
extension.bundle.js:164:26994
o extension.bundle.js:164:644607
extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:626220
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5443
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18256
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:194:17098
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-10-01 15:34
@VivekaR18 please add repro steps, including how you create the function app in azure

**Comment by VivekaR18** [comment] 2019-10-03 05:36
Create a function app in azure portal. To upload the python code into the function app, the VSCode is used. Download the appropriate packages for azure and link your azure account with VSCode. Create a function in VSCode using Triggers like HttpTrigger, TimerTrigger. Upload the created folder to the azure function app in VSCode.

**Comment by EricJizbaMSFT** [comment] 2019-11-21 22:09
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1684

**Closed by EricJizbaMSFT** 2019-11-21 22:09 UTC
Labels: needs more info
