### ISSUE TITLE
Functions 3.x Changes

### ISSUE THREAD

**Issue by ColbyTresness** [microsoft/vscode-azurefunctions#1546] opened 2019-10-03 23:56 UTC
Per email:

•	Whenever anyone opens the extension, check their core tools version
•	If V3, use V3, if V1, use V1. Nothing complex here
•	If V2, show info bubble about V3, with a forward link to a doc explaining how to update and the differences V3 provides. Until customer manually updates core tools version, use V2.
•	Allow customers to preview V3 alongside V2 if they wish by leveraging dev containers. The doc referenced above should contain a link to instructions on how to set this up.

**Comment by EricJizbaMSFT** [comment] 2019-10-21 20:11
Closing as dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1489

**Closed by EricJizbaMSFT** 2019-10-21 20:11 UTC
