### ISSUE TITLE
Issue: Python azure function plugin creates wrong folder structure

### ISSUE THREAD

**Issue by ecc256** [microsoft/vscode-azurefunctions#2178] opened 2020-06-24 01:56 UTC
Azure Functions [developer guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#programming-model) describes recommended folder structure for a Python Functions project.
But following [tutorial](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01) creates different folder structure.
It won't allow [Unit Testing](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python#unit-testing) as part of the same project.

Could somebody explain, how configure azure function plugin to generate recommended folder structure, please?
Thanks

**Comment by anthonychu** [comment] 2020-06-29 06:42
@Hazhzeng is working on a new folder structure that works with tests as well as imports and intellisense. We'll be updating the guidance in the near future and make any adjustments to tooling as needed. /cc @anirudhgarg

**Comment by EricJizbaMSFT** [comment] 2020-06-29 21:27
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1970

**Closed by EricJizbaMSFT** 2020-06-29 21:27 UTC
