### ISSUE TITLE
Error when clicking on function.json

### ISSUE THREAD

**Issue by jreid143** [microsoft/vscode-azurefunctions#2502] opened 2020-10-30 15:14 UTC
Does this occur consistently? Yes
Repro steps:

1. Just clicking on function.json from VSCode in a function in Azure
2.

Action: azureFunctions.openFile
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿{
  "bindings": [
    {
      "authLevel": "function",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    },
    {
      "name": "outputDocument",
      "direction": "out",
      "type": "cosmosDB",
      "databaseName": "outDatabase",
      "collectionName": "MyCollection",
      "connectionStringSetting": "jir-test-cosmosdb_DOCUMENTDB"
    }
  ]
}.

Version: 1.0.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:110341
errorHandler extension.bundle.js:48:165914
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-10-30 16:48
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2490

**Closed by EricJizbaMSFT** 2020-10-30 16:48 UTC
