### ISSUE TITLE
VS Code Azure Functions Extension Python deployment workflow fails with "Failed to deploy path that does not exist"

### ISSUE THREAD

**Issue by gbowerman** [microsoft/vscode-azurefunctions#1336] opened 2019-06-07 23:37 UTC
VS Code Functions extension on Windows 0.17.1 fails deploying a Python function with an error that it cannot find a zipfile..
![zipfile](https://user-images.githubusercontent.com/4258913/59138532-81339900-8942-11e9-930e-07d1c63a0310.png)

**Comment by gbowerman** [comment] 2019-06-07 23:48
Possible dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1329

**Comment by EricJizbaMSFT** [comment] 2019-06-10 16:28
I'm guessing you selected "Deploy anyway" after the dialog in https://github.com/microsoft/vscode-azurefunctions/issues/1335

The "func: pack" task creates that zip, so it makes sense that it doesn't exist if that task failed. We're kind of in a catch 22 here because we don't want to block deploy if a pre-deploy task fails, but many times the pre-deploy task is required. Users can set the pre-deploy task to anything, including any arbitrary shell task. For example, TypeScript users might set it to a "build" and "lint" task and it could make complete sense to "Deploy Anyway" if just the lint task fails.

**Comment by gbowerman** [comment] 2019-07-10 23:42
For this particular workflow, I either don't want the option of Deploy anyway, or if you have to provide that option - warn me that a deployment will fail if I select it.

**Comment by EricJizbaMSFT** [comment] 2019-07-17 17:26
We don't want to get rid of "Deploy Anyway" - it's modeled after "Debug Anyway" which I think is a very common pattern that most users are familiar with. In that sense, closing as "by design"

We already have https://github.com/microsoft/vscode-azurefunctions/issues/1335 to track improvements to the "Deploy anyway" dialog. In that sense, closing as "duplicate"

**Closed by EricJizbaMSFT** 2019-07-17 17:26 UTC
Labels: needs more info
