### ISSUE TITLE
Debugger unable to find func to enable debugging

### ISSUE THREAD

**Issue by james2432** [microsoft/vscode-azurefunctions#3293] opened 2022-08-23 11:17 UTC
Launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to .NET Functions",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}" //work around, need to look for func and attach debugger to it
            //"processId": "${command:azureFunctions.pickProcess}"  //Azure function times out trying to find the func process
        }
    ]
}
```

tasks.json:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "clean (functions)",
			"command": "dotnet",
			"args": [
				"clean",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"problemMatcher": "$msCompile",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"label": "build (functions)",
			"command": "dotnet",
			"args": [
				"build",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"dependsOn": "clean (functions)",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": "$msCompile",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"label": "clean release (functions)",
			"command": "dotnet",
			"args": [
				"clean",
				"--configuration",
				"Release",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"problemMatcher": "$msCompile",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"label": "publish (functions)",
			"command": "dotnet",
			"args": [
				"publish",
				"--configuration",
				"Release",
				"/property:GenerateFullPaths=true",
				"/consoleloggerparameters:NoSummary"
			],
			"type": "process",
			"dependsOn": "clean release (functions)",
			"problemMatcher": "$msCompile",
			"options": {
				"cwd": "${workspaceFolder}/api"
			}
		},
		{
			"type": "func",
			"dependsOn": "build (functions)",
			"options": {
				"cwd": "${workspaceFolder}/api/bin/Debug/net6.0"
			},
			"command": "host start --csharp",
			"isBackground": true,
			"problemMatcher": "$func-dotnet-watch"
		}
	]
}
```

settings.json:
```
{
    "azureFunctions.deploySubpath": "api/bin/Release/net6.0/publish",
    "azureFunctions.projectLanguage": "C#",
    "azureFunctions.projectRuntime": "~4",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.preDeployTask": "publish (functions)"
}
```
extensions.json:
```
{
  "recommendations": [
    "ms-azuretools.vscode-azurefunctions",
    "ms-dotnettools.csharp"
  ]
}
```

Azure Functions v1.7.4
Azure Function Core Tools v.4.0.4736
VSCode: 1.71.0
C#: v1.25.0

The current work around is to pick the process manually vs allowing azurefunctions to find it automatically by changing the launch options

**Comment by MicroFish91** [comment] 2022-08-25 22:24
Closing as a duplicate of #3009

**Closed by MicroFish91** 2022-08-25 22:24 UTC

**Comment by james2432** [comment] 2022-08-26 11:01
Doesn't seem like a duplicate though, this is on windows and the signed certificates for vsdbg are still valid until September 1st 2022
