### ISSUE TITLE
unable to create Azure function app project using the VS code

### ISSUE THREAD

**Issue by amarmanchalagithub** [microsoft/vscode-azurefunctions#2602] opened 2020-12-11 18:54 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

**Comment by amarmanchalagithub** [comment] 2020-12-11 18:55
The issue text was copied to 


Does this occur consistently? 
Repro steps:


1.
2.

Action: azureFunctions.createNewProject
Error type: Error
Error Message: Command "dotnet "c:\Users\aam5268\.vscode\extensions\ms-azuretools.vscode-azurefunctions-1.0.1\resources\dotnetJsonCli\netcoreapp3.0\Microsoft.TemplateEngine.JsonCli.dll" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\itemTemplates-~3.nupkg" --require "c:\Users\aam5268\AppData\Roaming\Code\User\globalStorage\ms-azuretools.vscode-azurefunctions\dotnetTemplates\projectTemplates-~3.nupkg" --operation create --identity Microsoft.AzureFunctions.ProjectTemplate.CSharp.3.x --arg:name "sfsfswewe" --arg:AzureFunctionsVersion v3" failed with exit code "2097158":
{
  "Message": "Could not load template",
  "Status": 2097158,
  "TemplateFullName": "Azure Functions",
  "ResultInfo": null,
  "OutputBaseDirectory": null,
  "CreationEffects": null
}


Version: 1.0.1
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:46:75083
fulfilled extension.bundle.js:46:73829
processTicksAndRejections task_queues.js:94:5
```

</details>
the clipboard.  Please paste it into this window.

**Comment by ejizba** [comment] 2020-12-11 22:03
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2596

**Closed by ejizba** 2020-12-11 22:03 UTC
