### ISSUE TITLE
There is no function under the "Functions" node after deploying a project to a Linux Consumption function app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3967] opened 2024-02-01 10:42 UTC
**OS:** M1 & Linux
**Build Version:** v1.13.2
**Regression:** Previous Release (v1.13.1)

**Repro Steps:**
1. Create a JavaScript project with HTTP Trigger function and open it in VS Code.
2. Create a Node.js Linux Consumption function app.
3. Deploy the JavaScript project to the above function app.
4. Check whether there is a HTTP Trigger function under the "Functions" node.

**Expect:**
There is a HTTP Trigger function under the "Functions" node.

**Actual:**
There is no function under the "Functions" node.
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/d39edf87-1381-49a2-ad79-02b865e01d57)
Output log:
![image](https://github.com/microsoft/vscode-azurefunctions/assets/45614674/1d1b5de8-3692-499b-8850-b204d8e1f536)

**More Info:**
1. This issue also reproduces for a Python Linux Consumption function app.
2. This issue does not reproduce on the function app with App Service Plan or Premium hosting plan.
3. This issue does not reproduce on the previous released Function extension v1.13.1.
4. This issue is unstable on Windows platform.

**Comment by neeklo** [comment] 2024-02-01 12:23
Facing the same issue. Looks like a regression introduced in version 1.13.2
Reverting the plugin to the previous version 1.13.1 via the "Uninstall" > "Install another version..." menu option in VS Code corrects the behavior

**Comment by m-shaverdy-nasery** [comment] 2024-02-01 14:20
Same here! I am wondering what their QA does!!!

**Comment by nturinski** [comment] 2024-02-01 23:49
Big thanks to our testing team @v-ruizh for catching this.

I currently have merged the fix, but I want to do some more testing before releasing. Hopefully we can release the fix tomorrow, but as mentioned by @neeklo, reverting back to the previous version (1.13.1) should be a workaround.

Sorry about the inconvenience!

**Comment by v-ruizh** [comment] 2024-02-02 13:20
Verified this issue on Azure Functions extension 20240201.17, it does not reproduce for .NET, Python and Node.js Function Apps.
But it still **reproduces for Java Linux Consumption Function App** with the below steps.

1. Create a **Java Linux Consumption** Function App.
2. **Expand** the above Function App -> **Expand** "Functions" node.
3. Deploy the Java project to the above Function App.

**More Info:**
1. This issue does not reproduce if deploying a Java project to a **non-expanded Java Linux Consumption Function App**.
2. This issue does not reproduce for Java Function app with App Service Plan or Premium hosting plan.

**Comment by nturinski** [comment] 2024-02-05 23:33
v1.13.3 is released. Updating should fix this issue. Again, I'm really sorry about this critical bug; thanks again for being so quick to report it.

@v-ruizh Could you verify if the issue below is still occurring?

> Verified this issue on Azure Functions extension 20240201.17, it does not reproduce for .NET, Python and Node.js Function Apps. But it still **reproduces for Java Linux Consumption Function App** with the below steps.
> 
> 1. Create a **Java Linux Consumption** Function App.
> 2. **Expand** the above Function App -> **Expand** "Functions" node.
> 3. Deploy the Java project to the above Function App.
> 
> **More Info:**
> 
> 1. This issue does not reproduce if deploying a Java project to a **non-expanded Java Linux Consumption Function App**.
> 2. This issue does not reproduce for Java Function app with App Service Plan or Premium hosting plan.

**Closed by nturinski** 2024-02-05 23:33 UTC
Labels: AT-CTI

**Comment by v-ruizh** [comment] 2024-02-06 08:50
@nturinski Verify this issue on the current released Function extension v1.13.3. It still **reproduces** for the **Java Linux Consumption Function App** with the below steps.
1. Create a **Java Linux Consumption** Function App.
2. **Expand** the above Function App -> **Expand** "Functions" node.
3. Deploy the Java project to the above Function App.

**Comment by jessejiang0214** [comment] 2024-03-18 05:49
v1.13.4 C# project, still exist!!!
