### ISSUE TITLE
Error Message: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

### ISSUE THREAD

**Issue by rahulmodu** [microsoft/vscode-azurefunctions#2166] opened 2020-06-17 11:49 UTC
Action: azureFunctions.deploy
Error type: Error
Error Message: Upload failed: Integrity error: MD5 hash mismatch between the local copy and the uploaded copy.

Version: 0.22.1
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:281:31064
fulfilled extension.bundle.js:281:29201
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment] 2020-06-17 17:10
Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1983

As a workaround you can set "azureFunctions.suppressMd5Validation" to "true" in your VS Code settings

**Closed by EricJizbaMSFT** 2020-06-17 17:10 UTC
