### ISSUE TITLE
Deployment hangs on "Creating zip package..."

### ISSUE THREAD

**Issue by evandropomatti** [microsoft/vscode-azurefunctions#2156] opened 2020-06-12 16:24 UTC
I created a Function App with Python but I'm not able to deploy it using VS Code.

I'm trying to deploy it to the cloud and it never leaves this state:

```
Creating zip package...
```

![image](https://user-images.githubusercontent.com/6530769/84523586-e8e79700-acae-11ea-8109-24b6212e9120.png)

The code is in [my repo](https://github.com/evandropomatti/mb-prototype) and it runs locally with no problems.

Here are some info about my setup:
- Azure Functions Plugin v0.22.1
- WSL Ubuntu 20.04
- Python 3.8.2
- VS Code 1.46.0

**Comment by EricJizbaMSFT** [comment] 2020-06-12 18:01
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2108

**Closed by EricJizbaMSFT** 2020-06-12 18:01 UTC
