### ISSUE TITLE
Add support for typescript watch mode in function app debug 

### ISSUE THREAD

**Issue by aniket7824** [microsoft/vscode-azurefunctions#2051] opened 2020-04-25 06:52 UTC
Please add support so that a typescript based function app keep building in watch mode white debug in vscode is on.

**Comment by EricJizbaMSFT** [comment] 2020-04-27 22:00
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/781

**Closed by EricJizbaMSFT** 2020-04-27 22:00 UTC
