### ISSUE TITLE
Debug Function. Error: Exit code 2

### ISSUE THREAD

**Issue by RPagels** [Microsoft/vscode-azurefunctions#997] opened 2019-02-15 13:03 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

- Followed creating new EventHubTrigger extension.
- Pressed F5 to debug
- Got error.

Action: azureFunctions.pickProcess
Error type: Error
Error Message: Failed to start debugging. Task "host start" failed with exit code "2".

Version: 0.14.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2019-02-15 17:26
@RPagels can you copy the output of the "host start" task?

**Comment by RPagels** [comment] 2019-02-21 17:27
Hi Eric!

File attached.  Please note, working with @Tim Brown(NextDynamic) and we are running a large event in GLR across 6 cities by Mar 10.  Any help is greatly appreciated.  

[TaskHostOutput-Exit Code 2.txt](https://github.com/Microsoft/vscode-azurefunctions/files/2890363/TaskHostOutput-Exit.Code.2.txt)

**Comment by EricJizbaMSFT** [comment] 2019-02-21 17:34
Hmm I see output for `dotnet clean` and `dotnet build`, but not `func host start`. Maybe try running `func host start` in the terminal and see if that gives you an actual error?

I am seeing this warning, which you probably need to fix. You can use a storage account in azure or the storage emulator if on windows. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#configure-the-project-for-local-development
```
Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than HTTP.
```

**Comment by nextdynamic** [comment] 2019-02-21 17:45
Take a look at this output:  func host start is being called just before exit code 2

> Executing task: dotnet clean <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/21/2019 12:39:55 PM.
     1>Project "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\HubwayFunctions.csproj" on node 1 (Clean target(s)).
     1>CoreClean:
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\host.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\local.settings.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\HubwayFunctions.deps.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\HubwayFunctions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\System.Net.Http.Formatting.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Authentication.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Authentication.Core.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Authorization.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Authorization.Policy.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Hosting.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Http.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Http.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Http.Extensions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Http.Features.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.JsonPatch.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Mvc.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Mvc.Core.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Routing.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.Routing.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.AspNetCore.WebUtilities.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.Amqp.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.Documents.ChangeFeedProcessor.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.DocumentDB.Core.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.EventHubs.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.EventHubs.Processor.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.Services.AppAuthentication.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.Host.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.Extensions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.Extensions.CosmosDB.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.EventHubs.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.Extensions.Http.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Azure.WebJobs.Host.Storage.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Build.Framework.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Build.Utilities.Core.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.DotNet.PlatformAbstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.Binder.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.EnvironmentVariables.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.FileExtensions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Configuration.Json.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.DependencyInjection.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.DependencyInjection.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.DependencyModel.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.FileProviders.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.FileProviders.Physical.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.FileSystemGlobbing.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Hosting.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Hosting.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Logging.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Logging.Abstractions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Logging.Configuration.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.ObjectPool.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Options.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Options.ConfigurationExtensions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Extensions.Primitives.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.IdentityModel.Logging.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.IdentityModel.Tokens.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.Net.Http.Headers.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\NCrontab.Signed.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Newtonsoft.Json.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Newtonsoft.Json.Bson.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\System.IdentityModel.Tokens.Jwt.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\System.Runtime.CompilerServices.Unsafe.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\System.Text.Encodings.Web.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\Microsoft.WindowsAzure.Storage.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\runtimes\win7-x64\native\DocumentDB.Spatial.Sql.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\runtimes\win7-x64\native\Microsoft.Azure.Documents.ServiceInterop.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\runtimes\unix\lib\netstandard1.3\System.Text.Encoding.CodePages.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\runtimes\win\lib\netstandard1.3\System.Text.Encoding.CodePages.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.csprojAssemblyReference.cache".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.csproj.CoreCompileInputs.cache".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.AssemblyInfoInputs.cache".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.AssemblyInfo.cs".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.csproj.CopyComplete".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.dll".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\obj\Debug\netcoreapp2.2\HubwayFunctions.pdb".
       _CleanFunctions:
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\extensions.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\HubwayFunctions.pdb".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\HubwayCosmosDBTrigger\function.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\HubwayEventHubTrigger\function.json".
         Deleting file "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\HubwayHttpTrigger\function.json".
         Removing directory "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\".
     1>Done Building Project "C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\HubwayFunctions.csproj" (Clean target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.29

Terminal will be reused by tasks, press any key to close it.

> Executing task: dotnet build <

Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 64.42 ms for C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\HubwayFunctions.csproj.
  HubwayFunctions -> C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\Debug\netcoreapp2.2\bin\HubwayFunctions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.74

Terminal will be reused by tasks, press any key to close it.

> Executing task: func host start <

The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.

**Comment by nextdynamic** [comment] 2019-02-21 17:47
When I run these commands manually from the terminal inside vs code, it works – just not via the debug mode

Dotnet clean
Dotnet build
Func host start

**Comment by EricJizbaMSFT** [comment] 2019-02-21 19:58
Yeah I see "func host start" in the task output, but it's blank. I think there's a bug in VS Code where the first few lines of output can get cut off, so it's hard for me to know what the problem is. Did you _just_ install the func cli? Sometimes you have to restart VS Code to make sure it gets on the PATH

Can you copy the full output of running "func host start" from the command line?

**Comment by nextdynamic** [comment] 2019-02-21 20:09
This is not a fresh install – been using for a few months now.

Runs from the command line:

PS C:\Users\tibrown\Workspace\Hubway\HubwayFunctions> func host start
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 67.53 ms for C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\HubwayFunctions.csproj.
  HubwayFunctions -> C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\output\bin\HubwayFunctions.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.41



                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.4.317 Commit hash: 63e1996b6c281079427e7c9b8a0a1c633988a195)
Function Runtime Version: 2.0.12285.0
[2/21/2019 8:05:24 PM] Starting Rpc Initialization Service.
[2/21/2019 8:05:24 PM] Initializing RpcServer
[2/21/2019 8:05:24 PM] Building host: startup suppressed:False, configuration suppressed: False
[2/21/2019 8:05:24 PM] Reading host configuration file 'C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\output\host.json'
[2/21/2019 8:05:24 PM] Host configuration file read:
[2/21/2019 8:05:24 PM] {
[2/21/2019 8:05:24 PM]   "version": "2.0"
[2/21/2019 8:05:24 PM] }
[2/21/2019 8:05:25 PM] Initializing Host.
[2/21/2019 8:05:25 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[2/21/2019 8:05:25 PM] LoggerFilterOptions
[2/21/2019 8:05:25 PM] {
[2/21/2019 8:05:25 PM]   "MinLevel": "None",
[2/21/2019 8:05:25 PM]   "Rules": [
[2/21/2019 8:05:25 PM]     {
[2/21/2019 8:05:25 PM]       "ProviderName": null,
[2/21/2019 8:05:25 PM]       "CategoryName": null,
[2/21/2019 8:05:25 PM]       "LogLevel": null,
[2/21/2019 8:05:25 PM]       "Filter": "<AddFilter>b__0"
[2/21/2019 8:05:25 PM]     },
[2/21/2019 8:05:25 PM]     {
[2/21/2019 8:05:25 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/21/2019 8:05:25 PM]       "CategoryName": null,
[2/21/2019 8:05:25 PM]       "LogLevel": "None",
[2/21/2019 8:05:25 PM]       "Filter": null
[2/21/2019 8:05:25 PM]     },
[2/21/2019 8:05:25 PM]     {
[2/21/2019 8:05:25 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2/21/2019 8:05:25 PM]       "CategoryName": null,
[2/21/2019 8:05:25 PM]       "LogLevel": null,
[2/21/2019 8:05:25 PM]       "Filter": "<AddFilter>b__0"
[2/21/2019 8:05:25 PM]     }
[2/21/2019 8:05:25 PM]   ]
[2/21/2019 8:05:25 PM] }
[2/21/2019 8:05:25 PM] FunctionResultAggregatorOptions
[2/21/2019 8:05:25 PM] {
[2/21/2019 8:05:25 PM]   "BatchSize": 1000,
[2/21/2019 8:05:25 PM]   "FlushTimeout": "00:00:30",
[2/21/2019 8:05:25 PM]   "IsEnabled": true
[2/21/2019 8:05:25 PM] }
[2/21/2019 8:05:25 PM] SingletonOptions
[2/21/2019 8:05:25 PM] {
[2/21/2019 8:05:25 PM]   "LockPeriod": "00:00:15",
[2/21/2019 8:05:25 PM]   "ListenerLockPeriod": "00:00:15",
[2/21/2019 8:05:25 PM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2/21/2019 8:05:25 PM]   "LockAcquisitionPollingInterval": "00:00:05",
[2/21/2019 8:05:25 PM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2/21/2019 8:05:25 PM] }
[2/21/2019 8:05:25 PM] Starting JobHost
[2/21/2019 8:05:25 PM] Starting Host (HostId=minintcm9uqlc-1899954225, InstanceId=68bcde5e-efed-427c-994a-f81235612fcd, Version=2.0.12285.0, ProcessId=3520, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[2/21/2019 8:05:25 PM] Loading functions metadata
[2/21/2019 8:05:25 PM] 3 functions loaded
[2/21/2019 8:05:25 PM] WorkerRuntime: dotnet. Will shutdown other standby channels
[2/21/2019 8:05:26 PM] Generating 3 job function(s)
[2/21/2019 8:05:27 PM] Found the following functions:
[2/21/2019 8:05:27 PM] Company.Function.HubwayCosmosDBTrigger.Run
[2/21/2019 8:05:27 PM] Company.function.HubwayEventHubTrigger.Run
[2/21/2019 8:05:27 PM] Company.Function.HubwayHttpTrigger.Run
[2/21/2019 8:05:27 PM]
[2/21/2019 8:05:27 PM] Host initialized (1913ms)
[2/21/2019 8:05:30 PM] Host started (4408ms)
[2/21/2019 8:05:30 PM] Job host started
Hosting environment: Production
Content root path: C:\Users\tibrown\Workspace\Hubway\HubwayFunctions\bin\output
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        HubwayHttpTrigger: [GET,POST] http://localhost:7071/api/HubwayHttpTrigger

[2/21/2019

**Comment by EricJizbaMSFT** [comment] 2019-02-21 22:23
I don't see anything wrong in those logs. I think I might know the problem here. Can you post a screenshot of the workspace? I'm curious about your directory structure. We don't work well if your function app project is in a subdirectory of your workspace. We want to improve that, but there's not a simple fix - tracked by https://github.com/Microsoft/vscode-azurefunctions/issues/686

You can try creating a brand new project from VS Code, adding a simple http trigger, and F5-ing. If that works we know it's a problem in your project and not your system. At that point you could change your project structure or I could help give workarounds

**Comment by nextdynamic** [comment] 2019-02-21 22:55
[cid:image003.jpg@01D4CA0E.451C9140]
[cid:image004.jpg@01D4CA0E.451C9140]

**Comment by nextdynamic** [comment] 2019-02-21 23:01
Interesting.

Created a new folder, created a new C# project, created a new http trigger function.


Hit F5 – worked perfect.  No issues with the debugger.

You said you have some work arounds?

**Comment by EricJizbaMSFT** [comment] 2019-02-22 02:44
Okay I've added some workarounds here: https://github.com/Microsoft/vscode-azurefunctions/issues/686#issuecomment-466252387

Please continue the discussion on that thread. Closing this as duplicate.

**Closed by EricJizbaMSFT** 2019-02-22 02:44 UTC
Labels: needs more info

**Comment by RPagels** [comment] 2019-03-08 15:02
Hi Eric!  We ran into another issue when Deploying the Azure Functions to Azure.  The connection strings used in the local.settings.json file, are not getting published in the Function App Application Settings. Is there a setting we are missing?  Is there a local file we are suppose to use instead of local.settings.json? What are best practices for doing this?

**Comment by EricJizbaMSFT** [comment] 2019-03-08 19:04
@Rpagels you can right click on the Application Settings node to upload settings:
![screen shot 2019-03-08 at 11 00 20 am](https://user-images.githubusercontent.com/11282622/54049484-7a558880-4191-11e9-8014-0a54f2a9a31d.png)

This doesn't happen automatically because we assume a lot of people don't want to use the same connection strings for their local testing as they use when deploying to Azure. However we have an open issue to make the above feature more visible: https://github.com/Microsoft/vscode-azurefunctions/issues/1077

**Comment by RPagels** [comment] 2019-03-08 19:43
Perfect, this will work for the labs.  Thank you!
