### ISSUE TITLE
Symlinked directories don't zip properly

### ISSUE THREAD

**Issue by kobyl** [microsoft/vscode-azurefunctions#1115] opened 2019-03-23 00:11 UTC
On windows. With NPM when adding references using "file:...", the zipped deployment package does not resolve the files properly.

Repro steps:
 - Create a library project - lib1
 - Create function lib project - func1.
 - in func1's package.json, add a reference to lib1 using npm's file syntax.
  "lib1": "file../lib1"

  - Deploy to azure. The function will fail to resolve lib1. Viewing the resource, you'll see the www/node_modules/lib is just a text file with "../lib1" in it.

The root seems to be that lib1 doesn't resolve properly during the zip phase.

**Comment by EricJizbaMSFT** [comment] 2019-03-27 17:50
Thanks for filing - I can repro. We'll look into it

**Comment by EricJizbaMSFT** [comment] 2019-05-01 23:24
@kobyl FYI - we just released v0.17.0 including this fix

**Comment by kobyl** [comment] 2019-05-15 03:53
Thx for fixing - unfortunately the fix seems incomplete. :( In my package my files are placed into a dist folder, and the main is set to dist/export.js.

Unfortunately, none of the directories are zipped and deployed with the package, so it's not there.

I guess this might be by design - to avoid zipping up 100s of megs of node modules we don't need?

**Comment by EricJizbaMSFT** [comment] 2019-05-15 15:37
Can you give the exact folder structure of your project? Or just a screenshot of your workspace? So that I can try to reproduce?

We should be zipping most folders by default - if users want to avoid zipping "100s of megs of node modules" they have to manually add that to their `.funcignore` file.

Also what is the value of your `azureFunctions.deploySubpath` setting?

**Comment by kobyl** [comment] 2019-05-16 05:47
Here you go:

The file I need is actually the exports.js and .js.map. I moved had them built into this dir to see what would happen. I see them in the deployment now, but am now having troubles resolving 'azure-storage' of all things.

I don't think I have a .funcignore file, and I don't know where the azureFunctions.deploySubpath is to be found.

Incidentally - is there a way to script this process, or can I upload a file manually? It takes forever to zip the package and send the whole thing up every time from vscode.

```
05/14/2019  08:46 PM    <DIR>          .
05/14/2019  08:46 PM    <DIR>          ..
05/11/2019  07:32 PM    <DIR>          .vscode
05/12/2019  09:22 PM    <DIR>          dist
05/14/2019  08:46 PM            13,679 exports.js
05/14/2019  08:46 PM            52,600 exports.js.map
02/10/2019  08:23 AM               350 index.html
05/12/2019  09:13 PM    <DIR>          node_modules
05/12/2019  09:13 PM           406,882 package-lock.json
05/14/2019  08:46 PM             2,265 package.json
02/05/2019  09:32 AM                56 README.md
05/12/2019  06:11 PM    <DIR>          src
02/05/2019  09:32 AM               435 tsconfig.json
02/05/2019  09:32 AM               519 webpack.config.base.js
02/05/2019  09:32 AM               505 webpack.config.dev.js
05/14/2019  08:46 PM             1,639 webpack.config.js
05/12/2019  07:18 PM           243,796 yarn.lock
05/11/2019  07:32 PM    <DIR>          __mocks__
```

**Comment by kobyl** [comment] 2019-05-16 06:12
Oh - and here's my deployed dir shape:

![image](https://user-images.githubusercontent.com/3729400/57830406-e4c50f00-7766-11e9-9076-5c7a3245db95.png)

The function is actually failing right now because it's missing the node_modules, which contains azure-storage.

**Comment by EricJizbaMSFT** [comment] 2019-05-16 16:11
I'm confused - that doesn't look like an Azure Functions project. Is this a web app or a function app? There seems to be a lot going on here - is this project open source somewhere? Can I take a look? If not - can you create a simple project that repros the same issue and post that?

`azureFunctions.deploySubpath` should be set in `.vscode/settings.json`.

**Comment by kobyln** [comment] 2019-05-16 22:03
Right - this is the project that's imported into the azure functions project with a link.
Prior to this bug using a file link would result in nothing there. Now the top level of the linked project is deployed, but none of the directories are.

ie - my package.json has:

```
  "myOtherProject": "file:../myOtherProjectDir",
```

LMK if that doesn't make sense - I'll try to put together a sample.

Thx!

**Comment by EricJizbaMSFT** [comment] 2019-05-20 23:21
Okay I see what you're saying now. We're including top level files from that linked folder, but not sub-directories. I opened a separate issue here to track with more specific repro steps: https://github.com/microsoft/vscode-azurefunctions/issues/1289 and I'll go ahead and re-close this one

**Closed by EricJizbaMSFT** 2019-05-20 23:21 UTC
Labels: P2, bug
