### ISSUE TITLE
Change in extensionBundle does not automatically give bundle version's templates 

### ISSUE THREAD

**Issue by mhoeger** [microsoft/vscode-azurefunctions#2612] opened 2020-12-23 19:29 UTC
Steps to repro: 
1. Have a host.json with one extension bundle version (ex: "version": "[1.*, 2.0.0)")
2. Try to create a function and see available templates 
3. Change host.json to a different extension bundle version (ex: "version": "[2.*, 3.0.0)")
4. Try to create a function and see available templates have not changed
5. Close and re-open window
6. Templates reflect those for the appropriate extension bundle version

It would be great if I didn't have to close and re-open the window

**Comment by ejizba** [comment] 2021-01-04 19:01
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2547

**Closed by ejizba** 2021-01-04 19:01 UTC
