### ISSUE TITLE
Include inline explanation of selections options during ‘Create Project’ so users can understand configuration options

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azurefunctions#1874] opened 2020-02-05 17:55 UTC
For some of the options in the create project flow, the selection option is not intuitive. Specifically, the authorization levels. Can we include inline text to explain what the three options refer to?

![image](https://user-images.githubusercontent.com/37638436/73868600-99bfc000-47fd-11ea-80c2-9c98a607691c.png)

**Comment by EricJizbaMSFT** [comment] 2020-02-05 19:01
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1788

**Closed by EricJizbaMSFT** 2020-02-05 19:01 UTC
