### ISSUE TITLE
Unable to view my azure function .json via visual studio code

### ISSUE THREAD

**Issue by bennkingy** [microsoft/vscode-azurefunctions#2600] opened 2020-12-11 14:07 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureFunctions.openFile
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿{
  "bindings": [
    {
      "authLevel": "anonymous",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ]
}.

Version: 1.0.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:109835
errorHandler extension.bundle.js:48:165914
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment] 2020-12-11 22:06
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2490

**Closed by ejizba** 2020-12-11 22:06 UTC
