### ISSUE TITLE
Bug: Function are sometimes missing from newly deployed Function Apps

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azurefunctions#1872] opened 2020-02-05 17:43 UTC
Every so often, a new deployed Function app is missing it's function both inside VSC's Azure Functions window, and in the portal. In some cases, I have been able to get the function to re-appear.

**Comment by EricJizbaMSFT** [comment] 2020-02-05 19:06
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1848

**Closed by EricJizbaMSFT** 2020-02-05 19:06 UTC
