### ISSUE TITLE
Not able to add new azure function

### ISSUE THREAD

**Issue by Githamza** [microsoft/vscode-azurefunctions#3408] opened 2022-08-08 08:55 UTC
I opened my project repo as usual , then I noticed that I can't add new azure function

the + icon disappeared:

![image](https://user-images.githubusercontent.com/11578288/183379405-f2e241cb-a47d-44d6-8833-f70fd230d939.png)

**Comment by alexweininger** [comment] 2022-10-31 19:02
Duplicate of #3280. This was fixed in VS Code 1.70.2 https://github.com/microsoft/vscode/releases/tag/1.70.2

**Closed** 2022-10-31 19:03 UTC
