### ISSUE TITLE
There is a word error in the error message of debug

### ISSUE THREAD

**Issue by Elvira-sxr** [microsoft/vscode-azurefunctions#2021] opened 2020-04-07 08:09 UTC
## Configuration:

• VS Code 1.43.2
• JDK 1.8
• Maven 3.3.3
• Azure Functions Core Tool 2.7.2254
• VS Code extensions 
	○ Azure Account 0.8.9
        ○ Debugger for Java 0.25.1
	○ Language Support for Java 0.59.1

## Reproduce steps:
1. Create a java function project
2. Debug Java Function locally
## Result:
Debug error message is wrong
![image](https://user-images.githubusercontent.com/51812626/78645348-fd439800-78e9-11ea-9baa-28bdf67fdfad.png)

**Comment by EricJizbaMSFT** [comment] 2020-04-07 16:43
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/191

**Closed by EricJizbaMSFT** 2020-04-07 16:43 UTC
