### ISSUE TITLE
Fail to deploy the Java project to a basic Java Function App with an error

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3104] opened 2022-04-11 08:54 UTC
**OS:** Win10
**Build Version:** 20220407.4
**VS Code Version-insiders:** 1.67.0-insider (user setup)
**Function Core Tools:** v4

**Repro Steps:**

1. Create a Java project.
2. Create a basic Java Function App.
3. Deploy the Java project to the Java Function App.
4. Check whether succeeds to deploy the Java project to a basic Java Function App.

**Expect:**
Succeed to deploy the Java project to a basic Java Function App.

**Actual:**
Fail to deploy the Java project to a basic Java Function App with an error.
![image](https://user-images.githubusercontent.com/62053665/162687822-c8570550-6433-4c71-b4ea-8cbee1620658.png)
Output logs:
![image](https://user-images.githubusercontent.com/62053665/162687908-13bdec9f-4cfd-4162-ac2f-cfe7d9a68b2b.png)

**More Info:**

1. This issue also reproduces for a Linux Java Function App.
2. This issue doesn't reproduce for other languages.
3. [Unstable] [Codespace] Fail to deploy the Java project to a basic Java Function App with a different error.
![image](https://user-images.githubusercontent.com/62053665/162692716-a87f2990-f6a0-4242-8d51-ae2a0fdb5ffa.png)

**Comment by MateoSaez** [comment] 2022-04-12 13:22
Same issue here.
![image](https://user-images.githubusercontent.com/79751192/162972056-1681e874-3a77-4c67-879d-bd7863325b54.png)

**Comment by alexweininger** [comment] 2022-04-12 19:22
@MateoSaez sorry you ran into this bug, the good news is we are working on a fix for this right now, and we have a development build available if you'd like to try and verify the fix works for us.

---

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the extension .VSIX from our Azure DevOps Pipeline - [Direct download link](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5753365/vsix?itemPath=vsix%2Fvscode-azurefunctions-1.6.2-alpha.vsix) | [View artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45131&view=artifacts&pathAsName=false&type=publishedArtifacts)
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.
1. Navigate to the extensions view and verify the version is `1.6.2-alpha`
![Screen Shot 2022-04-12 at 12 19 33 PM](https://user-images.githubusercontent.com/12476526/163037446-e8232513-1fe6-4d50-83dd-ef155063ab4b.png)

Once installed, attempt to deploy your app as normal. Please let us know if deployment succeeded/failed.

---

Follow along with #2844 for more updates and discussion, we're directing all of these zip deploy issues over there.

**Comment by alexweininger** [comment] 2022-04-12 19:22
Closing as a duplicate of #2844

**Closed by alexweininger** 2022-04-12 19:22 UTC
Labels: AT-CTI

**Comment by alexweininger** [comment] 2022-04-13 19:18
Fix has been released in version [v1.6.2](https://github.com/microsoft/vscode-azurefunctions/releases/tag/v1.6.2) of the extension.
