### ISSUE TITLE
Can't open logstream

### ISSUE THREAD

**Issue by Miura55** [microsoft/vscode-azurefunctions#1434] opened 2019-08-08 01:33 UTC
Repro steps:

1.
2.

Action: postDeploy
Error type: Error
Error Message: This operation is not supported by this app service plan.

Version: 0.17.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
SiteClient.get kudu [as kudu] extension.bundle.js:332:359969
Object.<anonymous> extension.bundle.js:332:832250
o extension.bundle.js:332:831321
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-08-08 15:34
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/589

**Closed by EricJizbaMSFT** 2019-08-08 15:34 UTC
