### ISSUE TITLE
Deploy Issue

### ISSUE THREAD

**Issue by BSJAIN92** [Microsoft/vscode-azurefunctions#920] opened 2019-01-19 17:49 UTC
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: azureFunctions.deploy
Error type: ESOCKETTIMEDOUT
Error Message: ESOCKETTIMEDOUT

Version: 0.13.1
OS: win32

**Comment by EricJizbaMSFT** [comment] 2019-01-29 17:20
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/890

**Closed by EricJizbaMSFT** 2019-01-29 17:20 UTC
