### ISSUE TITLE
Improve the journey for creating a function project and function

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azurefunctions#785] opened 2018-11-05 17:12 UTC
Right now there's a disconnect between creating a function project caused by adding the app to the workspace and reloading the view. The user is required to navigate back to the Azure view to continue the journey (in the case where they are creating a new function) and there should be some way to keep them on track.

**Comment by EricJizbaMSFT** [comment] 2018-11-07 18:50
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/593

**Closed by EricJizbaMSFT** 2018-11-07 18:50 UTC
