### ISSUE TITLE
Cannot retrieve/create an RG when using Azure Functions: Create App in Azure cmd. 

### ISSUE THREAD

**Issue by OKriw** [microsoft/vscode-azurefunctions#3761] opened 2023-07-18 12:05 UTC
Error msg:
Provider "/subscriptions/XXXX/providers/Microsoft.Resources" does not have resource type "resourceGroups".
When trying to create Azure Functions: Create App in Azure  from vscode cmd.
Error message is not helpful enough for m to resolve the issue.
The error pops up after I specify runtime stack.

When using  Azure Functions: Create App in Azure (Advanced) everything is fine.

**Comment by alexweininger** [comment] 2023-07-18 19:52
This is a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/3620, except this is with the updated error message. Please follow along there for updates and if you have questions post them there. Or reach me on Teams.

This is an issue caused by a bug with internal Microsoft subscriptions, which doesn't impact external customers.

There's an ICM here that we've been using to request fixes. The ARM team can fix it by unregistering and registering the Microsoft.Resources provider. https://portal.microsofticm.com/imp/v3/incidents/details/381037873

**Closed by alexweininger** 2023-07-18 19:52 UTC
