### ISSUE TITLE
Failure when trying to push to Function App

### ISSUE THREAD

**Issue by bandrei** [Microsoft/vscode-azurefunctions#451] opened 2018-07-12 07:36 UTC
```
0:32:55 CoblocDocument: Running deployment command...
00:32:55 CoblocDocument: Command: "D:\home\site\deployments\tools\deploy.cmd"
00:32:56 CoblocDocument: Handling Basic Web Site deployment.
00:32:57 CoblocDocument: KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
00:32:57 CoblocDocument: Finished successfully.
00:32:58 CoblocDocument: Running post deployment command(s)...
00:33:01 CoblocDocument: Syncing 0 function triggers with payload size 2 bytes successful.
00:33:01 CoblocDocument: Deployment successful.
00:33:12 CoblocDocument: Waiting for long running command to finish...

```

Although the wizard asks which subscription to deploy to, and identifies my subscriptions correctly, the function is not deployed to the Azure Function App and as you can see, when it's trying to sync the count is 0.

os: Mac 10.13.5 (17F77)
vs code: Version 1.25.0 (1.25.0) 0f080e5267e829de46638128001aeb7ca2d6d50e
extension: 0.9.1

**Comment by EricJizbaMSFT** [comment] 2018-07-12 18:00
Is this a C# project? Did you run a build before deploying? For now you have to make sure you build yourself before deploying. We recently changed the product so that it automatically builds for you, but we haven't released that quite yet: https://github.com/Microsoft/vscode-azurefunctions/issues/223

I've also seen "Syncing 0 function triggers" if I try to deploy to a brand new function app really quickly. However, it goes away if I deploy again.

**Comment by bandrei** [comment] 2018-07-13 23:52
@EricJizbaMSFT I have just tried this, and althoug the project is being built and the deployment is reported in the Azure portal there is still nothing there.

**Comment by bandrei** [comment] 2018-07-13 23:53
Here's another deployment output:

os: macOS 10.13.5 (17F77)
vs code: Version 1.25.0 (1.25.0) 0f080e5267e829de46638128001aeb7ca2d6d50e
azure extension: 0.9.1

```
00:45:42 CoblocTest: Creating zip package...
00:45:44 CoblocTest: Starting deployment...
00:45:53 CoblocTest: Fetching changes.
00:45:53 CoblocTest: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\241i0z3o.zip (4.51 MB) to D:\local\Temp\zipdeploy\extracted
00:45:56 CoblocTest: Updating submodules.
00:45:56 CoblocTest: Preparing deployment for commit id '61fa8a9fd0'.
00:45:57 CoblocTest: Generating deployment script.
00:45:58 CoblocTest: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"'.
00:45:59 CoblocTest: Generating deployment script for Web Site
00:45:59 CoblocTest: Generated deployment script files
00:46:00 CoblocTest: Running deployment command...
00:46:00 CoblocTest: Command: "D:\home\site\deployments\tools\deploy.cmd"
00:46:02 CoblocTest: Handling Basic Web Site deployment.
00:46:04 CoblocTest: KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
00:46:04 CoblocTest: Copying file: '.gitignore'
00:46:04 CoblocTest: Copying file: 'cobloc-document-nation.csproj'
00:46:04 CoblocTest: Copying file: 'host.json'
00:46:04 CoblocTest: Copying file: 'local.settings.json'
00:46:04 CoblocTest: Copying file: '.vscode\extensions.json'
00:46:04 CoblocTest: Copying file: '.vscode\launch.json'
00:46:04 CoblocTest: Copying file: '.vscode\settings.json'
00:46:04 CoblocTest: Copying file: '.vscode\tasks.json'
00:46:04 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\cobloc-document-nation.deps.json'
00:46:04 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\host.json'
00:46:04 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\local.settings.json'
00:46:04 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\cobloc-document-nation.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\cobloc-document-nation.pdb'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Authentication.Abstractions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Authentication.Core.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Authorization.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Authorization.Policy.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Hosting.Abstractions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Http.Abstractions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Http.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Http.Extensions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Http.Features.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.JsonPatch.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Mvc.Abstractions.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Mvc.Core.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll'
00:46:05 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Routing.Abstractions.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.Routing.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.AspNetCore.WebUtilities.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Azure.WebJobs.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Azure.WebJobs.Extensions.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Azure.WebJobs.Extensions.Http.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Azure.WebJobs.Host.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.CSharp.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Data.Edm.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Data.OData.dll'
00:46:06 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.DotNet.PlatformAbstractions.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.Configuration.Abstractions.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.Configuration.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.Configuration.EnvironmentVariables.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.Configuration.FileExtensions.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.Configuration.Json.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.DependencyInjection.Abstractions.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.DependencyModel.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.FileProviders.Abstractions.dll'
00:46:07 CoblocTest: Copying file: 'bin\Debug\netstandard2.0\bin\Microsoft.Extensions.FileProviders.Physical.dll'
00:46:07 CoblocTest: Omitting next output lines...
00:46:15 CoblocTest: Running post deployment command(s)...
00:46:19 CoblocTest: Syncing 0 function triggers with payload size 2 bytes successful.
00:46:19 CoblocTest: Deployment successful.
>>>>>> Deployment to "CoblocTest" completed. <<<<<<
```

**Comment by bandrei** [comment] 2018-07-13 23:54
I've also tried with continous deployment and that works very smoothly, so I am not sure where the problem is.

**Comment by EricJizbaMSFT** [comment] 2018-07-18 16:59
@bandrei I think I figured out where the problem is coming from. In short, we've had some changes in recent releases that made for a confusing experience and we will get this fixed in the next release.

For a longer explanation:
What entry point did you use to deploy? Did you select 'Deploy to Function App' from the file explorer? Like this?
![screen shot 2018-07-18 at 9 40 05 am](https://user-images.githubusercontent.com/11282622/42895378-9d399c18-8a6e-11e8-84c8-6c32bf9e3f2d.png)

The functions explorer used to be in the file explorer window instead of it's own Azure window, so the main deploy entry point used to be this arrow button:
![screen shot 2018-07-18 at 9 32 13 am](https://user-images.githubusercontent.com/11282622/42895485-ed3f6ba2-8a6e-11e8-80dc-9684d4143460.png)

After you click that, it will prompt for a folder like this:
![screen shot 2018-07-18 at 9 32 45 am](https://user-images.githubusercontent.com/11282622/42895497-fa63ed76-8a6e-11e8-8043-c9bf6bff4a66.png)

The key difference is that it includes 'bin/Debug/netstandard2.0' in the path, rather than just using the root path of the workspace. That's actually controlled by the 'azureFunctions.deploySubpath' setting in your `.vscode/settings.json` file.

The bug is that we were ignoring that setting if you used the file explorer entry point from above. The obvious fix is just to append the subPath to the folder path you select, but it's a little confusing because you can actually right click on any folder. I propose we _only_ append the subPath if you right-clicked on the root of the workspace. For example, if the user right clicks on the 'bin/Release/netstandard2.0' subFolder, I don't think it makes sense to append the path. Do you agree with that? My only concern is that it might not be obvious that you can right click on the 'root' of the workspace since your mouse has to be in the empty space below the list of files. Did you find that obvious? Or were you right-clicking on the 'bin' or 'obj' folders just to get the 'Deploy to Function App' menu item to show up?

**Closed** 2018-07-18 20:19 UTC
Labels: P1, bug

**Comment by bandrei** [comment] 2018-07-26 06:21
@EricJizbaMSFT yes, I used the explorer entry point as you described.

**Comment by bandrei** [comment] 2018-07-26 06:21
thanks for fixing it!
