### ISSUE TITLE
Publishing node functions to Linux

### ISSUE THREAD

**Issue by mscoutermarsh** [Microsoft/vscode-azurefunctions#857] opened 2018-12-11 17:40 UTC
Hello 👋 ,

Having trouble finding this documented anywhere. Is it possible to select OS type somehow when 
publishing a new function?

Thanks!

**Comment by EricJizbaMSFT** [comment] 2018-12-11 17:51
@mscoutermarsh you can't create a Linux function app from our extension, yet. That's being tracked by https://github.com/Microsoft/vscode-azurefunctions/issues/811. However if you create one in the portal, you should still be able to deploy to it like normal. Let me know if that doesn't work otherwise I'll close this as a duplicate of 811

**Comment by mscoutermarsh** [comment] 2018-12-11 17:59
@EricJizbaMSFT Thanks! I'll give that a try and let you know.

**Comment by mscoutermarsh** [comment] 2018-12-15 16:59
Gave it a try and unable to deploy.

Here's what I did.

**1. created a new function app via the portal**
![image](https://user-images.githubusercontent.com/155044/50045389-e5863780-0046-11e9-83f0-ac0a92ac68a8.png)

**2. Created a function locally (used the "create function" from within vscode.**
function.json
```json
{
    "disabled": false,
    "bindings": [
      {
        "authLevel": "anonymous",
        "type": "httpTrigger",
        "direction": "in",
        "name": "req",
        "methods": [
          "get",
          "post"
        ]
      },
      {
        "type": "http",
        "direction": "out",
        "name": "res"
      }
    ]
  }  
```
index.js
```javascript
module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
};
```

**3. Then I deployed it by right clicking on the folder an going "Deploy Function App", selected my new Linux app.**

**4. Error message**
```
8:52:32 AM mscccc2: Creating zip package...
8:52:33 AM mscccc2: Starting deployment...
8:52:33 AM mscccc2: Uploading zip package to storage container...
8:52:35 AM mscccc2: Syncing triggers...
Error: Encountered an error (InternalServerError) from host runtime.
```

**Comment by EricJizbaMSFT** [comment] 2019-01-16 19:48
Closing as duplicate of #811 as mentioned above. The InternalServerError should likely be fixed as a part of https://github.com/Microsoft/vscode-azurefunctions/issues/804

**Closed by EricJizbaMSFT** 2019-01-16 19:48 UTC

**Comment by EricJizbaMSFT** [comment] 2019-01-18 23:33
@mscoutermarsh it turns out there is a bug in the functions runtime. If you continue seeing InternalServerError you can try deleting the proxies.json file in your project (assuming you don't have any proxies) as a workaround. See https://github.com/Azure/azure-functions-host/issues/3978 for more info
