### ISSUE TITLE
Fail to deploy Python project to a new function app 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#788] opened 2018-11-06 02:40 UTC
**OS/Platform:** MacOS High Sierra
**Node.js** : V8.12.0
**Extension Version:** [20181105.8](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=102&view=results)

**Repro Steps:**
1. Create a new project with Python language.
2. Create a new function with HTTP trigger template and Function Authorization level.
3. Debug the Python project.
4. Make sure the Python project is open ->Deploy this Python project to a new Azure Function app according to the notification: Create a new function app -> Create a new resource group -> Create a new storage account -> Select EastUS.

**Expect:**
Succeed to deploy to the new function app.

**Actual:**
Fail to deploy with an error dialog.
![h](https://user-images.githubusercontent.com/34729092/48039546-1612b180-e12a-11e8-8486-31e51cf92733.jpg)

**Comment by EricJizbaMSFT** [comment] 2018-11-09 17:45
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/798 (This one was filed first, but that one has more comments already)

@v-dantch could you join that issue and respond to my comments there as well? Specifically can you try creating a linux consumption function app from the portal as described in this comment: https://github.com/Microsoft/vscode-azurefunctions/issues/798#issuecomment-437434135

**Closed by EricJizbaMSFT** 2018-11-09 17:45 UTC
Labels: CTI, bug
