### ISSUE TITLE
Display 'Function host is not running' after deploying C# projects

### ISSUE THREAD

**Issue by v-ruizh** [Microsoft/vscode-azurefunctions#1149] opened 2019-04-02 10:27 UTC
OS: Windows
Node.js: V10.15.0
Build Version: [20190401.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4613)
Azure Functions Core Tools: V2.4.498

Repro Steps:

1. Create a C# project.
2. Create a new function with 'HTTP trigger' template and 'Function' level.
3. Deploy this C# project to Azure Function app.
4. Copy the Function URL to terminal and check the result.

Expect:
Succeed to run the command.

Actual:
Display 'Function host is not running'.
![image](https://user-images.githubusercontent.com/45614674/55394706-7d664d80-5572-11e9-867c-400fee37e0af.png)
The logs shows as below after executing 'Start Streaming Logs' for the Function App.
![image](https://user-images.githubusercontent.com/45614674/55394932-15fccd80-5573-11e9-8baf-d372e9851409.png)

More Info:
This issue don't reproduce for JavaScript and TypeScript project.

**Comment by EricJizbaMSFT** [comment] 2019-04-02 18:52
When you create a function app, the language is set by the app setting `FUNCTIONS_WORKER_RUNTIME`. You would have to change that app setting if you want to deploy a different language. We already have an existing issue to warn users if the local language and remote language don't match. Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/924

**Closed by EricJizbaMSFT** 2019-04-02 18:52 UTC
Labels: AT-CTI
