### ISSUE TITLE
Display an error after deploying a Python project to a function app with Linux OS

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1023] opened 2019-02-22 09:55 UTC
**OS:** All
**Func:** V2.4.317
**Build Version:** [20190222.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3467)

**Repro Steps:**
1. Create a Python project.
2. Debug --> Deploy --> Expand the 'Functions' node and check the result.

**Expect:**
Display a valid function.

**Actual:**
Display an error.
![image](https://user-images.githubusercontent.com/34729092/53234601-bb538600-3644-11e9-9c51-7182877150cf.png)

**More Info:**
This issue does not reproduce for the Python projects created by cli.
![image](https://user-images.githubusercontent.com/34729092/53234631-cf978300-3644-11e9-92b4-ba9e0e030b7c.png)

**Comment by EricJizbaMSFT** [comment] 2019-02-22 17:43
Closing this as duplicate of a few others:
* Failed to copy url for non-anonymous http triggers on linux consumption: https://github.com/Microsoft/vscode-azurefunctions/issues/654
* Make html error with image more readable: https://github.com/Microsoft/vscode-azurefunctions/issues/1025

**Closed by EricJizbaMSFT** 2019-02-22 17:43 UTC
Labels: AT-CTI
