### ISSUE TITLE
Enter steps to reproduce is

### ISSUE THREAD

**Issue by sand-enqos** [Microsoft/vscode-azurefunctions#1078] opened 2019-03-11 09:03 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Forbidden
Error Message: Forbidden

Version: 0.15.0
OS: darwin
VS Code Version: 1.31.1

<details>
<summary>Call Stack</summary>

```
Function.module.exports.j._normalizeError (dist/extension.bundle.js:333:540799)
Object.module.exports.j._processResponse (dist/extension.bundle.js:333:536609)
$.h [as _callback] (dist/extension.bundle.js:333:530461)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.EventEmitter.emit (domain.js:442:20)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:182:13)
$.EventEmitter.emit (domain.js:442:20)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
IncomingMessage.EventEmitter.emit (domain.js:442:20)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-03-11 19:19
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/989

**Closed by EricJizbaMSFT** 2019-03-11 19:19 UTC

**Comment by EricJizbaMSFT** [comment] 2019-03-11 19:20
Closed as duplicate. If you have time, please look at my questions in the other issue and comment there with your answers as we're having a hard time reproducing this bug
