### ISSUE TITLE
When using a VSCode Workspace deploying an Azure Function hangs on Creating zip package...

### ISSUE THREAD

**Issue by sebastianrogers** [microsoft/vscode-azurefunctions#2239] opened 2020-07-13 15:40 UTC
I have an basic function created via Azure Functions.

In VS CodeSpaces when I open a workspace containing the project attempts to deploy the project fail hanging when trying to build the zip file.

When I open the project folder directly it works.

**Comment by EricJizbaMSFT** [comment] 2020-07-13 17:03
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2108

**Closed by EricJizbaMSFT** 2020-07-13 17:03 UTC
