### ISSUE TITLE
While deploy Azure Function from VSCode to Azure

### ISSUE THREAD

**Issue by nielsophey** [Microsoft/vscode-azurefunctions#643] opened 2018-09-23 15:05 UTC
While deploying a Azure Function to Azure from VSCode I get an error Message - but overall the function ist deployed...

Repro steps:
Have a  function in VSCode (https-trigger, javescript) and click deploy 

Action: azureFunctions.deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.10.2
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-09-24 15:05
Thanks for filing - there may have been an outage in Azure Functions. In any case, closing as a duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/645 for further investigation

**Closed by EricJizbaMSFT** 2018-09-24 15:05 UTC
Labels: duplicate
