### ISSUE TITLE
The runtime list of C# language in Function App creation and project creation are inconsistent

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurefunctions#3081] opened 2022-03-21 09:21 UTC
**OS:** All
**Build Version:** 20220315.4
**Function Core Tools:** **v4**
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Azure Functions: Create New Project... -> Select a folder -> Select C# language.
2. Check the .NET runtime list with Azure Functions version ~4.
3. F1 -> Azure Functions: Create Function App in Azure -> Input a function app name -> Enter.
4. Check whether the runtime list in Function App creation and project creation are consistent or not.

**Expect:**
The runtime list in Function App creation and project creation are consistent.

**Actual:**
The runtime list in Function App creation and project creation are inconsistent.
![image](https://user-images.githubusercontent.com/45614674/159233062-0a89f08a-5a0e-4383-bc4f-6867d58006c4.png)

**More Info:**
This issue also reproduces on the previous released Function extension.

**Comment by nturinski** [comment] 2022-03-24 22:35
I can't get this behavior to reproduce on my machine.  Could you show me the output of `dotnet --list-runtimes`?

**Comment by v-ruizh** [comment] 2022-03-25 02:19
You can get the output of `dotnet --list-runtimes` from below.
![image](https://user-images.githubusercontent.com/45614674/160041668-180f84de-c41f-47c5-b241-dff6b3d1b91a.png)

**Comment by ejizba** [comment] 2022-03-28 16:51
@nturinski I think this can be closed as "Not VS Code's fault" because both lists come from external APIs. 

The azure ones come from the stacks API. Source code here: https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks

The local project ones come from the cli feed. Source code here: https://github.com/Azure/azure-functions-tooling-feed/blob/main/cli-feed-v4.json

.NET 5 Isolated is not officially supported on v4, and I don't know if it ever will be. That means the fix would be to remove it from the cli feed, but the team rarely removes things from the cli feed (for the sake of backwards compatibility) and it's already technically "hidden".

I don't know why .NET 6 Isolated is hidden by default from Azure, but again not VS Code's fault.

**Comment by nturinski** [comment] 2022-04-07 22:34
Closing according to boss man's recommendations

**Closed by nturinski** 2022-04-07 22:34 UTC
Labels: needs more info, AT-CTI
