### ISSUE TITLE
Getting error when try to deploy and create function direct from vscode

### ISSUE THREAD

**Issue by MLopesSousa** [microsoft/vscode-azurefunctions#1348] opened 2019-06-19 00:55 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: BadRequest
Error Message: Encountered an error (InternalServerError) from host runtime.

Version: 0.17.1
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:2558997
s extension.bundle.js:262:110821
s extension.bundle.js:164:25754
extension.bundle.js:164:26994extension.bundle.js:164:26994
o extension.bundle.js:208:58625
extension.bundle.js:164:24675extension.bundle.js:164:24675
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:605959
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5462
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18275
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17117
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by MLopesSousa** [comment] 2019-06-19 00:57
This error is happen when I try to deploy a python functions using consumption plan in East US.

**Comment by ionsphere** [comment] 2019-06-19 19:21
Dupe of #1346

**Comment by nturinski** [comment] 2019-06-19 20:28
Hi @MLopesSousa as @ionsphere said, I think that these issues are closely related.  Please follow along with issue in #1346

**Comment by divyagandhii** [comment] 2019-06-19 23:07
can you please confirm what region your app is in?

**Comment by nturinski** [comment] 2019-06-20 18:08
Hi @MLopesSousa,

I think that this should have been resolved now.  Could you try deploying again and let me know the results? Thanks!

**Comment by MLopesSousa** [comment] 2019-06-20 19:19
@nturinski I will try ASAP, thanks :)

**Comment by MLopesSousa** [comment] 2019-06-20 19:20
@divyagandhii East US

**Comment by EricJizbaMSFT** [comment] 2019-07-19 21:33
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1346. This was fixed in Azure a while back.

**Closed by EricJizbaMSFT** 2019-07-19 21:33 UTC
