### ISSUE TITLE
Invalid function URL (httptriggers), and 404 not found

### ISSUE THREAD

**Issue by UtkarshYeolekar** [Microsoft/vscode-azurefunctions#1159] opened 2019-04-08 10:35 UTC
I have created a function with the name  : createproduct. 
Here is the function.json file of it : 

`{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "put"
      ],
      "route": "product/{id}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}`

After deploying, if we click on the get function URL it gives :
https://productssd.azurewebsites.net/api/createproduct

In VS code output : 
HTTP Trigger Urls:
  createproduct: https://productssd.azurewebsites.net/api/createproduct

And while accessing it gives 404, not found.

And if we check url from the azure portal, the url is different, and which is accessible :
https://productssd.azurewebsites.net/api/product

I think that the azure function extension is not checking, whether the routes, have been mentioned in the function.json or not, and they are generating it on the basis of the function name.

**Comment by EricJizbaMSFT** [comment] 2019-04-08 15:23
Thanks for filing - this is a known issue. Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/205

**Closed by EricJizbaMSFT** 2019-04-08 15:23 UTC
