### ISSUE TITLE
Renamed Route is Incorrect

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azurefunctions#1011] opened 2019-02-20 23:12 UTC
I create a route with the name `heroes-get` and then rename it in the `host.json` to `heroes`.

When I right click on the function int he extension and choose "copy url", it copies the `heroes-get` url, which is not what I want. I want the correct one of `heroes`

![image](https://user-images.githubusercontent.com/1202528/53131405-b9050500-353a-11e9-9c29-2faa6bfea9f7.png)

![2019-02-20_18-10-24](https://user-images.githubusercontent.com/1202528/53131537-08e3cc00-353b-11e9-8c3b-3ed478708097.gif)

tagging @fiveisprime

**Comment by EricJizbaMSFT** [comment] 2019-02-27 22:28
Closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/205

**Closed by EricJizbaMSFT** 2019-02-27 22:28 UTC
