### ISSUE TITLE
Create Azure Function cloud app fails for resource group

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurefunctions#3668] opened 2023-05-08 17:52 UTC
Repro: 

1. Use command palette to use **Azure Functions: Create Function App in Azure (Advanced)**
2. Answer prompts until I get to select a resource group.
3. Select create new resource group
4. Enter name which is unique to subscription
5. Notification: internal error: Expected value to be neither null nor undefined
6. Output window shows

```
2023-05-08 17:50:12.686 [error] Error: Internal error: Expected value to be neither null nor undefined: resourceTypeData
	at nonNullValue (/home/node/.vscode-server/extensions/ms-azuretools.vscode-azurefunctions-1.10.5/dist/extension.bundle.js:2:4154216)
	at /home/node/.vscode-server/extensions/ms-azuretools.vscode-azurefunctions-1.10.5/dist/extension.bundle.js:2:3998238
	at Generator.next (<anonymous>)
	at fulfilled (/home/node/.vscode-server/extensions/ms-azuretools.vscode-azurefunctions-1.10.5/dist/extension.bundle.js:2:3996281)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm logged into Azure so that shouldn't be the issue. If I use a resource group that is already created, it works.

**Comment by alexweininger** [comment] 2023-05-09 22:25
Duplicate of #3620, please follow that issue for updates.

**Closed by alexweininger** 2023-05-09 22:25 UTC
