### ISSUE TITLE
Deploy Java Function Project fails: Error Message: Invalid Object

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-azurefunctions#730] opened 2018-10-17 10:51 UTC
Configuration:
```
• VS Code 1.28.1
• JDK 1.8
• Maven 3.5.4
•.Net Core SDK 2.1.403
• Node 8.11.4
• Azure Functions Core Tool 2.0.3
• VS Code extensions 
	○ Azure Account  0.4.3
	○ Debugger for Java 0.14.1
	○ Language Support for Java 0.32.0
•  CI build for vscode-azurefunction extension 0.11.1-alpha (Build#244)
```

Reproduce steps:

1. Create a java function project
2. Deploy Java Function Project to a new function app

Result:
Deploy failed,
![image](https://user-images.githubusercontent.com/41051257/47080802-8de07100-d23b-11e8-9a6b-38502fe4309f.png)

Investigation:
Deploy again, successful. it's not stable repro

**Comment by jdneo** [comment] 2018-11-01 02:09
@ZhengJun003 

Tried several times but not able to repro, any more information could be helpful. 😃 

BTW, I guess it's not `debug fail` but `deploy fail`, right?

**Comment by ZhengJun003** [comment] 2018-11-01 10:32
I test several times today, try to reproduce this bug, but I can't repeat success now. If you don't think it's important, you can turn it off。

**Comment by jdneo** [comment] 2018-11-01 10:51
Closing it for now since it's not reproducible.

For anyone who meets this issue. Please feel free to reopen/comment on this issue.

Thanks.

**Closed by jdneo** 2018-11-01 10:51 UTC
Labels: bug, java
