### ISSUE TITLE
Support Deployments node on Linux Consumption

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurefunctions#1024] opened 2019-02-22 09:56 UTC
**OS:** All
**Func:** V2.4.317
**Build Version:** [20190222.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3467)

**Repro Steps:**
1. Create a new slot for one function app with Linux OS.
2. Expand 'Deployment' node.
3. Check the result.

**Expect:**
Succeed to expand the node.

**Actual:**
Display 'Error: The service is unavailable'.
![image](https://user-images.githubusercontent.com/34729092/53234313-20f34280-3644-11e9-811b-eb1a1724d9ed.png)

**More Info:**
This issues does not reproduce for slots with Windows OS.
![image](https://user-images.githubusercontent.com/34729092/53234304-189b0780-3644-11e9-8ade-af5fea041253.png)

**Comment by EricJizbaMSFT** [comment] 2019-03-14 22:43
The service unavailable error is a little odd, but the platform doesn't support deployments for linux consumption yet. Changed title to reflect that

**Comment by EricJizbaMSFT** [comment] 2019-03-14 22:52
Actually closing as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/1046

**Closed by EricJizbaMSFT** 2019-03-14 22:52 UTC
Labels: AT-CTI, feature
