### ISSUE TITLE
Fail to create a Linux Function App with the Premium hosting plan and "East Asia" location

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurefunctions#2475] opened 2020-10-19 09:43 UTC
**OS:** All
**Build Version:** 20201015.3

**Repro Steps:**
1. Create a Linux Function App with the Premium hosting plan and "East Asia" location.

**Expect:**
Succeed to create the Function App.

**Actual:**
Fail to create the Function App.
![image](https://user-images.githubusercontent.com/57662131/96408781-c7775880-1216-11eb-9df9-fc9f988c71f9.png)
Details in Output:
```
2:23:50 PM: Creating resource group "nicolenet3prelin" in location "eastasia"...
2:23:52 PM: Successfully created resource group "nicolenet3prelin".
2:23:52 PM: Ensuring App Service plan "nicolenet3prelin" exists...
2:23:53 PM: Creating App Service plan "nicolenet3prelin"...
2:24:05 PM: Error: Requested features are not supported in region. Please try another region.
```

**More Info:**
1. This issue doesn't reproduce for Windows Function App.
2. This issue doesn't reproduce when creating a Linux function app with Consumption/App Service Plan hosting plan and "East Asia" location.
3. Succeed to create a Linux Function App with the Premium hosting plan and "East Asia" location in portal.
![image](https://user-images.githubusercontent.com/57662131/96409952-b9c2d280-1218-11eb-840b-bcc1331d6d19.png)

**Comment by EricJizbaMSFT** [comment] 2020-10-19 17:19
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/2258

**Closed by EricJizbaMSFT** 2020-10-19 17:19 UTC
Labels: AT-CTI
