### ISSUE TITLE
Unable to set breakpoints in PowerShell function 

### ISSUE THREAD

**Issue by yobyot** [microsoft/vscode-azurefunctions#2204] opened 2020-07-02 18:42 UTC
I am unable to set breakpoints in a PowerShell function using VS Code with the Azure Functions extension. Debugging the same function script in a console debugging session works fine.

The machine environment is:
- macOS 10.15.5
- pwsh 7.02
- VS Code 1.46.1
- ms-azuretools.vscode-azurefunctions 0.22.1

Linked below are two animated gifs showing the same script on the same machine in debug mode. In both cases, the attempt is to set a breakpoint on line 19 of the function script and when the debugger stops inspect a variable named `$subGuid`

As you can see in the console session, this works.

However, in the VS Code debug session, the script first stops at the "wrong" place. This is [described in the doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-powershell-local#breakall-might-cause-your-debugger-to-break-in-an-unexpected-place) which then says you can set the proper breakpoints.

In my case, it doesn't matter if the breakpoints are set before attaching the debugger or after the first pause, continuing the debugging session in VS Code does not stop at the breakpoints set. The script does run to completion but it produces no console output on any pwsh stream (I am using 6 -- Information).

Here's a link the to [successful console debugging session](https://www.yobyot.com/wp-content/uploads/tempimage/consoledebug.gif).

And here's a link to the [unsuccessful console debugging session](https://www.yobyot.com/wp-content/uploads/tempimage/vscodedebug.gif)

**Comment by EricJizbaMSFT** [comment] 2020-07-07 20:08
Dupe of https://github.com/microsoft/vscode-azurefunctions/issues/1661. At the moment, you have to use `Wait-Debugger` instead of a breakpoint

**Closed by EricJizbaMSFT** 2020-07-07 20:08 UTC

**Comment by yobyot** [comment] 2020-07-07 21:20
Based on #1661, I'm not sure this is a dupe. What you can't see in the recordings is that there _is_ a `Wait-Debugger` statement in the function code. What happens is that when the session attaches to the runspace, the debugger stops in odd places (documented but a disaster of its own) and then whether or not there are breakpoints in the function script, as soon as you hit F11 (step in) or F5 (run) all it does is hang.

All in all, with odd statements debugging directive required in the code, stopping where it isn't supposed to, not stopping where it is, lousy doc/examples and just generally being hard to use you could label PowerShell function local debugging a hot mess, IMHO.

**Comment by EricJizbaMSFT** [comment] 2020-07-07 21:29
> the debugger stops in odd places

Like this? https://github.com/microsoft/vscode-azurefunctions/issues/1660

> All in all, with odd statements debugging directive required in the code, stopping where it isn't supposed to, not stopping where it is, lousy doc/examples and just generally being hard to use you could label PowerShell function local debugging a hot mess, IMHO.

I 100% agree. That's why it's the only language labeled "Preview" when creating a project through our extension:
<img width="370" alt="Screen Shot 2020-07-07 at 2 25 43 PM" src="https://user-images.githubusercontent.com/11282622/86845079-d10cf400-c05d-11ea-897c-ace3cb26e168.png">

Unfortunately, most of the problems stem from PowerShell itself, so we had very little control over on the VS Code side. They are supposed to be fixed in PowerShell 7, which Azure Functions should officially support soon.

**Comment by yobyot** [comment] 2020-07-08 12:29
```
$endlessPreview = $true
while ($endlessPreview) {
    $useability = $null
    $reliability = $null
    $documentation = $null
    Write-Host "Blame the other product"
}
```
