### ISSUE TITLE
Initializing a python project on MacOS for a path with spaces fails

### ISSUE THREAD

**Issue by sradomski** [microsoft/vscode-azurefunctions#1088] opened 2019-03-14 11:10 UTC
Repro steps:

1. Use Microsoft Code to initialize an Azure Function Project for Python
2. Choose any directory that contains spaces in the complete path
3. Watch ". .env/bin/activate && func init ./ --worker-runtime python" fail with bad interpeter

Action: azureFunctions.createFunction
Error type: Error
Error Message: Failed to run ". .env/bin/activate && func init ./ --worker-runtime python" command. Check output window for more details.

Version: 0.15.0
OS: darwin
VS Code Version: 1.32.2

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:1:132939)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:1:132003)
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-03-14 17:02
@sradomski can you copy the contents of the output window? Also - what version of the func cli do you have? I'm on version `2.4.419` and this seems to be working for me.

**Comment by sradomski** [comment] 2019-03-14 21:11
<pre>
Updating .NET templates for runtime "~1" to version "1.8.0"...
You must have the .NET CLI installed to perform this operation.
Command "dotnet '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetTemplates/itemTemplates-~1.nupkg' --require '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetTemplates/projectTemplates-~1.nupkg' --operation list" failed with exit code "127":
/bin/sh: dotnet: command not found

Updating .NET templates for runtime "~2" to version "2.18.3"...
You must have the .NET CLI installed to perform this operation.
Command "dotnet '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetJsonCli/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetTemplates/itemTemplates-~2.nupkg' --require '/Users/sradomski/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.15.0/resources/dotnetTemplates/projectTemplates-~2.nupkg' --operation list" failed with exit code "127":
/bin/sh: dotnet: command not found

Running command: ". .env/bin/activate && func init ./ --worker-runtime python "...
Installing wheel package
Error running 'pip install wheel'. 


Error: Failed to run ". .env/bin/activate && func init ./ --worker-runtime python" command. Check output window for more details.
</pre>

It's a vanilla MS Code installation - seems like I need some <tt>dotnet</tt> command-line tool, but it's not obvious where I would get it and I really appreciated the "don't make me think" approach with the rest of the process.

**Comment by EricJizbaMSFT** [comment] 2019-03-14 21:28
You can safely ignore the dotnet errors. Those only apply if you're trying to using a C# project. Created a separate issue to hide those because I agree they're confusing.

I'm more interested in the output after this line:
```
Running command: ". .env/bin/activate && func init ./ --worker-runtime python "...
```
but unfortunately there's nothing helpful there. Can you try running that command manually in the terminal and see if it works? Wondering if we need to file an issue on the func cli.

Also run `func --version` to see what version of the func cli you're on.

**Comment by sradomski** [comment] 2019-03-14 22:15
<pre>
$ . .env/bin/activate && func init ./ --worker-runtime python
Installing wheel package
Error running 'pip install wheel'. 
</pre>

Not sure if this is any more enlightening 😄

**Comment by EricJizbaMSFT** [comment] 2019-03-14 23:44
Well it tells us the problem is somewhere in the func cli. You could also try this to see if the problem is with the python/pip configuration:
 ```
. .env/bin/activate && pip install wheel
```

**Comment by sradomski** [comment] 2019-03-15 06:44
<pre>
$ . .env/bin/activate && pip install wheel
-bash: /Users/sradomski/Documents/UI/Code/Foo Bar/.env/bin/pip: "/Users/sradomski/Documents/UI/Code/Foo: bad interpreter: No such file or directory
</pre>

**Comment by gfelot** [comment] 2019-04-01 11:44
Same issue here !
```
$ func --version
2.4.498
```
Fresh azurefunction tools installed on my mac.

Any update ?

**Comment by EricJizbaMSFT** [comment] 2019-05-07 17:59
Closing this as I can't repro and since the project creation experience is much simpler now for Python. We used to rely on the func cli and it would install several packages - which is probably where the original error was coming from. We don't do that any more - see https://github.com/microsoft/vscode-azurefunctions/pull/1188 for more info

**Closed by EricJizbaMSFT** 2019-05-07 17:59 UTC
Labels: needs more info
