### ISSUE TITLE
Add an action 'Open in Portal' for 'Deployments' context menu

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurefunctions#847] opened 2018-12-03 09:54 UTC
**OS:** All
**Node.js:** V8.12.0
**Build Number:** [20181201.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1165&view=results)

**Repro Steps:**
1. Expand one function app ->Right click 'Deployments' node -> Check the context menu.

**Expect**:
There shows an action 'Open in Portal' on the context menu.

**Actual**:
There is no action 'Open in Portal' on the context menu.
![actions](https://user-images.githubusercontent.com/34729022/49365486-f0c19500-f721-11e8-8e6c-a1074146173b.png)

**Comment by EricJizbaMSFT** [comment] 2018-12-03 16:48
Added "Deployments" to existing issue. Now closing this as duplicate of https://github.com/Microsoft/vscode-azurefunctions/issues/90

**Closed by EricJizbaMSFT** 2018-12-03 16:48 UTC
Labels: CTI
