### ISSUE TITLE
Trying to publish my function from VSC

### ISSUE THREAD

**Issue by vbrodsky** [microsoft/vscode-azurefunctions#1742] opened 2019-12-08 22:35 UTC
Repro steps:

1.
2.

Action: azureFunctions.deploy
Error type: Unauthorized
Error Message: The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.

Version: 0.20.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2860478extension.bundle.js:218:2860478
s extension.bundle.js:218:111766
s extension.bundle.js:164:25792
extension.bundle.js:164:27034extension.bundle.js:164:27034
o extension.bundle.js:164:670342
extension.bundle.js:164:24705extension.bundle.js:164:24705
$._callback extension.bundle.js:1:636382
$.t._callback.t.callback.t.callback extension.bundle.js:194:5590
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18450
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17282
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment] 2019-12-09 17:38
@vbrodsky were you by chance trying a SignalR learning module? If so, we can close as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1676. If not, please add more detailed repro steps

**Comment by vbrodsky** [comment] 2019-12-10 13:53
@EricJizbaMSFT this is likely to be a similar issue.
- I have created my first Azure function following https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-01. This created a subscription called Dev Env Subscription, subscription id 9471dc89-72db-44b8-bbc1-0ae1eb2795a4
- After a while, I have created a second function and added an output binding to Cosmos DB to it
- Now I am trying to publish my function to Azure from VSC but getting this error

What is my solution? Is it to keep using the default subscription and select another region for my function? Or is it to create another (Consumption) subscription? In the latter case, would I still get my first year with CosmosDB free?

**Comment by EricJizbaMSFT** [comment] 2019-12-20 20:41
Yeah I'm not familiar with the ins and outs of subscriptions, especially all the pricing/free stuff. I would recommend going directly to an Azure team for help: https://azure.microsoft.com/support/options/

From VS Code, you can try using the "Advanced" option when creating a function app to select a different region or plan type (which might be allowed for your subscription). I'm going to go ahead and close this as a duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1583

**Closed by EricJizbaMSFT** 2019-12-20 20:41 UTC
Labels: needs more info
