### ISSUE TITLE
Deployment sometimes fails without message

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azurefunctions#106] opened 2017-12-01 08:16 UTC
1. Deploy the the java function app from vs code to the target function app which already has functions under it.
2. There is message the deployment complete
3. Trigger the function the result is not updated.

**Comment by bsaby** [comment] 2017-12-15 03:29
I find a stable repro steps:

1. First, deploy the functions of project A to a function app: C
2. Then Deploy the functions of project B to the same function app: C

Result:
There is message the deployment of project B complete but the function app is not updated.

**Comment by jdneo** [comment] 2017-12-15 05:23
I can repro this issue according to @bsaby 's steps.

There's a discussion thread here: https://github.com/projectkudu/kudu/issues/2646

In short, the root cause is the deployment will fail because of the *.jar file is in use on server side.

Seems this issue will only occur for Java function. JS functions can do such hot replacement. (I cannot repro this issue for JS functions according to the steps. @EricJizbaMSFT Correct me if I'm wrong)

I try to stop the function app before deployment and start it after deployment on my side. This issue won't occurrd any more. 

@EricJizbaMSFT Do you think the fix should only do the stop and start staff when project type is Java type and leave what is was when it's JS or other language?

**Comment by EricJizbaMSFT** [comment] 2017-12-15 17:48
@jdneo let's try and get the kudu team to fix the bug first. Ideally they handle everything for us and we don't need to start/stop the app. After all - people might be deploying outside of VS Code and running into the same issue.

If the Kudu team can't or won't fix the issue in a reasonable amount of time - then yes we could start/stop the app if it's Java.

**Comment by jdneo** [comment] 2017-12-18 02:08
According to the discussion here: projectkudu/kudu#2646. Kudu team cannot fix it. 

I'll raise a PR for this later.

**Closed** 2017-12-18 19:49 UTC
Labels: bug
