### ISSUE TITLE
Error "{}" trying to create function app in Azure

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurefunctions#560] opened 2018-09-05 01:11 UTC
Repro steps:
Right-click on a subscription -> Create Function App in Azure...
!) error

Action: azureFunctions.createFunctionApp
Error type: RangeError
Error Message: {}

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment] 2018-09-05 16:26
Closing as dupe of https://github.com/Microsoft/vscode-azurefunctions/issues/480

**Closed by EricJizbaMSFT** 2018-09-05 16:26 UTC
