### ISSUE TITLE
There is no option to select a storage account after clicking the "Select storage account" in the dialog

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurefunctions#3186] opened 2022-05-23 10:25 UTC
**OS:** Win10/M1
**Azure Resource Extension Build Version:** 20220522.1
**Azure Function Extension build Version:** 20220522.1
**Regression:** Not a Regression

**Repro Steps:**

1. Create a new project with "Timer Trigger" template.
2. Debug -> Click "Select storage account" in the pop up dialog.
    <img width="248" alt="Screen Shot 2022-05-23 at 18 12 49" src="https://user-images.githubusercontent.com/62053665/169797478-befa0534-bb5a-425b-8342-6102351e7474.png">
3. Check whether the next step is to select a storage account.

**Expect:**
The next step is to select a storage account.

**Actual:**
There is no option to select a storage account.

**Comment by alexweininger** [comment] 2022-06-09 22:45
This might have broken when we changed the pick tree item stuff.

**Comment by nturinski** [comment] 2022-10-27 17:33
@v-mengwe I can't reproduce this issue anymore with the release version. Could you confirm that this is still reproducing?

**Comment by v-ruizh** [comment] 2022-11-03 07:26
@nturinski Verified this issue on Azure Functions build 20221101.1, it does not reproduce now, close it.

**Closed by v-ruizh** 2022-11-03 07:26 UTC
Labels: bug, P2, AT-CTI
